### DISCUSSION TITLE
hub/datasets/

### DISCUSSION THREAD

**Discussion by giscus** [ultralytics/ultralytics#12995] [Docs]
# hub/datasets/

Learn how Ultralytics HUB datasets streamline your ML workflow. Upload, format, validate, access, share, edit or delete datasets for Ultralytics YOLO model training.

https://docs.ultralytics.com/hub/datasets/

**Comment by ninopleno** [comment]
Hi there..... How should my YAML file looks like when uploading my dataset to your hub? I tried all possible combinations based on the instruction in `coco8.yaml` without success. Here is my dataset structure:

```shell
 |-- vehicle_v1/
    |-- images/
        |-- test/
        |-- train/
        |-- val/
    |-- labels/
        |-- test/
        |-- train/
        |-- val/
    |-- vehicle_v1.yaml
```

My YAML file looks like this:

```yaml
path:
train: [vehicle_v1/images/train, vehicle_v1/labels/train]
val: [vehicle_v1/images/val, vehicle_v1/labels/val]
test: [vehicle_v1/images/test, vehicle_v1/labels/test]

names:
  0: Armoured
  1: Civilian

download:

```

Any guidance and feedback are appreciated!
