### DISCUSSION TITLE
I want to make HIC-YOLOv8

### DISCUSSION THREAD

**Discussion by kashinou** [ultralytics/ultralytics#13428] [Q&A]
Hi, I am a beginner in machine learning. In my research I am trying to create HIC-YOLOv8, which is a structure of HIC-YOLOv5 applied to YOLOv8. I have created YOLOv8-p2-cbam.yaml based on the following yolov5s-p2-cbam.yaml. However, an error occurs during training. We do not know the cause of this problem and would appreciate it if you could let us know.

Also, I am Japanese and cannot use English well, so I am using a translation tool. I apologize if there are any wrong expressions.

Translated with DeepL.com (free version)
```
yolov5s-p2-cbam.yaml

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# Parameters
nc: 10  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [2.9434,4.0435, 3.8626,8.5592, 6.8534, 5.9391]
#  - [ 6.5781,12.539, 13.516,7.7115, 11.054,15.861 ]
#  - [ 21.357,11.243, 17.69,22.249, 34.716,19.689 ]
#  - [ 28.238,39.531, 59.706,32.094, 81.914,68.384 ]
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 3, CBAMBottleneck, [1024, 3]],
   [-1, 1, SPPF, [1024, 5]],  # 10
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 14

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [512, False]],  # 18

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],
   [-1, 3, C3, [256, False]], # 22 160*160  p2 head

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 19], 1, Concat, [1]],
   [-1, 3, C3, [512, False]],  # 25  80*80 p3 head

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 15], 1, Concat, [1]],
   [-1, 3, C3, [256, False]], # 28 40*40 p4 head

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 11], 1, Concat, [1]],
   [-1, 3, C3, [1024, False]],  # 31 20*20 p5 head

   [[22, 25, 28, 31], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
```
YOLOv8-p2-cbam.yaml
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 3, CBAM, [1024, 3]]
  - [-1, 1, SPPF, [1024, 5]]  # 10

# YOLOv8.0n head
head:
  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 14

  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [512]]  # 18 (P3/8-small)

  - [-1, 1, Conv, [256, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]
  - [-1, 3, C2f, [256]]  # 22  160*160 p3 head

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 19], 1, Concat, [1]]
  - [-1, 3, C2f, [512]] # 25 80*80 p4 head

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [256]]  # 28 40*40 p4 head

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 11], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 31

  - [[22, 25, 28, 31], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```
![スクリーンショット 2024-06-07 171749](https://github.com/ultralytics/ultralytics/assets/108340200/f35ed881-afb3-4691-a507-1256aa9d42d7)

**Comment by pderrenger** [comment]
Hello,

Thank you for reaching out and sharing the details of the issue you're encountering with your HIC-YOLOv8 model adaptation. It's great to see you applying advanced configurations to YOLOv8!

To better assist you, could you please provide the specific error message you're receiving during training? This will help pinpoint the potential causes and suggest more accurate solutions.

Additionally, ensure that all custom modules like `CBAM` and `C2f` are correctly implemented and integrated within the YOLOv8 framework. Sometimes, discrepancies in module definitions or mismatches in expected input and output dimensions can lead to errors during training.

Looking forward to your response to help you resolve this issue effectively!

**Comment by kashinou** [comment]
I made modifications from the code that was mentioned earlier, but another error occurred, so I would like to see the modified code and the new error that occurred.


yolov5s-p2-involution-cbam.yaml
```
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 10  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [2.9434,4.0435, 3.8626,8.5592, 6.8534, 5.9391]
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 3, CBAMBottleneck, [1024, 3]],
   [-1, 1, SPPF, [1024, 5]],  # 10
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Involution, [1024, 1, 1]],
   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 15

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [512, False]],  # 19

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],
   [-1, 3, C3, [256, False]], # 23 160*160  p2 head

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 19], 1, Concat, [1]],
   [-1, 3, C3, [512, False]],  # 26  80*80 p3 head

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 15], 1, Concat, [1]],
   [-1, 3, C3, [256, False]], # 29 40*40 p4 head

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 11], 1, Concat, [1]],
   [-1, 3, C3, [1024, False]],  # 32 20*20 p5 head

   [[23, 26, 29, 32], 1, Detect, [nc, anchors]],  # Detect(P2, P3, P4, P5)
  ]
```

YOLOv8-cbam-involution.yaml

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]    #2
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]   
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]    
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, CBAM, [1024, 3]]
  - [-1, 1, SPPF, [1024, 5]]  # 10

# YOLOv8.0n head
head:
  - [-1, 1, Involution, [1024, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 14

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 17 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]
  - [-1, 3, C2f, [128]]  # 20  160*160 p3 head

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 17], 1, Concat, [1]]
  - [-1, 3, C2f, [256]] # 23 80*80 p4 head

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 14], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 26 40*40 p4 head

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 29

  - [[20, 23, 26, 29], 1, Detect, [nc]]  # Detect(P3, P4, P5)

```

in ultralytics/ultralytics/nn/modules/block.py



```
# Ultralytics YOLO 🚀, AGPL-3.0 license
import torch
import torch.nn as nn
import torch.nn.functional as F

from .conv import Conv, DWConv, GhostConv, LightConv, RepConv
from .transformer import TransformerBlock

__all__ = ('DFL', 'HGBlock', 'HGStem', 'SPP', 'SPPF', 'C1', 'C2', 'C3', 'C2f', 'C3x', 'C3TR', 'C3Ghost',
           'GhostBottleneck', 'Bottleneck', 'BottleneckCSP', 'Proto', 'RepC3', 'CBAM', 'Involution')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class ChannelAttention(nn.Module):

    def __init__(self, in_planes, ratio=16):
        """
        Initialize the Channel Attention module.
        Args:
            in_planes (int): Number of input channels.
            ratio (int): Reduction ratio for the hidden channels in the channel attention block.
        """
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.f1 = nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False)
        self.relu = nn.ReLU()
        self.f2 = nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        """
        Forward pass of the Channel Attention module.
        Args:
            x (torch.Tensor): Input tensor.
        Returns:
            out (torch.Tensor): Output tensor after applying channel attention.
        """
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            avg_out = self.f2(self.relu(self.f1(self.avg_pool(x))))
            max_out = self.f2(self.relu(self.f1(self.max_pool(x))))
            out = self.sigmoid(avg_out + max_out)
            return out


class SpatialAttention(nn.Module):

    def __init__(self, kernel_size=7):
        """
        Initialize the Spatial Attention module.
        Args:
            kernel_size (int): Size of the convolutional kernel for spatial attention.
        """
        super().__init__()
        assert kernel_size in (3, 7), 'kernel size must be 3 or 7'
        padding = 3 if kernel_size == 7 else 1
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        """
        Forward pass of the Spatial Attention module.
        Args:
            x (torch.Tensor): Input tensor.
        Returns:
            out (torch.Tensor): Output tensor after applying spatial attention.
        """
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            avg_out = torch.mean(x, dim=1, keepdim=True)
            max_out, _ = torch.max(x, dim=1, keepdim=True)
            x = torch.cat([avg_out, max_out], dim=1)
            x = self.conv(x)
            return self.sigmoid(x)


class CBAM(nn.Module):
    # ch_in, ch_out, shortcut, groups, expansion, ratio, kernel_size
    def __init__(self, c1, c2, kernel_size=3, shortcut=True, g=1, e=0.5, ratio=16):
        """
        Initialize the CBAM (Convolutional Block Attention Module) .
        Args:
            c1 (int): Number of input channels.
            c2 (int): Number of output channels.
            kernel_size (int): Size of the convolutional kernel.
            shortcut (bool): Whether to use a shortcut connection.
            g (int): Number of groups for grouped convolutions.
            e (float): Expansion factor for hidden channels.
            ratio (int): Reduction ratio for the hidden channels in the channel attention block.
        """
        super().__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c_, c2, 3, 1, g=g)
        self.add = shortcut and c1 == c2
        self.channel_attention = ChannelAttention(c2, ratio)
        self.spatial_attention = SpatialAttention(kernel_size)

    def forward(self, x):
        """
        Forward pass of the CBAM .
        Args:
            x (torch.Tensor): Input tensor.
        Returns:
            out (torch.Tensor): Output tensor after applying the CBAM bottleneck.
        """
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            x2 = self.cv2(self.cv1(x))
            out = self.channel_attention(x2) * x2
            out = self.spatial_attention(out) * out
            return x + out if self.add else out

class Involution(nn.Module):

    def __init__(self, c1, c2, kernel_size, stride):
        """
        Initialize the Involution module.
        Args:
            c1 (int): Number of input channels.
            c2 (int): Number of output channels.
            kernel_size (int): Size of the involution kernel.
            stride (int): Stride for the involution operation.
        """
        super().__init__()
        self.kernel_size = kernel_size
        self.stride = stride
        self.c1 = c1
        reduction_ratio = 1
        self.group_channels = 16
        self.groups = self.c1 // self.group_channels
        self.conv1 = Conv(c1, c1 // reduction_ratio, 1)
        self.conv2 = Conv(c1 // reduction_ratio, kernel_size ** 2 * self.groups, 1, 1)

        if stride > 1:
            self.avgpool = nn.AvgPool2d(stride, stride)
        self.unfold = nn.Unfold(kernel_size, 1, (kernel_size - 1) // 2, stride)

    def forward(self, x):
        """
        Forward pass of the Involution module.
        Args:
            x (torch.Tensor): Input tensor.
        Returns:
            out (torch.Tensor): Output tensor after applying the involution operation.
        """
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            weight = self.conv2(x)
            b, c, h, w = weight.shape
            weight = weight.view(b, self.groups, self.kernel_size ** 2, h, w).unsqueeze(2)
            out = self.unfold(x).view(b, self.groups, self.group_channels, self.kernel_size ** 2, h, w)
            out = (weight * out).sum(dim=3).view(b, self.c1, h, w)

            return out
```

in ultralytics/ultralytics/nn/modules/tasks.py

```
# Ultralytics YOLO 🚀, AGPL-3.0 license

import contextlib
from copy import deepcopy
from pathlib import Path

import torch
import torch.nn as nn

from ultralytics.nn.modules import (AIFI, C1, C2, C3, C3TR, SPP, SPPF, Bottleneck, BottleneckCSP, C2f, C3Ghost, C3x,
                                    Classify, Concat, Conv, Conv2, ConvTranspose, Detect, DWConv, DWConvTranspose2d,
                                    Focus, GhostBottleneck, GhostConv, HGBlock, HGStem, Pose, RepC3, RepConv,
                                    RTDETRDecoder, Segment, CBAM, Involution)
from ultralytics.utils import DEFAULT_CFG_DICT, DEFAULT_CFG_KEYS, LOGGER, colorstr, emojis, yaml_load
from ultralytics.utils.checks import check_requirements, check_suffix, check_yaml
from ultralytics.utils.loss import v8ClassificationLoss, v8DetectionLoss, v8PoseLoss, v8SegmentationLoss
from ultralytics.utils.plotting import feature_visualization
from ultralytics.utils.torch_utils import (fuse_conv_and_bn, fuse_deconv_and_bn, initialize_weights, intersect_dicts,
                                           make_divisible, model_info, scale_img, time_sync)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def parse_model(d, ch, verbose=True):  # model_dict, input_channels(3)
    """Parse a YOLO model.yaml dictionary into a PyTorch model."""
    import ast

    # Args
    max_channels = float('inf')
    nc, act, scales = (d.get(x) for x in ('nc', 'activation', 'scales'))
    depth, width, kpt_shape = (d.get(x, 1.0) for x in ('depth_multiple', 'width_multiple', 'kpt_shape'))
    if scales:
        scale = d.get('scale')
        if not scale:
            scale = tuple(scales.keys())[0]
            LOGGER.warning(f"WARNING ⚠️ no model scale passed. Assuming scale='{scale}'.")
        depth, width, max_channels = scales[scale]

    if act:
        Conv.default_act = eval(act)  # redefine default activation, i.e. Conv.default_act = nn.SiLU()
        if verbose:
            LOGGER.info(f"{colorstr('activation:')} {act}")  # print

    if verbose:
        LOGGER.info(f"\n{'':>3}{'from':>20}{'n':>3}{'params':>10}  {'module':<45}{'arguments':<30}")
    ch = [ch]
    layers, save, c2 = [], [], ch[-1]  # layers, savelist, ch out
    for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):  # from, number, module, args
        m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
        for j, a in enumerate(args):
            if isinstance(a, str):
                with contextlib.suppress(ValueError):
                    args[j] = locals()[a] if a in locals() else ast.literal_eval(a)

        n = n_ = max(round(n * depth), 1) if n > 1 else n  # depth gain
        if m in (Classify, Conv, ConvTranspose, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, Focus,
                 BottleneckCSP, C1, C2, C2f, C3, C3TR, C3Ghost, nn.ConvTranspose2d, DWConvTranspose2d, C3x, RepC3, CBAM, Involution):
            c1, c2 = ch[f], args[0]
            if c2 != nc:  # if c2 not equal to number of classes (i.e. for Classify() output)
                c2 = make_divisible(min(c2, max_channels) * width, 8)

            args = [c1, c2, *args[1:]]
            if m in (BottleneckCSP, C1, C2, C2f, C3, C3TR, C3Ghost, C3x, RepC3, CBAM, Involution):
                args.insert(2, n)  # number of repeats
                n = 1
        elif m is AIFI:
            args = [ch[f], *args]
        elif m in (HGStem, HGBlock):
            c1, cm, c2 = ch[f], args[0], args[1]
            args = [c1, cm, c2, *args[2:]]
            if m is HGBlock:
                args.insert(4, n)  # number of repeats
                n = 1

        elif m is nn.BatchNorm2d:
            args = [ch[f]]
        elif m is Concat:
            c2 = sum(ch[x] for x in f)
        elif m in (Detect, Segment, Pose):
            args.append([ch[x] for x in f])
            if m is Segment:
                args[2] = make_divisible(min(args[2], max_channels) * width, 8)
        elif m is RTDETRDecoder:  # special case, channels arg must be passed in index 1
            args.insert(1, [ch[x] for x in f])
        else:
            c2 = ch[f]

        m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
        t = str(m)[8:-2].replace('__main__.', '')  # module type
        m.np = sum(x.numel() for x in m_.parameters())  # number params
        m_.i, m_.f, m_.type = i, f, t  # attach index, 'from' index, type
        if verbose:
            LOGGER.info(f'{i:>3}{str(f):>20}{n_:>3}{m.np:10.0f}  {t:<45}{str(args):<30}')  # print
        save.extend(x % i for x in ([f] if isinstance(f, int) else f) if x != -1)  # append to savelist
        layers.append(m_)
        if i == 0:
            ch = []
        ch.append(c2)
    return nn.Sequential(*layers), sorted(save)


```
When I tried to train using YOLOv8-cbam-involution.yaml
```
Traceback (most recent call last):
  File "C:\Users\ukkyo\newyolov8\train.py", line 1, in <module>
    from ultralytics import YOLO
  File "C:\Users\ukkyo\newyolov8\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\Users\ukkyo\newyolov8\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\Users\ukkyo\newyolov8\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\Users\ukkyo\newyolov8\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\Users\ukkyo\newyolov8\ultralytics\engine\model.py", line 9, in <module>
    from ultralytics.hub.utils import HUB_WEB_ROOT
  File "C:\Users\ukkyo\newyolov8\ultralytics\hub\__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "C:\Users\ukkyo\newyolov8\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\ukkyo\newyolov8\ultralytics\data\base.py", line 19, in <module>
    from .utils import HELP_URL, IMG_FORMATS
  File "C:\Users\ukkyo\newyolov8\ultralytics\data\utils.py", line 19, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "C:\Users\ukkyo\newyolov8\ultralytics\nn\__init__.py", line 3, in <module>
    from .tasks import (BaseModel, ClassificationModel, DetectionModel, SegmentationModel, attempt_load_one_weight,
  File "C:\Users\ukkyo\newyolov8\ultralytics\nn\tasks.py", line 10, in <module>
    from ultralytics.nn.modules import (AIFI, C1, C2, C3, C3TR, SPP, SPPF, Bottleneck, BottleneckCSP, C2f, C3Ghost, C3x,
ImportError: cannot import name 'Involution' from 'ultralytics.nn.modules' (C:\Users\ukkyo\newyolov8\ultralytics\nn\modules\__init__.py)
```
