### DISCUSSION TITLE
Scaleup in LetterBox

### DISCUSSION THREAD

**Discussion by Li-Yidong** [ultralytics/ultralytics#16475] [Q&A] [answered]
Hi, 
I have a doubt about `scaleup` in `LetterBox`. When doing training by default settings, will `scaleup` be `True` or `False`?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Li-Yidong, thank you for reaching out about Ultralytics 🚀! We suggest checking the [Docs](https://docs.ultralytics.com) for answers to common questions, which cover [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage.

For questions about the `scaleup` setting in `LetterBox`, it would be helpful to share a bit more context, such as the training configuration you are using. This will assist our engineers in providing a more accurate response. If you suspect there's a bug 🐛, please include a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us investigate.

Join our vibrant Ultralytics community for real-time discussions on [Discord](https://ultralytics.com/discord) 🎧. For more in-depth conversation, [Discourse](https://community.ultralytics.com) and our [Subreddit](https://reddit.com/r/ultralytics) are great places to connect and share knowledge.

## Upgrade

Ensure you're using the latest `ultralytics` package by upgrading your installation:

```bash
pip install -U ultralytics
```

To avoid any compatibility issues, use [**Python>=3.8**](https://www.python.org/) and [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

## Environments

YOLOv8 can be run in several pre-verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** with [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **AWS** with [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker** with [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Currently, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, ensuring the correct operation of all YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/).

This response is automated, but an Ultralytics engineer will help you soon! 😊

**Comment by glenn-jocher** [comment]
@Li-Yidong by default, `scaleup` is set to `True` during training in `LetterBox`.

**Reply by Li-Yidong** [reply]
@glenn-jocher Thanks for your response. Is it possible that set `scaleup` to `False` during traing?

**Reply by glenn-jocher** [reply, marked as answer]
@Li-Yidong yes, you can set `scaleup` to `False` during training by modifying the augmentation settings in your configuration.

**Reply by Li-Yidong** [reply]
@glenn-jocher I added `scaleup: False` into `yolov8m-obb.yaml` and its runing well. But I didn't find `scaleup` in `https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml`. Is it just a document issue or something else?
The yaml file is as below: 
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 Oriented Bounding Boxes (OBB) model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect
 
# Parameters
nc: 4  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs
 
scaleup: False
 
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
 
# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12
 
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)
 
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)
 
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)
 
  - [[15, 18, 21], 1, OBB, [nc, 1]]  # OBB(P3, P4, P5)
```
