### DISCUSSION TITLE
Ultralytics 支持的模型 - Ultralytics YOLOv8 文档

### DISCUSSION THREAD

**Discussion by giscus** [ultralytics/ultralytics#6903] [Docs]
# Ultralytics 支持的模型 - Ultralytics YOLOv8 文档

探索 Ultralytics 支持的多样化 YOLO 系列、SAM、MobileSAM、FastSAM、YOLO-NAS 和 RT-DETR 模型。开启您的 CLI 和 Python 使用示例之旅。

https://docs.ultralytics.com/zh/models/

**Comment by grf-hlz** [comment]
怎么弄配置文件 *.yaml

**Reply by pderrenger** [reply]
@grf-hlz 配置文件 `*.yaml` 用于定义 YOLOv8 模型的训练和验证参数，包括模型结构、数据集、超参数等。创建和修改这些文件很简单，只需遵循 YAML 语法规则即可。以下是一个基本的配置文件示例和说明：

```yaml
# 模型配置
model: yolov8n.yaml  # 模型定义文件路径

# 数据集配置
data: coco128.yaml  # 数据集定义文件路径

# 训练参数
epochs: 100  # 训练周期数
batch: 16  # 批量大小
imgsz: 640  # 输入图像尺寸

# 优化器配置
optimizer: SGD  # 优化器类型

# 其他设置
device: 0  # 训练使用的设备编号
```

要创建或修改配置文件，请按照以下步骤操作：

1. 使用文本编辑器打开一个新的 `.yaml` 文件。
2. 按照上面的示例格式填写您的配置参数。
3. 保存文件，并确保文件扩展名为 `.yaml`。

您可以在我们的文档中找到更多关于配置文件的详细信息和高级选项。📘🔧
