### DISCUSSION TITLE
Additional augmentations needed

### DISCUSSION THREAD

**Discussion by RanaShiva** [ultralytics/ultralytics#8725] [Q&A]
Hi, for a project I need to apply a few augmentations that I could not find provided in the default.yaml file. 
These are - random resizing and cropping, brightness and contrast, and blur and noise. Is there some way that I can do so using yolov8 during training?
While going through the documentation I came across this `ultralytics.data.augment.Albumentations`.
 If this can be helpful, then can you please provide me a working integrated code for the train mode? Thanks

**Comment by pderrenger** [comment]
Hello! 😊

Absolutely, you can integrate additional augmentations using `Albumentations` with YOLOv8. Here's a quick example on how you can do this for training:

First, ensure you have `albumentations` installed:
```bash
pip install albumentations
```

Then, you can define your custom augmentation pipeline in your training script like so:

```python
from ultralytics import YOLO, Albumentations
import albumentations as A

# Define your custom augmentations
custom_augmentations = Albumentations([
    A.RandomResizedCrop(height=640, width=640),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2),
    A.GaussianBlur(blur_limit=(3, 7)),
    A.GaussNoise(var_limit=(10.0, 50.0)),
])

# Load your model
model = YOLO('yolov8n.pt', augment=custom_augmentations)

# Train with custom augmentations
results = model.train(data='coco128.yaml', epochs=100, imgsz=640)
```

This code snippet integrates `Albumentations` directly into the YOLOv8 training process, applying the specified augmentations randomly during training. Adjust the parameters as needed for your project!

Hope this helps! Let us know if you have any more questions.

**Reply by RanaShiva** [reply]
ImportError: cannot import name 'Albumentations' from 'ultralytics'

It's actually present here:
from ultralytics.data.augment import Albumentations

**Reply by RanaShiva** [reply]
Also this error -     model = YOLO('yolov8n.pt', augment=True)
TypeError: __init__() got an unexpected keyword argument 'augment'

**Reply by pderrenger** [reply]
Hello! 😊

Apologies for the confusion earlier. It seems there was a slight mix-up in the usage example. For integrating custom augmentations with YOLOv8, you don't pass the augmentations directly through the `YOLO` model initialization. Instead, you should define your custom augmentation pipeline and then pass it to the `train` method. Here's a corrected snippet:

```python
from ultralytics import YOLO
from ultralytics.data.augment import Albumentations
import albumentations as A

# Define your custom augmentations
custom_augmentations = Albumentations([
    A.RandomResizedCrop(height=640, width=640),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2),
    A.GaussianBlur(blur_limit=(3, 7)),
    A.GaussNoise(var_limit=(10.0, 50.0)),
])

# Load your model
model = YOLO('yolov8n.pt')

# Train with custom augmentations
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, augment=custom_augmentations)
```

And regarding the `TypeError`, the `augment` parameter should indeed be used in the `train` method, not during model initialization. The corrected example above should clarify this usage. 

Hope this helps, and let me know if there's anything else you need!

**Reply by dkumza** [reply]
Intresting solution to use augmentations by adding Albumentations to training!
But i need more explanation how to implement this to my training script.
I'm doing as you recommending, but i have no luck:
`results = model.train(data='data.yaml', imgsz=640, epochs=1, patience=50, cache=True, lr0=0.001, optimizer='AdamW', augment=custom_augmentations)`
                    
I'm getting this error:
`TypeError: 'augment=<ultralytics.data.augment.Albumentations object at 0x7fc0b74a4290>' is of invalid type Albumentations. 'augment' must be a bool (i.e. 'augment=True' or 'augment=False')
`

**Reply by pderrenger** [reply]
Hey there! 👋

It seems like there's a bit of a mix-up with how custom augmentations are handled. Unfortunately, in the current YOLOv8 implementation, you can't directly pass an `Albumentations` object through the `augment` parameter in the `train` method. The `augment` parameter is designed to accept a boolean value to toggle the usage of predefined augmentations.

However, if you're looking to integrate `Albumentations` into your YOLOv8 training process, you'd need to customize the data loading process to apply these augmentations yourself before feeding the data into the model for training. The recommended place for this integration is within your dataset class.

Here's a quick example of how you can manually integrate Albumentations:

```python
import albumentations as A
from ultralytics.data.datasets import LoadImagesAndLabels

# Define your Albumentations-based augmentations
custom_augmentations = A.Compose([
    A.RandomResizedCrop(height=640, width=640),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2),
    A.GaussianBlur(blur_limit=(3, 7)),
    A.GaussNoise(var_limit=(10.0, 50.0)),
])

# Customize the LoadImagesAndLabels dataset
dataset = LoadImagesAndLabels(path='path/to/your/dataset', img_size=640, augment=custom_augmentations)

# Now, use this dataset for training somehow
# This step requires a bit more customization depending on your specific usage
```

Do note this is a more advanced customization and might require a deeper dive into the YOLOv8 data loading mechanisms. For now, directly passing `augment=custom_augmentations` as a parameter to `model.train()` won't work due to the current method's constraints. 

Thanks for reaching out, and let me know if there's anything else I can help with!

**Reply by whittenator** [reply]
> Intresting solution to use augmentations by adding Albumentations to training! But i need more explanation how to implement this to my training script. I'm doing as you recommending, but i have no luck: `results = model.train(data='data.yaml', imgsz=640, epochs=1, patience=50, cache=True, lr0=0.001, optimizer='AdamW', augment=custom_augmentations)`
> 
> I'm getting this error: `TypeError: 'augment=<ultralytics.data.augment.Albumentations object at 0x7fc0b74a4290>' is of invalid type Albumentations. 'augment' must be a bool (i.e. 'augment=True' or 'augment=False') `

They are just auto replying with ChatGPT, don't listen to a word they say now, 99% of the time its hallucination. The only way to add additional augmentations is to edit the augment.py file or monkey patch your code like so:
```python
"""
This script trains a YOLOv8 model using the specified dataset and hyperparameters.

Usage:
    python train_yolov8.py --config path/to/training_parameters.yaml

Arguments:
    --config: Path to the training parameters YAML file.
"""

import argparse
import yaml
from ultralytics import YOLO
from ultralytics.data.augment import Albumentations
from ultralytics.utils import LOGGER, colorstr
from ultralytics.utils.checks import check_version

def __init__(self, p=1.0):
        """
        Initialize the Albumentations transform object for YOLO bbox formatted parameters.

        This class applies various image augmentations using the Albumentations library, including Blur, Median Blur,
        conversion to grayscale, Contrast Limited Adaptive Histogram Equalization, random changes of brightness and
        contrast, RandomGamma, and image quality reduction through compression.

        Args:
            p (float): Probability of applying the augmentations. Must be between 0 and 1.

        Attributes:
            p (float): Probability of applying the augmentations.
            transform (albumentations.Compose): Composed Albumentations transforms.
            contains_spatial (bool): Indicates if the transforms include spatial transformations.

        Raises:
            ImportError: If the Albumentations package is not installed.
            Exception: For any other errors during initialization.

        Examples:
            >>> transform = Albumentations(p=0.5)
            >>> augmented = transform(image=image, bboxes=bboxes, class_labels=classes)
            >>> augmented_image = augmented['image']
            >>> augmented_bboxes = augmented['bboxes']

        Notes:
            - Requires Albumentations version 1.0.3 or higher.
            - Spatial transforms are handled differently to ensure bbox compatibility.
            - Some transforms are applied with very low probability (0.01) by default.
        """
        self.p = p
        self.transform = None
        prefix = colorstr("albumentations: ")

        try:
            import albumentations as A

            check_version(A.__version__, "1.0.3", hard=True)  # version requirement

            # List of possible spatial transforms
            spatial_transforms = {
                "Affine",
                "BBoxSafeRandomCrop",
                "CenterCrop",
                "CoarseDropout",
                "Crop",
                "CropAndPad",
                "CropNonEmptyMaskIfExists",
                "D4",
                "ElasticTransform",
                "Flip",
                "GridDistortion",
                "GridDropout",
                "HorizontalFlip",
                "Lambda",
                "LongestMaxSize",
                "MaskDropout",
                "MixUp",
                "Morphological",
                "NoOp",
                "OpticalDistortion",
                "PadIfNeeded",
                "Perspective",
                "PiecewiseAffine",
                "PixelDropout",
                "RandomCrop",
                "RandomCropFromBorders",
                "RandomGridShuffle",
                "RandomResizedCrop",
                "RandomRotate90",
                "RandomScale",
                "RandomSizedBBoxSafeCrop",
                "RandomSizedCrop",
                "Resize",
                "Rotate",
                "SafeRotate",
                "ShiftScaleRotate",
                "SmallestMaxSize",
                "Transpose",
                "VerticalFlip",
                "XYMasking",
            }  # from https://albumentations.ai/docs/getting_started/transforms_and_targets/#spatial-level-transforms

            # Transforms
            T = [
                # Spatial Augmentations
                #A.RandomScale(scale_limit=(-0.5, 1.5), p=0.5),
                A.HorizontalFlip(p=0.5),
                
                # Color and Contrast Augmentations
                A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.3),
                A.HueSaturationValue(hue_shift_limit=15, sat_shift_limit=20, val_shift_limit=15, p=0.3),
                
                # Noise and Blur Augmentations
                A.GaussNoise(var_limit=(10.0, 30.0), p=0.2),
                A.MotionBlur(blur_limit=3, p=0.2),
                
                # Weather Effects (use sparingly)
                A.RandomFog(fog_coef_lower=0.2, fog_coef_upper=0.4, p=0.1),
                A.RandomRain(blur_value=2, rain_type='drizzle', p=0.1),
                
                # Others
                A.CLAHE(clip_limit=2.0, p=0.1),
            ]

            # Compose transforms
            self.contains_spatial = any(transform.__class__.__name__ in spatial_transforms for transform in T)
            self.transform = (
                A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))
                if self.contains_spatial
                else A.Compose(T)
            )
            LOGGER.info(prefix + ", ".join(f"{x}".replace("always_apply=False, ", "") for x in T if x.p))
        except ImportError:  # package not installed, skip
            pass
        except Exception as e:
            LOGGER.info(f"{prefix}{e}")

def main(config):
    Albumentations.__init__ = __init__
    model = YOLO('yolov8s-p2.yaml')  # build from YAML and transfer weights

    # Train the model
    results = model.train(**config)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train YOLOv8 model')
    parser.add_argument('--config', type=str, required=True, help='Path to the training parameters YAML file')

    args = parser.parse_args()

    with open(args.config, 'r') as f:
        config = yaml.safe_load(f)

    main(config)
```

The config file I use is like so:
```YAML
# All Hyperparameters and Augmentations can be found here: https://docs.ultralytics.com/modes/train/#augmentation-settings-and-hyperparameters

data: /opt/yolo-dataset/dataset.yaml
project: test
epochs: 300
imgsz: 1024
device:
  - 0
  - 1
batch: 96
save_period: 5
pretrained: best.pt
optimizer: auto
verbose: True
deterministic: False
single_cls: False
amp: True
profile: True
val: True
plots: True
resume: False
augment: True

# Augmentation Settings

# Adjusts the hue of the image by a fraction of the color wheel. Range: 0.0 - 1.0
hsv_h: 0.015
# Alters the saturation of the image by a fraction. Range: 0.0 - 1.0  
hsv_s: 0.7
# Modifies the value (brightness) of the image by a fraction. Range: 0.0 - 1.0
hsv_v: 0.4
# Rotates the image randomly within the specified degree range. Range: -180 - +180
degrees: 0.0
# Translates the image horizontally and vertically by a fraction of the image size. Range: 0.0 - 1.0
translate: 0.0
# Scales the image by a gain factor. Range: >=0.0
scale: 0.5
# Shears the image by a specified degree. Range: -180 - +180
shear: 0.0
# Applies a random perspective transformation to the image. Range: 0.0 - 0.001
perspective: 0.0
# Flips the image upside down with the specified probability. Range: 0.0 - 1.0
flipud: 0.0
# Flips the image left to right with the specified probability. Range: 0.0 - 1.0
fliplr: 0.0
# Combines four training images into one. Range: 0.0 - 1.0
mosaic: 0.25
# Blends two images and their labels, creating a composite image.
mixup: 0.0
# Copies objects from one image and pastes them onto another, useful for increasing object instances and learning object occlusion.
copy_paste: 0.0
# Automatically applies a predefined augmentation policy. (randaugment, autoaugment, augmix)
auto_augment: randaugment 
# Randomly erases a portion of the image
erasing: 0.0
```
