### DISCUSSION TITLE
P2 v8 Model ?

### DISCUSSION THREAD

**Discussion by ExtReMLapin** [ultralytics/ultralytics#895] [Q&A]
Hello,
Is there any plan to realse a P2 v8 model ?
Thanks.

**Comment by pinheiromelobruno** [comment]
Hi, I’m trying too to add a P2 head for detecting small targets. Any tips? For now I’m trying to make an analogy from the steps for YOLOv5 ([yolov5/yolov5-p2.yaml at master · ultralytics/yolov5 · GitHub](https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p2.yaml)):


# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 1  # number of classes
depth_multiple: 0.33  # scales module repeats
width_multiple: 0.25  # scales convolution channels

# YOLOv8.0n_P2 backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n_P2 head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P2
  - [-1, 1, C2f, [128]]  # 18 (P2/4-xsmall)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 21 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 24 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 27 (P5/32-large)

  - [[18, 21, 24, 27], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)

When I try to train I get this error:


Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/content/ultralytics/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/content/ultralytics/ultralytics/yolo/engine/model.py", line 298, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides)
KeyError: None

**Reply by glenn-jocher** [reply]
@pinheiromelobruno hello! It's great to see your interest in adapting YOLOv8 for detecting small targets with a P2 head. While I can't provide a direct code example, I can offer some guidance.

When adapting a model architecture, it's crucial to ensure that the configuration aligns with the expected input and output dimensions at each stage of the model. The error you're encountering suggests there might be a mismatch or an undefined key related to the task you're trying to perform.

For YOLOv8, you would need to carefully adjust the architecture to include a P2 head, ensuring that the feature maps from the backbone are correctly concatenated with the upsampling layers in the head. This process involves a deep understanding of the model's architecture and how the layers interact.

I recommend reviewing the YOLOv8 documentation on our [Ultralytics Docs](https://docs.ultralytics.com) to better understand the model structure and the expected format for configuration files. Additionally, examining the error message and traceback can provide insights into which part of the model configuration is causing the issue.

Remember to verify that each layer's input and output dimensions are compatible and that all necessary keys are defined in your configuration. Good luck with your model adaptation, and don't hesitate to reach out if you have further questions!

**Comment by ExtReMLapin** [comment]
giving a try with 


```
# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.67  # scales module repeats
width_multiple: 0.75  # scales convolution channels

# YOLOv8.0m backbone
backbone:
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [768, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, SPPF, [768, 5]]  # 9

# YOLOv8.0m head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone p2
  - [-1, 3, C2f, [128]]  # 18 (P3/8-small)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat head P3
  - [-1, 3, C2f, [256]]  # 21 (P3/8-medium)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 21 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [768]]  # 24 (P5/32-large)

  - [[15, 18, 21, 24], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)

```

**Reply by ExtReMLapin** [reply]
eats too much vram, can't test it

**Reply by glenn-jocher** [reply]
@ExtReMLapin hello! It looks like you're experimenting with a custom YOLOv8 model configuration aiming to include a P2 layer. If you're encountering VRAM limitations during your tests, consider a few strategies to mitigate this issue:

1. **Reduce Batch Size**: Smaller batch sizes consume less VRAM, allowing you to train with more complex models or higher resolution images.
2. **Model Simplification**: Adjust the `depth_multiple` and `width_multiple` parameters to reduce the complexity of the model, which can help lower VRAM usage.
3. **Gradient Accumulation**: Use gradient accumulation if you're reducing the batch size to maintain the effective batch size over multiple iterations.
4. **Mixed Precision Training**: Utilize mixed precision training to reduce VRAM consumption and potentially speed up training.

Remember, balancing model complexity with hardware limitations is key to successful training. For more detailed guidance on training YOLOv8 models, please refer to our documentation at https://docs.ultralytics.com. Keep experimenting, and good luck with your model development! 🚀

**Comment by pinheiromelobruno** [comment]
I dit it this way, it worked well, but I need to do further tests:

# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 1  # number of classes
depth_multiple: 0.33  # scales module repeats
width_multiple: 0.25  # scales convolution channels

# YOLOv8.0n_P2 backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n_P2 head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P2
  - [-1, 1, C2f, [128]]  # 18 (P2/4-xsmall)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 21 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 24 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 27 (P5/32-large)

  - [[18, 21, 24, 27], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)

**Reply by ExtReMLapin** [reply]
@pinheiromelobruno any news ?

**Reply by glenn-jocher** [reply]
@ExtReMLapin @pinheiromelobruno I've updated PR https://github.com/ultralytics/ultralytics/pull/1560 with a correct YOLOv8-P2 model using the new unified YAML format:

```yaml
# Ultralytics YOLO 🚀, GPL-3.0 license
# YOLOv8 object detection model with P2-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P2
  - [-1, 3, C2f, [128]]  # 18 (P2/4-xsmall)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat head P3
  - [-1, 3, C2f, [256]]  # 21 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 24 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 27 (P5/32-large)

  - [[18, 21, 24, 27], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)
```

**Reply by pinheiromelobruno** [reply]
@glenn-jocher thanks!

**Reply by herrig** [reply]
Did you have success?

I am trying to train a custom model to identify small plants but I got this error: KeyError: 'depth_multiple'

My code:

from ultralytics import YOLO

model = YOLO('yolov8-p2.yaml').load('yolov8x.pt')
model.train(data="/blue/nsboyd/re.herrigfurlane/Teste/Hole_v8/data.yaml", 
            workers=16,
            batch=64, 
            epochs=1200, 
            imgsz=640, 
            lr0=0.010, 
            lrf=0.005,
            seed=1234,
            momentum=0.900,)

**Reply by ExtReMLapin** [reply]
depth_multiple is implicit when calling the yaml from command line as you actually don't call the real yaml file.
You can add a depth_multiple variable in the yaml file

**Reply by herrig** [reply]
Thanks for your answer. I am sorry, but I am a beginner level in programming. Could you tell me how to do this?

**Reply by glenn-jocher** [reply]
@herrig certainly! To resolve the `KeyError: 'depth_multiple'` issue, you need to define the `depth_multiple` parameter in your YAML configuration file. This parameter is used to scale the depth of the model's layers, allowing you to customize the model's size and complexity.

Here's a simple example of how you can add the `depth_multiple` parameter to your YAML file:

```yaml
# parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth scale (adjustable)
width_multiple: 0.50  # layer channel scale (adjustable)

# Backbone
backbone:
  # [from, number, module, args]
  [...]

# Head
head:
  [...]
```

In this example, `depth_multiple` is set to `0.33`, which means each layer will repeat 33% as many times as the maximum. You can adjust this value according to your needs. The `width_multiple` parameter works similarly but for the width (number of channels) of the layers.

After adding the `depth_multiple` (and optionally `width_multiple`) to your YAML file, you should be able to train your model without encountering the `KeyError`. Remember to save the changes to your YAML file before starting the training process. Good luck with your model training! 🌱🚀
