### DISCUSSION TITLE
pt/quickstart/

### DISCUSSION THREAD

**Discussion by giscus** [ultralytics/ultralytics#9704] [Docs]
# pt/quickstart/

Explora vários métodos para instalar Ultralytics usando pip, conda, git e Docker. Aprende a utilizar Ultralytics com a interface de linha de comandos ou nos teus projectos Python .

https://docs.ultralytics.com/pt/quickstart/

**Comment by jonatapaulino** [comment]
Oops! I always follow your videos on YouTube. Thanks for teaching agent. I have a question: Is there any way to refine the hyperparameters in yolov8? I have a project that has an accuracy of 67, but I need to improve this performance a lot. Can you help me? Thanks.

**Reply by glenn-jocher** [reply]
Hey, thanks for the kind words and for following our videos! 🙌 To refine the hyperparameters for YOLOv8 and improve your model's accuracy, you can experiment with various settings in your training configuration file (usually a `.yaml` file). Here's a quick example of how you might adjust some common hyperparameters:

```yaml
# Example of hyperparameters in a YAML configuration file
lr0: 0.01  # initial learning rate
lrf: 0.1   # final learning rate factor
momentum: 0.937  # optimizer momentum
weight_decay: 0.0005  # weight decay
warmup_epochs: 3  # number of warmup epochs
warmup_momentum: 0.8  # initial momentum during warmup
warmup_bias_lr: 0.1  # initial learning rate for biases during warmup
```

You can modify these values to see if they help improve performance. Additionally, consider using techniques like data augmentation, increasing the dataset size, or even using a more complex model variant if your hardware allows. For a detailed guide on tuning these parameters, check out the [Ultralytics documentation](https://docs.ultralytics.com/). Good luck with your project! 🚀
