### ISSUE TITLE
Is there a good solution to predict two labels for the same object?

### ISSUE THREAD

**Issue by blue-q** [ultralytics/ultralytics#10128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![2024_04_15_16_58_48_person_0](https://github.com/ultralytics/ultralytics/assets/85726493/099a5910-4d5b-4a2f-b742-368d5ded27f0)

**Comment by glenn-jocher** [comment]
Certainly! Predicting two labels for the same object can be achieved by using the multi-label classification capability. You can train your YOLOv8 model on a dataset where objects are annotated with multiple class labels. Ensure your dataset's annotation format supports multi-labels per object (e.g., JSON, XML formats).

After preparing your dataset, modify the model's configuration to predict multiple labels by adjusting the final layer to output multiple probabilities per class.

Here's a simplified example of adjusting the dataset configuration (`data.yaml`):

```yaml
# Example of data.yaml configuration for multi-label prediction
train: path/to/train/images
val: path/to/val/images

nc: 2  # Number of classes
names: ['class_1', 'class_2']
multi_label: true  # Enable multi-label classification
```

Ensure your training process is aware of the multi-label setup. You might need to adjust loss computation to handle multi-label outputs effectively.

Remember, multi-label classification can increase the complexity of your model, so it's crucial to provide enough training data for each label combination to ensure accurate predictions. 🚀
