### ISSUE TITLE
Using YOLOv8 and YOLOv9 for Document Layout Segmentation

### ISSUE THREAD

**Issue by only-yao** [ultralytics/ultralytics#10229]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am experiencing persistent issues with truncation in document layout segmentation while using YOLOv8 and YOLOv9, as previously discussed in [#4369](https://github.com/ultralytics/ultralytics/issues/4369). Despite trying the following adjustments, the issue persists with an approximate occurrence rate of 3%:

1. I modified the `mask_ratio` parameter with values [2, 4, 8].
2. I implemented image rotations during the training data preparation phase.
3. I switched to YOLOv9 from YOLOv8.

However, none of these measures have resolved the truncation issues illustrated in the image below. Currently, I am compelled to manually correct the model predictions using the original PDF character coordinates.

![image](https://github.com/ultralytics/ultralytics/assets/36235579/20d75f6d-0c60-4162-a9bd-afd79a63706b)

I would greatly appreciate any insights or recommendations on how to avoid or minimize these issues.

Thank you!

**Comment by glenn-jocher** [comment]
Hello! 👋

Truncation in document layout segmentation can indeed be challenging. Given the steps you've already tried, here are a couple of suggestions that might help further:

- **Try Adjusting the Anchor Sizes**: Sometimes tweaking the anchor box sizes can help the model better fit the peculiarities of document layouts. Use the `--autoanchor` flag during training to automatically adjust anchors based on your dataset.

- **Increase Model Input Size**: If not already maximized within your computational constraints, increasing the `imgsz` parameter can help the model detect smaller or more nuanced features by providing it with more detailed inputs.

For adjusting anchor sizes, your training command could be adjusted to include the autoanchor like this (assuming you're using CLI):

```bash
yolo detect train data=your_dataset.yaml model=yolov8n.yaml imgsz=640 autoanchor=True
```

And for experimenting with a larger `imgsz`, simply adjust the value accordingly:
```bash
yolo detect train data=your_dataset.yaml model=yolov8n.yaml imgsz=1280  # Example with larger input size
```

If these steps don't mitigate the truncation issue, it might be valuable to look into custom layer adjustments or even a targeted post-processing script that refines the segmentation based on specific patterns or characteristics of your dataset.

Best of luck, and I hope this helps!

**Comment by only-yao** [comment]
Thank you for your suggestions regarding the truncation issue in document layout segmentation. I attempted to implement the autoanchor parameter as you recommended. However, I encountered an error when executing the following command:

```bash
yolo detect train data=class1.yaml model=/data/d/models/yolo/yolov9e.pt mask_ratio=4 epochs=15 batch=8 imgsz=1280 autoanchor=True save_period=1 workers=8
```

The error message was:

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/yolov9/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/yolov9/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 515, in entrypoint
    check_dict_alignment(full_args_dict, overrides)
  File "/root/miniconda3/envs/yolov9/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 322, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'autoanchor' is not a valid YOLO argument.
```

Upon further investigation, I used the `yolo cfg` command and reviewed the documentation at [Ultralytics Train Settings](https://docs.ultralytics.com/modes/train/#train-settings) but found no mention of the autoanchor parameter for YOLOv8 or YOLOv9 training. I noticed the autoanchor option appears only in the training settings for YOLOv5, as described [here](https://docs.ultralytics.com/yolov5/tutorials/architecture_description/?h=autoanchor#3-training-strategies).

Could you provide additional information or clarification regarding the autoanchor parameter? Is it applicable to YOLOv9 models? My installed version of Ultralytics is 8.2.2.

Thank you for your assistance.

**Comment by glenn-jocher** [comment]
Hey there! 😊

My sincere apologies for the confusion regarding the `autoanchor` parameter. You’re absolutely right; the `autoanchor` flag is specific to the YOLOv5 training process and is not directly applicable to YOLOv8 or YOLOv9, hence the error you encountered. I appreciate your diligence in checking the documentation and employing the `yolo cfg` command for clarity.

For YOLOv8 and YOLOv9 models, anchor optimization needs to be performed separately before initiating the training process. This can be done by analyzing your dataset to adjust the anchor boxes manually, which, though not as straightforward as using `autoanchor`, can lead to improved detection performance for document layout segmentation.

Thank you for your patience, and hope this clears things up! If you have more questions or need further assistance, feel free to ask. Happy to help!

**Comment by only-yao** [comment]
Thank you for clarifying the use of the autoanchor parameter with YOLOv5 and explaining its inapplicability to YOLOv8 and YOLOv9. As a novice using the YOLOv8 framework, I have begun researching anchor boxes. Could you guide me on how to manually set up these anchor boxes? My understanding is that I should first perform clustering on the labeled data to choose the appropriate boxes. Once that is done, should I proceed directly with training, or is there an additional step I should be aware of?

Additionally, I have set the `imgsz` parameter to 1280 and noticed that, compared to a size of 640, the model size does not change, but the VRAM usage increases to about four times as much. Could you help me understand why this occurs?

Looking forward to your guidance.

**Comment by glenn-jocher** [comment]
Hey there! 🌟

Absolutely, I'd be happy to help guide you on setting up the anchor boxes for YOLOv8. Your grasp of initializing this process through clustering labeled data is spot on! This helps in identifying the most representative anchor sizes for your specific dataset. After clustering, you will integrate these anchor sizes into your model's configuration file, directly replacing the default anchor values.

To update the anchor boxes in your model's config:
1. Open your YOLO model config file.
2. Locate the `anchors` attribute.
3. Replace the default anchors with your clustered ones.

Example:
```yaml
anchors:
  - [10,13, 16,30, 33,23]  # Small anchors
  - [30,61, 62,45, 59,119]  # Medium anchors
  - [116,90, 156,198, 373,326]  # Large anchors
```

After updating the anchors, proceed with training. There's no additional essential step unless you want to further fine-tune or experiment with other hyperparameters! 😊

Regarding the `imgsz` parameter and VRAM usage, increasing `imgsz` from 640 to 1280 scales up the input image's dimensions, which directly impacts memory usage. Since the network processes a significantly larger matrix, it requires more computational resources, especially VRAM. This is why you're observing a quadrupled VRAM consumption. It allows the model to potentially capture more details at the expense of higher VRAM requirements.

Hope this helps clarify things! If you have further questions, feel free to ask. Happy modeling! 🚀

**Comment by only-yao** [comment]
Thank you for the examples you provided. I have selected the parameters for 9 anchors through clustering, as follows:

Anchors:
  - [59,14, 16,130]  # Small anchors
  - [381,23, 230,40, 46,260]  # Medium anchors
  - [500,35, 42,479, 475,187, 416,475]  # Large anchors

Here is my training script:
```
yolo detect train data=class1.yaml model=/data/d/models/yolo/yolov9e.pt mask_ratio=4 epochs=15 batch=12 imgsz=640 save_period=1 workers=8
```

Attached is a comparison of the performance before and after setting the anchors, with the blue color indicating the use of anchors.

![image](https://github.com/ultralytics/ultralytics/assets/36235579/bdc263dd-12a6-4e04-8330-05e56825af60)

Additionally, under the same batch size with `imgsz` set to 1280, there isn't a significant improvement in mAP50-95. How can I enhance the mAP50-95 score? Currently, I have around 120,000 data points with image sizes of 1025x1025. The strategies I am considering include:
1. Increasing the training batch size and number of training steps.
2. Expanding the model parameters and training data.
3. Applying noise to the original images (such as dilation).

**Comment by only-yao** [comment]
Additionally, how should I choose the number of anchors?

**Comment by glenn-jocher** [comment]
Hey there! Choosing the number of anchors mainly depends on the diversity of object sizes in your dataset. 📊 Generally, more anchors can better cover varied object sizes, but too many might lead to complexity and overfitting. A practical approach is to start with around 3 anchors per scale (small, medium, large) based on common practices in YOLO configurations.

You can analyze your dataset's bounding box sizes with k-means clustering to find an optimal anchor count and size. The process involves:
1. Extracting all bounding boxes from your dataset.
2. Applying k-means clustering to find clusters best representing your boxes.
3. Adjusting `k` in k-means to find a balance between model complexity and the range of object sizes.

For customization, you might test with increasing or decreasing the number of anchors per scale based on your analysis and observe the impact on model performance. Keep experimenting! 🚀

**Comment by enymfc25173** [comment]
how about this problem. has it been solved? I encountered the same issue

**Comment by glenn-jocher** [comment]
Hello! 👋

If you're encountering the same issue, could you please provide more details about your setup and the specific problem you're facing? This will help us better understand the context and assist you more effectively. Looking forward to your response!

**Comment by dq2b25** [comment]
> Hey there! 🌟
> 
> Absolutely, I'd be happy to help guide you on setting up the anchor boxes for YOLOv8. Your grasp of initializing this process through clustering labeled data is spot on! This helps in identifying the most representative anchor sizes for your specific dataset. After clustering, you will integrate these anchor sizes into your model's configuration file, directly replacing the default anchor values.
> 
> To update the anchor boxes in your model's config:
> 
> 1. Open your YOLO model config file.
> 2. Locate the `anchors` attribute.
> 3. Replace the default anchors with your clustered ones.
> 
> Example:
> 
> ```yaml
> anchors:
>   - [10,13, 16,30, 33,23]  # Small anchors
>   - [30,61, 62,45, 59,119]  # Medium anchors
>   - [116,90, 156,198, 373,326]  # Large anchors
> ```
> 
> After updating the anchors, proceed with training. There's no additional essential step unless you want to further fine-tune or experiment with other hyperparameters! 😊
> 
> Regarding the `imgsz` parameter and VRAM usage, increasing `imgsz` from 640 to 1280 scales up the input image's dimensions, which directly impacts memory usage. Since the network processes a significantly larger matrix, it requires more computational resources, especially VRAM. This is why you're observing a quadrupled VRAM consumption. It allows the model to potentially capture more details at the expense of higher VRAM requirements.
> 
> Hope this helps clarify things! If you have further questions, feel free to ask. Happy modeling! 🚀

You mention "Locate the anchors attribute", but I search "anchors" in the whole project and did not find the anchors config for yolov8.

**Comment by glenn-jocher** [comment]
Hello!

Thank you for reaching out with your query. It seems there was a misunderstanding in my previous message regarding the configuration of anchors for YOLOv8. Unlike some previous versions, YOLOv8 does not use a manual anchor configuration in the same way. Instead, YOLOv8 automatically optimizes anchor shapes during the training process based on your specific dataset, which simplifies the setup and improves model adaptability.

If you're looking to customize aspects of the model architecture or training process, I recommend focusing on other hyperparameters that can be adjusted in your training configuration file, such as learning rates, batch sizes, or augmentation strategies.

Apologies for any confusion, and thank you for your understanding. If you have more questions or need further assistance, please let me know!

**Comment by glenn-jocher** [comment]
Hello! 👋

Thank you for bringing this to our attention. It's crucial to ensure the quality of annotations for optimal model performance. Here are a few steps you can take to address this issue:

1. **Verify Annotation Quality**: It's essential to review and correct any annotation errors in your dataset. Tools like [LabelImg](https://github.com/tzutalin/labelImg) or [Roboflow](https://roboflow.com/) can help you visualize and edit annotations.

2. **Data Augmentation**: Implementing data augmentation techniques can help improve model robustness despite imperfect annotations. YOLOv8 supports various augmentation strategies that you can configure in your training script.

3. **Training with Custom Data**: If you have a subset of well-annotated data, consider training your model on this subset to see if it improves performance. You can also use transfer learning to fine-tune a pre-trained model on your custom dataset.

4. **Hyperparameter Tuning**: Experiment with different hyperparameters such as learning rate, batch size, and epochs to find the optimal settings for your dataset.

If you continue to face issues, please provide a minimum reproducible code example so we can better understand and investigate the problem. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). Also, ensure you are using the latest versions of `torch` and `ultralytics` packages.

Here's a sample training script for reference:
```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # Load a pre-trained model

# Train the model
results = model.train(data='path/to/your/data.yaml', epochs=100, imgsz=640, batch=16)
```

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

**Comment by johnlockejrr** [comment]
I have the sane problem with YOLOv8 segmentation training, my detected lines of text in the image got truncated:

![BCUF_Ms _L_2057_330-bw](https://github.com/user-attachments/assets/982310f7-2a86-4e56-89f6-bd3d8d0bc920)

**Comment by Y-T-G** [comment]
@johnlockejrr Try this but last layer should be Segment.

https://github.com/ultralytics/ultralytics/issues/16895#issuecomment-2413016050

**Comment by johnlockejrr** [comment]
Thank you @Y-T-G!

Should I keep the values in your example or should I change them somehow for my dataset?

**Comment by johnlockejrr** [comment]
UPDATE:

I trained the model with @Y-T-G config, seems it has improved, only one line truncated a letter.

![newtestamentinsy0000unse_g7r6_0227](https://github.com/user-attachments/assets/5294c705-5d81-411c-b795-2680cfa6503e)

**Comment by Y-T-G** [comment]
@johnlockejrr You can try this branch too with that yaml.

https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-2367471426

**Comment by johnlockejrr** [comment]
> @johnlockejrr You can try this branch too with that yaml.
> 
> [#11634 (comment)](https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-2367471426)

I'm installing your branch.
To be sure, this is my yaml conf:
```
train: /home/incognito/yolov8/datasets/syr_xml_yolov8/train
val: /home/incognito/yolov8/datasets/syr_xml_yolov8/val
nc: 1
names:
- text_line
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

imgsz: 960

# YOLOv8.0 backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [768, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 9-P6/64
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 11

# YOLOv8.0-p2-p6 head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 8], 1, Concat, [1]] # cat backbone P5
  - [-1, 3, C2, [768, False]] # 14
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 17
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 20 (P3/8-small)
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 2], 1, Concat, [1]] # cat backbone P2
  - [-1, 3, C2f, [128]] # 23 (P2/4-xsmall)
  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 20], 1, Concat, [1]] # cat head P3
  - [-1, 3, C2f, [256]] # 26 (P3/8-small)
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 17], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 28 (P4/16-medium)
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2, [768, False]] # 31 (P5/32-large)
  - [-1, 1, Conv, [768, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P6
  - [-1, 3, C2, [1024, False]] # 34 (P6/64-xlarge)
  - [[23, 26, 28, 31, 34], 1, Segment, [nc]] # Segment(P2, P3, P4, P5, P6)
```

Is that ok?
