### ISSUE TITLE
add a new key to the yaml file

### ISSUE THREAD

**Issue by WHK1229** [ultralytics/ultralytics#10395]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to add a new key to the yaml file in yolov8 to write a new network trunk into it

**Comment by glenn-jocher** [comment]
@WHK1229 hello! 👋 To add a new key to the YAML file for a custom network trunk in YOLOv8, you can simply open your YAML file in a text editor and add the new key along with its value. Here's a quick example if you're defining a new trunk `custom_trunk`:

```yaml
# Your existing YAML content

# Adding new custom trunk configuration
custom_trunk:
  depth_multiple: 0.33  # model depth multiple
  width_multiple: 0.50  # layer channel multiple
  # Your custom trunk layers go here
```

Just ensure that your new trunk configuration is correctly structured to be recognized by YOLOv8. After adding, you can then reference this `custom_trunk` in your model's YAML where required. 🚀
