### ISSUE TITLE
How to train two datasets simultaneously?

### ISSUE THREAD

**Issue by fu0fu0** [ultralytics/ultralytics#10405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have two sets of image datasets with identical labels. How can I simultaneously train both datasets to incorporate an additional feature information?

**Comment by glenn-jocher** [comment]
@fu0fu0 hello! 👋 To train YOLOv8 on two datasets simultaneously, you can merge both datasets into a single dataset structure. Assuming your datasets share identical labels, you can simply concatenate the paths of the image and label files in your dataset configuration YAML file. Here's how you might set it up:

```yaml
# Example dataset YAML configuration

train: 
  - path/to/dataset1/images/
  - path/to/dataset2/images/
val: 
  - path/to/dataset1/valid_images/
  - path/to/dataset2/valid_images/
  
nc: <number_of_classes>
names: ['class1', 'class2', ...]
```

Ensure that the directory structure for both datasets follows the expected format, with images and their corresponding labels in sync. Essentially, by listing both paths under the `train` and `val` keys, YOLOv8 will treat all listed images as part of a single, unified dataset during training.

Happy training! 😊
