### ISSUE TITLE
Can we use the model yaml file and pretrained model at the same time

### ISSUE THREAD

**Issue by 523997931** [ultralytics/ultralytics#1127]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I want to change some module in the model cfg yaml file, but I also want the module I don't change can load the pretraind weight, in yolov5 I remember I can do this at the same time, but in v8 I don't know if it can do?

**Comment by glenn-jocher** [comment]
@523997931 hi there! In YOLOv8 you can pass either a model yaml or a model pt file to create your model, but not both, i.e.:

```bash
yolo train model=yolov8n.pt
yolo train model=yolov8n.yaml
```

**Comment by farhanhumayun** [comment]
@glenn-jocher hi. Can you please elaborate the difference between using yolov8n.pt and yolov8n.yaml. As per my understanding the .pt file is used for the pertained weights and .yaml is used to start training from scratch. Also please elborated what does pretrained=False / True mean?
Thanks.

**Comment by glenn-jocher** [comment]
@farhanhumayun we have updated Usage examples in Docs that explain this:
https://docs.ultralytics.com/modes/train/

<img width="725" alt="Screenshot 2023-03-19 at 13 47 24" src="https://user-images.githubusercontent.com/26833433/226176149-77954eb0-30ab-4401-aae8-7ff4f0ee87d4.png">

**Comment by farhanhumayun** [comment]
@glenn-jocher thanks for the prompt reply!

**Comment by glenn-jocher** [comment]
@sipie800 hi,

Thanks for reaching out. Based on the traceback, it seems that you are using the `load()` method on the `YOLO` object, which is not a part of the object's methods. Instead, you can load the pre-trained weights by passing the file path of the weights file to the `YOLO` object's constructor.

Here’s an example loading the pre-trained weights from the `yolov8s.pt` weight file:

```python
from yolov8.models import YOLO

model = YOLO("cfg/yolov8s.yaml", pretrained_weights="yolov8s.pt")
```

This should load the pre-trained weights from the file specified and instantiate your model. If you want to train on a different dataset, you can set `pretrained_weights = None` to train the model from scratch. 

I hope this helps. Let me know if you have any other questions or concerns.

Best regards!

**Comment by chinhong11** [comment]
@glenn-jocher Hi, may I know if it is possible for me to take the original yolov8s.pt weights and train them on a modified yolov8s.yaml file, for example, with an added attention module like CBAM on the structure? Can the weights be transferred instead of starting training from scratch? I tried this command but it seems still start training from scratch:( This is the command I tried:

```
model = YOLO("ultralytics/models/v8/yolov8s-cbam.yaml").load('yolov8s.pt')
model.train(**{'cfg':'ultralytics/yolo/cfg/train.yaml'})
```

And this is the yaml file I modified:

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, CBAM, [7]] # 1
  - [-1, 1, Conv, [128, 3, 2]]  # 2-P2/4
  - [-1, 1, CBAM, [7]] # 3
  - [-1, 3, C2f, [128, True]]   # 4
  - [-1, 1, Conv, [256, 3, 2]]  # 5-P3/8
  - [-1, 1, CBAM, [7]] # 6
  - [-1, 6, C2f, [256, True]]   # 7
  - [-1, 1, Conv, [512, 3, 2]]  # 8-P4/16
  - [-1, 1, CBAM, [7]] # 9
  - [-1, 6, C2f, [512, True]]   # 10
  - [-1, 1, Conv, [1024, 3, 2]]  # 11-P5/32
  - [-1, 1, CBAM, [7]] # 12
  - [-1, 3, C2f, [1024, True]]  # 13
  - [-1, 1, SPPF, [1024, 5]]  # 14

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 15
  - [[-1, 9], 1, Concat, [1]]  # cat backbone P4 # 16
  - [-1, 3, C2f, [512]]  # 17

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] # 18
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P3 # 19
  - [-1, 3, C2f, [256]]  # 20 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]] # 21
  - [[-1, 17], 1, Concat, [1]]  # cat head P4 # 22
  - [-1, 3, C2f, [512]]  # 23 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]] # 24
  - [[-1, 14], 1, Concat, [1]]  # cat head P5 # 25
  - [-1, 3, C2f, [1024]]  # 26 (P5/32-large)

  - [[20, 23, 26], 1, Detect, [nc]]  # Detect(P3, P4, P5) # 27
```
