### ISSUE TITLE
TaskAlignedAssigner doesn't take into account `reg_max` which affects prediction of large objects

### ISSUE THREAD

**Issue by Y-T-G** [ultralytics/ultralytics#11634]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

The `TaskAlignedAssigner` is responsible for choosing best anchor point that best fits the target bounding box. But the assignment does not take into account the `reg_max` property of the head. That means [`select_candidates_in_gts`](https://github.com/ultralytics/ultralytics/blob/03da2944d7403a2ac16e87c78b39cc842d97c5d8/ultralytics/utils/tal.py#L213) will choose anchor points that fits the center point of the target bounding box but due to the `reg_max` limit of 16 which it is not taking into account, it may be using the anchor points that is coming from an FPN layer that can't entirely cover the whole box due to `reg_max`. For example, choosing an anchor point from the 20x20 feature maps would be suitable for an object that covers the whole image. But if TAL assigns an anchor point from the 40x40 or 80x80 feature maps, the predicted box will not be able to cover the whole box as `reg_max` limits the regression to encompass just 30x30 portion of the feature maps.

This problem is evident across multiple users reporting that the predictions are cropped for large objects.

https://github.com/ultralytics/ultralytics/issues/6777
https://github.com/ultralytics/ultralytics/issues/6062
https://github.com/ultralytics/ultralytics/issues/4961
https://github.com/ultralytics/ultralytics/issues/4988#issuecomment-1729252938
https://github.com/ultralytics/ultralytics/issues/4973
https://github.com/ultralytics/ultralytics/issues/2949

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Y-T-G thank you for pointing out the issue with how `TaskAlignedAssigner` handles `reg_max` when predicting large objects. This definitely seems to be a critical aspect not currently accounted for, affecting the predictions for larger objects as you described.

We appreciate your willingness to submit a PR! It would be fantastic to see your approach to adjusting the `TaskAlignedAssigner` to consider `reg_max`. If you need any guidance or assistance while preparing the PR or if you would like to discuss potential solutions, don't hesitate to reach out. 🚀

Looking forward to your contribution!

**Comment by Laughing-q** [comment]
@Y-T-G @Burhan-Q Hey guys! Nice catch! yes it's true the regressed bounding boxes are limited by the `reg_max` value.
Sorry for the delay though, I had to test it locally and tried some solutions might help with the cases of regressing large objects. :)
Here's my suggestions:
1. scale up the `reg_max`, for example scale it up to 32 or 64, and it'll help!
2. directly set `reg_max=1` which means abandoning the DFL module, then the regressed values of bounding boxes are unlimited, hence more friendly to the large objects.

**Comment by djdll** [comment]
here, I found a similar problem to mine, but my target was not large objects, but objects with non-obvious boundaries. After training, I found that some images had bounding boxes that did not completely cover the object. So I wonder if reducing reg_max in dfl can improve this problem, but I would like to ask if there is anything to pay attention to if the 16 of reg_max is changed to 8, or if you think the change is effective
Thanks!

**Comment by djdll** [comment]
here, I found a similar problem to mine, but my target is not large objects, but objects with non-obvious boundaries. After training, I found that some images have bounding boxes that do not fully cover the object, because my training input size is 288, So I wonder if reducing reg_max in dfl can improve this problem, but I would like to ask if there is anything to pay attention to if the 16 of reg_max is changed to 8, or if you think the change is effective.
Thanks!

**Comment by glenn-jocher** [comment]
Thank you for your question. Reducing `reg_max` from 16 to 8 can indeed help with objects that have non-obvious boundaries, as it allows for finer adjustments. However, this change may also impact the model's ability to generalize to larger objects. It's advisable to experiment with different `reg_max` values to find the optimal setting for your specific dataset and use case.

**Comment by GxTeo** [comment]
Increasing ```reg_max``` from 16 to 32/64 for ```img_sz=2048```  has increased the precision and recall for large objects quite evidently, I have looked briefly into the bounding boxes predictions and noticed that the cropping of bounding boxes on large objects are less obvious as well. 

However, I might note that there are also small objects in my images and it seems that there is a trade-off in performance in the detection of small objects when ```reg_max``` is increased. Currently I have not explored ```reg_max=1``` suggested by @Laughing-q , but would get onto it asap.

**Comment by glenn-jocher** [comment]
Thank you for sharing your observations. It's great to hear that increasing `reg_max` has improved precision and recall for large objects. We appreciate your suggestion to make `reg_max` configurable during training and will consider it for future updates. If you encounter further issues, please ensure you're using the latest package version.

**Comment by Y-T-G** [comment]
I created a branch with a test fix that ensures the anchors are assigned based on the maximum regressable box size for that anchor. You can try it by installing it locally:

```bash
git clone https://github.com/Y-T-G/ultralytics
git checkout TAL
pip install .
```

You can train normally after that.

There's also a dynamic `reg_max` calculation based on `imgsz` in the yaml file. So you will have to create a custom model `yaml` where you add `imgsz: 1280` as a new key. You can duplicate the [existing `yaml`](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/v8) and add the key. This will adjust the `reg_max` to be more suitable for the `imgsz` specified.

**Comment by GC19981106** [comment]
https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-2367471426 @Y-T-G How can I use this method in YOLO11? Can you provide me with the segp6-yaml file for using this program in YOLO11?

**Comment by Y-T-G** [comment]
@GC19981106 You can try this.

https://github.com/WangQvQ/ultralytics/blob/1b28ba79ff322b8510e128ccc9cdb6703d31f62a/ultralytics/cfg/models/11/yolo11-p6.yaml

Change last layer

`[[21, 24, 27, 30], 1, Detect, [nc]]`

to 

`[[21, 24, 27, 30], 1, Segment, [nc, 32, 256]]`

But it wouldn't work with my branch. You can try it with the latest Ultralytics version.

**Comment by GC19981106** [comment]
@Y-T-G Hi author, I used your YOLOv8 branch for training, but the result is not very good. Previously training map in yolo11 could go up to 95%, is there a problem on any side? Here is my yaml file:
```
# Parameters
nc: 2 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-seg-p6.yaml' will call yolov8-seg-p6.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]
  
imgsz: 1024

# YOLOv8.0x6 backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [768, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 9-P6/64
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 11

# YOLOv8.0x6 head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 8], 1, Concat, [1]] # cat backbone P5
  - [-1, 3, C2, [768, False]] # 14

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2, [512, False]] # 17

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2, [256, False]] # 20 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 17], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2, [512, False]] # 23 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2, [768, False]] # 26 (P5/32-large)

  - [-1, 1, Conv, [768, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P6
  - [-1, 3, C2, [1024, False]] # 29 (P6/64-xlarge)

  - [[20, 23, 26, 29], 1, Segment, [nc, 32, 256]] # Pose(P3, P4, P5, P6)

```
![2222222222222](https://github.com/user-attachments/assets/810149a1-d4e4-4e7e-8b98-8bec039017d3)
![111111111111111](https://github.com/user-attachments/assets/2f037fab-3ad8-4c98-8e92-fb7027f892c0)
![val_batch2_pred](https://github.com/user-attachments/assets/78d4b04c-e6fe-4d33-8568-f3e8e81484f9)
