### ISSUE TITLE
Can we specify (augmentation) hyperparams via text file?

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#11776]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In YOLOv5 it was possible to define the (augmentation) hyperparams via a text file. Now we specify each hyperparam when calling the `train()` function. Is there a way to either provide a configuration text file, or even better combine both, passing params to `train()` as well as providing additional hyperparams via a text file?

**Comment by glenn-jocher** [comment]
Yes, you can specify augmentation hyperparameters through a YAML configuration file in YOLOv8, similar to YOLOv5. You can define various parameters in your YAML file and pass the file when calling the `train()` function.

Here’s a quick example on how to do this:

1. Define your hyperparameters in a YAML file, say `hyp.yaml`:

   ```yaml
   lr0: 0.01  # initial learning rate
   lrf: 0.2   # final learning rate
   momentum: 0.937  # SGD momentum
   weight_decay: 0.0005
   warmup_epochs: 3
   warmup_momentum: 0.8
   warmup_bias_lr: 0.1
   box: 0.05
   cls: 0.5
   cls_pw: 1.0
   obj: 1.0
   obj_pw: 1.0
   iou_t: 0.20
   anchor_t: 4.0
   # additional augmentation parameters can be added here
   ```

2. Pass this file along with additional parameters directly in your `train()` call:

   ```python
   from ultralytics import YOLO

   model = YOLO('yolov8n.yaml')  # Load a model configuration
   model.train(data='coco128.yaml', hyp='hyp.yaml', epochs=100, imgsz=640)
   ```

This way you can easily manage your training hyperparameters externally and even override specific parameters directly in your code! 😊
