### ISSUE TITLE
dataset yaml not found error

### ISSUE THREAD

**Issue by luhgit** [ultralytics/ultralytics#1201]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

After I created the dataset and splits i.e. train, test and val and stored them in datatset/ directory. I tried to train the model using python API but fell into this Dataset config yaml file not found error. The path it complains about is an old path that does not exist as I renamed the project directory. So in the screenshot  test_notebook/ directory does not exist but it assumes the config to be existing on this old path.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/8448270/221889470-d9876764-4bdc-43cd-8289-f1ee09d00120.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/8448270/221891432-dbbe8ba9-47d4-413b-999f-39c935070415.png">

Then I tried with CLI and I got the same problem. As I was running all this in Jupyter Lab so I thought perhaps it could be due to jupyter notebook might cached somewhere the old path so I tried on terminal instead but the problem persisted. I was wondering if this could be something to do with yolov8? Has anyone faced such issues?

### Environment

- YOLO:  Ultralytics YOLOv8== 8.0.43
- OS: MacOS Ventura
- Python: 3.9.13

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about YOLOv8 🚀 **dataset formatting**. To train correctly your data must be in YOLO format. Please see our [Train Custom Data](https://github.com/ultralytics/yolov5/issues/36) tutorial for full documentation on dataset setup and all steps required to start training your first model. This applies to both YOLOv5 and YOLOv8. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLO assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLO locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!
