### ISSUE TITLE
Unable to train with multiple data folders

### ISSUE THREAD

**Issue by limwenyao** [ultralytics/ultralytics#1235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am using ultralytics 8.0.49
My data directory is as follows. I want to use folder1,2 as train, folder3,4 as valid:
```
path/to/data
  | - images
    | - folder1 (each folder contains .jpg)
    | - folder2
    | - folder3
    | - folder4
  | - labels
    | - folder1 (each folder contains .txt)
    | - folder2
    | - folder3
    | - folder4
```
I believe this format follows the [GlobalWheat2020](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/datasets/GlobalWheat2020.yaml) dataset format, hence my dataset.yaml config file is as follows:
```yaml
path: path/to/data
train:
  - images/folder1
  - images/folder2
val:
 - images/folder3
 - images/folder4
names:
  0: class1
```

My training script:
```python
from ultralytics import YOLO
model=YOLO('yolov8x.pt')
model.train(data='dataset.yaml', project='project', imgsz=(416,416))
```

When i execute the training, only the first train folder (folder 1) and first val folder (folder3) gets loaded, the rest are forgotten. I have tried disabling and re-ordering folder1 and folder3, it only seems to take in the first folder in the list. (There is no data issues with my other folders).

```
Model summary: 365 layers, 68156460 parameters, 68156444 gradients, 258.1 GFLOPs

Transferred 589/595 items from pretrained weights
To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.clear.ml
WARNING ⚠️ updating to 'imgsz=416'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'
optimizer: Adam(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias
train: Scanning /path/to/data/labels/folder1... 835 images, 29 backgrounds, 0 
train: New cache created: /path/to/data/labels/folder1.cache
train: Caching images (0.3GB True): 100%|██████████| 835/835 [00:00<00:00, 2892.89it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /path/to/data/labels/folder3.cache... 508 images, 35 backgrounds
val: Caching images (0.2GB True): 100%|██████████| 508/508 [00:00<00:00, 2849.27it/s]
Plotting labels to project/train1/labels.jpg... 
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to project/train1
Starting training for 100 epochs...
```

I have also tried generating a train.txt file and valid.txt file, it would only take in the data from the first folder from the first filepath in the train/valid.txt.

### Environment

YOLOv8.0.49 Python-3.8.13 torch-1.13.1+cu117 CUDA:0 (Tesla V100-32GB, 32508MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by limwenyao** [comment]
I have combined the folders into 1 train and 1 val folder, there is no issue running in this manner. However, as i have other models which are currently running in the original format, i do not wish to change the folder structure nor make duplicates of data.

**Comment by Laughing-q** [comment]
@limwenyao training with multiple data folders works properly to me.
with one folder and 126 images:
```yaml
path: ./datasets/coco128  # dataset root dir
train:
  - images/train  # train images (relative to 'path') 128 images
  # - images/train2  # train images (relative to 'path') 128 images
val: 
  - images/train  # val images (relative to 'path') 128 images
  # - images/train2  # val images (relative to 'path') 128 images
```
![image](https://user-images.githubusercontent.com/61612323/222618434-cbe6e6a6-d4af-4756-911e-a18613cbfb9f.png)
with two folders and 149 images:
```yaml
path: ./datasets/coco128  # dataset root dir
train:
  - images/train  # train images (relative to 'path') 128 images
  - images/train2  # train images (relative to 'path') 128 images
val: 
  - images/train  # val images (relative to 'path') 128 images
  - images/train2  # val images (relative to 'path') 128 images
```
![image](https://user-images.githubusercontent.com/61612323/222618372-501928a8-1da9-4856-a33c-9c7108265139.png)
