### ISSUE TITLE
Detection and segmentation from same img source

### ISSUE THREAD

**Issue by CastingSpell** [ultralytics/ultralytics#12986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Good afternoon,

Im trying to setup a training pipeline with multiple detectors, in order to avoid images redundance, I use the same folder for everything. However in this step, using yolo, I have a detector and a segmentator model, both require different kind of labels and different training processes, but I can't find the way of changing the labels path in order to call one or another wether its detection or segmentation.  I've seen this in another issue https://github.com/ultralytics/ultralytics/issues/2435:

> @TapendraBaduwal, thanks for your question! If you have image and label files in separate folders under the main data folder, you will need to specify the paths to both the image and label directories separately in the data.yaml file. This is necessary so that the YOLOv8 model can locate both the images and their associated labels during training and evaluation. Simply setting the path to the image folder will not suffice to locate the corresponding label files. Therefore, you will need to specify the paths to both the image and label folders in the data.yaml file.

But my yalm refuses to work:

```
 with open(f"{out_p}/data.yaml", "w") as f:
        f.write(
            f"""path: {DATASET_PATH}
train: images/train
val: images/val

labels: labels/segmentation/?

nc: x}
names: ["..."]}"""
        )
```

Thank you beforehand.

**Comment by glenn-jocher** [comment]
To use different label paths for your detector and segmentator models in YOLOv8, you need to specify the paths correctly in your `data.yaml` file. Based on the issue you've referenced, ensure your `data.yaml` looks like this:

```yaml
path: {DATASET_PATH}
train: images/train
val: images/val

labels:
  detection: labels/detection
  segmentation: labels/segmentation

nc: x
names: ["..."]
```

Then, in your training script, you can switch between the label paths based on whether you're training the detector or the segmentator. Make sure to load the correct `data.yaml` configuration for each training process.

If your `yaml` still refuses to work, ensure there are no syntax errors and that the paths you specified exist and are accessible.

**Comment by CastingSpell** [comment]
Thank you for your answer, however it does not work, I dont know if im doing something else wrong, this is what I'm getting:

```
train: Scanning /xxx/xxx/train_models/datasets/test_0/labels/train... 0 images
[...]

train: WARNING ⚠️ No labels found in /xxx/xxx/train_models/datasets/test_0/labels/train.cache. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
```

data.yaml
```
path: /home/aguia/train_models/datasets/lbd_2405/
train: images/train
val: images/val

labels:
    detection: labels/det
    segmentation: labels/seg


nc: x
names: ["..."]
```

Folder structure:
```
../train_models/datasets/test_0/
├── images
│   ├── train
│   └── val
└── labels
    └── det
        ├── train
        └── val
```
