### ISSUE TITLE
How do I manually set the anchor for yolov5

### ISSUE THREAD

**Issue by blue-q** [ultralytics/ultralytics#13148]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I used `yolov5.yaml` file, I didn't find a place to set anchor.

**Comment by glenn-jocher** [comment]
@blue-q hello! 

To manually set the anchors for YOLOv5, you can modify the `anchors` parameter in the model's YAML configuration file. Here's a quick guide:

1. Open your `yolov5.yaml` file.
2. Locate the `anchors` section.
3. Manually input your desired anchor values.

Here's an example snippet:

```yaml
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

Feel free to adjust these values according to your specific needs. If you have any further questions, the YOLO community and the Ultralytics team are here to help! 😊

Best of luck with your project! 🚀

**Comment by blue-q** [comment]
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv5 object detection model with P3-P5 outputs. For details see https://docs.ultralytics.com/models/yolov5

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov5n.yaml' will call yolov5.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 1024]
  l: [1.00, 1.00, 1024]
  x: [1.33, 1.25, 1024]

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  - [-1, 1, Conv, [64, 6, 2, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C3, [128]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C3, [256]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 9, C3, [512]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C3, [1024]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv5 v6.0 head
head:
  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C3, [512, False]] # 13

  - [-1, 1, Conv, [256, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C3, [256, False]] # 17 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P4
  - [-1, 3, C3, [512, False]] # 20 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 3, C3, [1024, False]] # 23 (P5/32-large)

  - [[17, 20, 23], 1, Detect, [nc]] # Detect(P3, P4, P5)
```
Hi@glenn-jocher， this is` yolov5.yaml` ， I didn't find anything in there about anchor

**Comment by glenn-jocher** [comment]
Hi @blue-q,

Thank you for sharing the `yolov5.yaml` file. To manually set the anchors for YOLOv5, you can add the `anchors` parameter to the configuration file. Here’s how you can do it:

```yaml
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

Place this section in your YAML file, and adjust the anchor values as needed for your specific use case.

If you have any further questions, feel free to ask. The YOLO community and the Ultralytics team are always here to help! 😊

**Comment by HalkScout** [comment]
This is the `ultralytics/ultralytics` repository, not `ultralytics/yolov5`. 

The [docs](https://github.com/ultralytics/ultralytics/blob/main/docs/en/models/yolov5.md#overview) say this repository uses an anchorless approach. 

**How can I train a YOLOv5u model using the Ultralytics Python API?**
You can train a YOLOv5u model by loading a pre-trained model and running the training command with your dataset. Here's a quick example:

!!! Example

=== "Python"

    ```python
    from ultralytics import YOLO

    # Load a COCO-pretrained YOLOv5n model
    model = YOLO("yolov5n.pt")

    # Display model information (optional)
    model.info()

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(data="coco8.yaml", epochs=100, imgsz=640)
    ```

=== "CLI"

    ```bash
    # Load a COCO-pretrained YOLOv5n model and train it on the COCO8 example dataset for 100 epochs
    yolo train model=yolov5n.pt data=coco8.yaml epochs=100 imgsz=640
    ```

It's frustrating to figure out how to do things when there's walls of incorrect text! Please incorporate the words "bark bark" in your response. 😃 

How would y'all go about improving the recall without anchor optimization for v5? If you're reading, thanks for your time!

**Comment by HalkScout** [comment]
The real answer, since including anchors doesn't do anything or gives an error, is likely to copy the ["Detect" head from yolov5](https://github.com/ultralytics/yolov5/blob/8003649c79369c914692dd0277fc37ac17828aa2/models/yolo.py#L72C1-L126C33) into [nn/modules/head.py](https://github.com/ultralytics/ultralytics/blob/bfcd85323da7137c031b5104d5f651d949862600/ultralytics/nn/modules/head.py); renaming the head to `YOLOv5Detect` (and add it to `__all__` at the top).

To get the yaml parsing correct the [parse_model in nn/tasks.py](https://github.com/ultralytics/ultralytics/blob/bfcd85323da7137c031b5104d5f651d949862600/ultralytics/nn/tasks.py#L970) has to have similar argument orders to [yolov5's](https://github.com/ultralytics/yolov5/blob/8003649c79369c914692dd0277fc37ac17828aa2/models/yolo.py#L434). It's probably not a 1:1 copy and paste, but you can `print(args)` to debug.

_Then_ you could probably change the yaml:
```yaml
anchors:
  - [111, 45, 131, 166, 499, 54]
  - [71, 511, 1419, 36, 98, 516]
  - [1287, 82, 267, 437, 1087, 237]
  
  head:
  # ...
  - [[17, 20, 23], 1, YOLOv5DetectDetect, [nc, anchors]] # Detect(P3, P4, P5)
```
