### ISSUE TITLE
Integrate new NN module

### ISSUE THREAD

**Issue by maudicito** [ultralytics/ultralytics#13339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know if i can modify the yolov8.yaml model without having to modify directly in the library and add the class model outside the library.

**Comment by glenn-jocher** [comment]
Hello,

Yes, you can modify the `yolov8.yaml` model configuration without altering the library directly. You can create a custom YAML file based on the original and make your modifications there, including adding new model classes. This allows you to maintain your changes separately and avoid conflicts with the library updates.

Simply copy the original YAML, make your changes, and then reference your custom YAML when training or running predictions. This approach keeps your custom configurations organized and easily manageable.

If you need further assistance or have more questions, feel free to ask!

**Comment by maudicito** [comment]
ok, I'll be more specific this time

I have the following kind of Module

```
class SpatialTransformer(nn.Module):
    def __init__(self, c1):
        #super().__init()
        super(SpatialTransformer, self).__init__()
        self.localization = nn.Sequential(
            nn.Conv2d(c1, 8, kernel_size=7),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True),
            nn.AdaptiveAvgPool2d(28),
            nn.ReLU(True)
        )
        # Calculate the size of the input to the fully connected layer
        self.fc_loc_size = 8*28*28 # Adjust for your input size
        self.fc_loc = nn.Sequential(
            nn.Linear(self.fc_loc_size, 32),
            nn.ReLU(True),
            nn.Linear(32, 3 * 2)
        )
        self.fc_loc[2].weight.data.zero_()
        self.fc_loc[2].bias.data.copy_(torch.tensor([1, 0, 0, 0, 1, 0], dtype=torch.float))

    def forward(self, x):
        # pdb.set_trace()
        xs = self.localization(x)
        # xs = xs.view(-1, self.fc_loc_size)
        xs=torch.flatten(xs,start_dim=1)
        # pdb.set_trace()
        theta = self.fc_loc(xs)
        theta = theta.view(-1, 2, 3)
        # theta=theta.expand(x.shape[0],-1,-1)
        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)
        return x
```
and my yolov8_custom.yaml is the next one

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1,1,SpatialTransformer ,[3]]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```

these are located in a folder called STN

when i Run the training process 


when I run the training process it tells me KeyError: 'SpatialTransformer', because it does not recognize my class that I generated, but I do not want to add it directly in block.py inside ultralytics in order not to create a dependency.

Is there anything I am missing? 
or what is my mistake? can you help me with this please?

**Comment by glenn-jocher** [comment]
@maudicito hello,

It looks like you've done a great job setting up your custom module and integrating it into the YOLOv8 configuration. The issue you're encountering with the `KeyError: 'SpatialTransformer'` arises because the YOLOv8 framework does not automatically recognize custom modules that are not predefined in its architecture files.

To resolve this, you can dynamically import your custom module so that it becomes recognizable by the YOLO framework without modifying the internal files like `block.py`. Here’s a general approach on how you can do this:

1. **Ensure your module is accessible**: Place your `SpatialTransformer` module in a directory that is in the Python path, or append the module's directory to the Python path at runtime.

2. **Dynamically import your module**: Before initializing or loading the model configuration, dynamically import your custom module. You can use Python's built-in `importlib` for this purpose. Here's a small snippet you can run before your training script:

    ```python
    import importlib.util
    import sys

    # Path to the directory containing your module
    module_path = '/path/to/your/module/directory'
    if module_path not in sys.path:
        sys.path.append(module_path)

    # Import your module
    spec = importlib.util.spec_from_file_location("SpatialTransformer", "/path/to/SpatialTransformer.py")
    spatial_transformer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(spatial_transformer)
    ```

3. **Use the imported module**: After importing, your `SpatialTransformer` class will be recognized by the YOLO framework, and you can proceed with training as usual.

This method allows you to keep your custom modules separate from the Ultralytics codebase, thus avoiding any direct modifications and making your project easier to manage and upgrade.

Let me know if this helps or if you have any more questions!

**Comment by maudicito** [comment]
the solution did not work for me, is there any other option?

**Comment by glenn-jocher** [comment]
Hello @maudicito,

I'm sorry to hear that the solution didn't work for you. Let's try another approach. Could you please ensure that your custom module is correctly defined and accessible from your script? Sometimes, a simple error in the path or module name can cause the import to fail.

Additionally, you might want to try placing your `SpatialTransformer` class directly in the script where you're configuring and running the model, just to test if it's recognized when not imported from another file.

If these suggestions don't resolve the issue, could you provide more details about the error message you're receiving? This information will help us better understand what might be going wrong.

Looking forward to your response!

**Comment by maudicito** [comment]
this time I want to be even more explicit haha

my project structure is as follows:


![image](https://github.com/ultralytics/ultralytics/assets/168103649/ebb0254e-80e3-48da-98d5-d549a91aa5b1)

I share with you the content of the files that work together


**spatial_transformer.py**

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class SpatialTransformer(nn.Module):
    def __init__(self, c1):
        #super().__init()
        super(SpatialTransformer, self).__init__()
        self.localization = nn.Sequential(
            nn.Conv2d(c1, 8, kernel_size=7),
            nn.MaxPool2d(2, stride=2),
            nn.ReLU(True),
            nn.AdaptiveAvgPool2d(28),
            nn.ReLU(True)
        )
        # Calculate the size of the input to the fully connected layer
        self.fc_loc_size = 8*28*28 # Adjust for your input size
        self.fc_loc = nn.Sequential(
            nn.Linear(self.fc_loc_size, 32),
            nn.ReLU(True),
            nn.Linear(32, 3 * 2)
        )
        self.fc_loc[2].weight.data.zero_()
        self.fc_loc[2].bias.data.copy_(torch.tensor([1, 0, 0, 0, 1, 0], dtype=torch.float))

    def forward(self, x):
        # pdb.set_trace()
        xs = self.localization(x)
        # xs = xs.view(-1, self.fc_loc_size)
        xs=torch.flatten(xs,start_dim=1)
        # pdb.set_trace()
        theta = self.fc_loc(xs)
        theta = theta.view(-1, 2, 3)
        # theta=theta.expand(x.shape[0],-1,-1)
        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)
        return x
```

**yolov8_stn.yaml**
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, SpatialTransformer ,[3]]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```


**initialize_model.py**
```
# -*- coding: utf-8 -*-
"""
Functions to train/test model
"""
## Python standard libraries
from ultralytics import YOLO


def initialize_model(model_name):
    
    model_ft = None
    
  
    #Select backbone architecture
    if model_name == "YOLOV8N":

        model_ft = YOLO('yolov8n.yaml')

    elif model_name == "YOLOV8M":
        
        model_ft = YOLO('yolov8m.yaml')

    elif model_name == "YOLOV8L":

        model_ft = YOLO('STN\\yolov8_stn.yaml')
    
    else:
        raise RuntimeError('{} not implemented'.format(model_name))
    

    return model_ft
```


**main.py**

```
# -*- coding: utf-8 -*-
Main script for LACE experiments

import argparse
import importlib.util
import os
import sys

import numpy as np
import torch
import matplotlib.pyplot as plt

from Utils.Initialize_model import initialize_model
from yaml import load , CLoader as Loader
#Turn off plotting
plt.ioff()

dir_actua = os.getcwd()
module_path = f'{dir_actua}\\STN'
if module_path not in sys.path:
    sys.path.append(module_path)

# Import your module
spec = importlib.util.spec_from_file_location("SpatialTransformer", "STN\\spatial_transformer.py")
spatial_transformer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(spatial_transformer)


def main(args):
    
    with open(args.yaml , 'r') as stream:
        out = load(stream, Loader=Loader)

    # Name of dataset
    Dataset ="button"
    
    # Model(s) to be used
    model_name = args.model
    
    # Number of runs and/or splits for dataset
    numRuns = out['num_runs']
    
    # Detect if we have a GPU available
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    print('Starting Experiments...')
    
    for split in range(0, numRuns):
        #Set same random seed based on split and fairly compare
        #eacah embedding approach
        torch.manual_seed(split)
        np.random.seed(split)
        np.random.seed(split)
        torch.cuda.manual_seed(split)
        torch.cuda.manual_seed_all(split)
        torch.manual_seed(split)
                

        # Initialize the histogram model for this run
        model_ft = initialize_model(model_name)

        
        # Send the model to GPU if available, use multiple if available
        if torch.cuda.device_count() > 1:
            print("Using", torch.cuda.device_count(), "GPUs!")
            # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
            list_device= np.arange(0, torch.cuda.device_count(), 1)
            list_device.tolist()
        else:
            list_device = device.type   
        # from info select the number of parameters for the model
        

        if args.feature_extraction:
            mode = 'feature_extract'
        else:
            mode = 'fine_tuning'

        # TRAIN VAL AND TEST USING ULTRALETYCS and store in runs 
        project = '{}/{}/{}/{}'.format(args.folder,
                                            mode,
                                            Dataset,
                                            model_name)
        name='Run_{}'.format(split+1)
        ## TRAIN 
        model_ft.train(data=args.yaml, epochs= args.num_epochs, workers=4, batch=args.train_batch_size ,imgsz=args.resize_size, 
                        device= list_device,pretrained=args.use_pretrained, project = project, name= name,save=args.save_results,
                       seed = split)
        
        print('**********Run ' + str(split + 1) + model_name + ' Finished**********')
       

def parse_args():
    parser = argparse.ArgumentParser(description='Run Angular Losses and Baseline experiments for dataset')
    parser.add_argument('--save_results', default=True, action=argparse.BooleanOptionalAction,
                        help='Save results of experiments(default: True)')
    
    parser.add_argument('--folder', type=str, default='Saved_Models/Test_Code/',
                        help='Location to save models')
    
    parser.add_argument('--yaml', type=str, default='data.yaml',
                        help='Location to save models')
    
    parser.add_argument('--feature_extraction', default=True, action=argparse.BooleanOptionalAction,
                        help='Flag for feature extraction. False, train whole model. True, only update fully connected/encoder parameters (default: True)')
    
    parser.add_argument('--use_pretrained', default=True, action=argparse.BooleanOptionalAction,
                        help='Flag to use pretrained model from ImageNet or train from scratch (default: True)')
    
    parser.add_argument('--train_batch_size', type=int, default=32,
                        help='input batch size for training (default: 128)')
    
    parser.add_argument('--val_batch_size', type=int, default=32,
                        help='input batch size for validation (default: 512)')
    
    parser.add_argument('--test_batch_size', type=int, default=32,
                        help='input batch size for testing (default: 256)')
    
    parser.add_argument('--num_epochs', type=int, default=100,
                        help='Number of epochs to train each model for (default: 50)')
    
    parser.add_argument('--resize_size', type=int, default=640,
                        help='Resize the image before center crop. (default: 256)')
    
    parser.add_argument('--lr', type=float, default=0.001,
                        help='learning rate (default: 0.01)')
    parser.add_argument('--model', type=str, default='YOLOV8L',
                        help='backbone architecture to use (default: 0.01)')
    parser.add_argument('--use-cuda', action='store_true', default=True,
                        help='enables CUDA training')
    args = parser.parse_args()
    return args

if __name__ == "__main__":
    args = parse_args()
    use_cuda = args.use_cuda and torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")
    main(args)
```
      


**if you check the code in main.py I added the solution you gave me**

and this is the error in console

```
Backend tkagg is interactive backend. Turning interactive mode on.cmain.py' ;1777b488-1cda-4b9d-80b6-06bfadffe49f
Starting Experiments...
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
Traceback (most recent call last):
  File "C:\Users\mbautista\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mbautista\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 284, in run_file      
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\mbautista\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\tickets\MSD-5258\STN-YOLO\main.py", line 139, in <module>
    main(args)
  File "C:\tickets\MSD-5258\STN-YOLO\main.py", line 61, in main
    model_ft = initialize_model(model_name)
  File "C:\tickets\MSD-5258\STN-YOLO\Utils\Initialize_model.py", line 25, in initialize_model
    model_ft = YOLO('STN\\yolov8_stn.yaml')
  File "c:\tickets\MSD-5258\STN-YOLO\.venv\lib\site-packages\ultralytics\engine\model.py", line 92, in __init__
    self._new(model, task)
  File "c:\tickets\MSD-5258\STN-YOLO\.venv\lib\site-packages\ultralytics\engine\model.py", line 128, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "c:\tickets\MSD-5258\STN-YOLO\.venv\lib\site-packages\ultralytics\nn\tasks.py", line 232, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "c:\tickets\MSD-5258\STN-YOLO\.venv\lib\site-packages\ultralytics\nn\tasks.py", line 678, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'SpatialTransformer'
```

Can you locate what my mistake was this time? did I add something wrong? please
