### ISSUE TITLE
question about ultralytics formatting bot

### ISSUE THREAD

**Issue by inisis** [ultralytics/ultralytics#13544]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher Thanks for adding auto formatting bot to [onnxslim](https://github.com/inisis/OnnxSlim), however it fails to run if the pr is created not by you , you can check it [here](https://github.com/inisis/OnnxSlim/actions/runs/9458596500/job/26054346765#step:2:194). How can I solve this, thank you.

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thank you for reaching out and for your interest in the auto-formatting bot! It looks like the issue you're encountering is related to the permissions and configurations of the GitHub Actions workflow.

To help you resolve this, please ensure the following:

1. **Permissions**: Verify that the GitHub Actions workflow has the necessary permissions to run on pull requests from contributors other than the repository owner. You can do this by checking the repository settings under `Settings > Actions > General` and ensuring that workflows are allowed to run for pull requests from forks.

2. **Workflow Configuration**: Ensure that the workflow file (`.github/workflows/your-workflow-file.yml`) is correctly configured to trigger on pull requests. Here’s an example configuration snippet:
    ```yaml
    name: Auto-formatting Bot

    on:
      pull_request:
        branches:
          - main

    jobs:
      format:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Run formatter
            run: |
              # Your formatting commands here
    ```

3. **Token Permissions**: Make sure that the GitHub token used in the workflow has the necessary permissions. By default, the `GITHUB_TOKEN` has read and write permissions on the repository. If you are using a custom token, ensure it has the correct scopes.

If the issue persists, please provide a minimum reproducible example of your workflow configuration and any relevant logs. This will help us better understand the problem and provide a more accurate solution. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to update us with any additional information or questions you might have. We're here to help! 😊

**Comment by inisis** [comment]
@glenn-jocher I still can not get it to work, can you help me fix it. https://github.com/inisis/OnnxSlim/actions/runs/9591137863/job/26447570285

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thank you for providing the link to the workflow run. To help you effectively, could you please ensure the following:

1. **Minimum Reproducible Example**: If you haven't already, please provide a minimum reproducible example of your workflow configuration. This will help us understand the issue better. You can find guidance on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Package Versions**: Ensure that you are using the most recent versions of `torch` and `ultralytics`. If not, please upgrade your packages and try running the workflow again.

Here's a quick checklist to verify your workflow configuration:
- **Permissions**: Confirm that the workflow has the necessary permissions to run on pull requests from contributors.
- **Workflow Triggers**: Ensure the workflow is set to trigger on pull requests:
    ```yaml
    on:
      pull_request:
        branches:
          - main
    ```
- **Token Permissions**: Verify that the `GITHUB_TOKEN` or any custom token used has the appropriate scopes.

If the issue persists, please share the relevant parts of your workflow configuration and any error messages you are encountering. This will help us diagnose the problem more accurately.

Looking forward to your response! 😊
