### ISSUE TITLE
Is there possibility to train YOLO model over multiple datasets?

### ISSUE THREAD

**Issue by dexforint** [ultralytics/ultralytics#14040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have several datasets on Kaggle in YOLO format. Do I have to unite them to train YOLO model? Is there possibility to train YOLO model over multiple datasets?

For example I would can use this `data.yaml` configuration:
```yaml
train: [/kaggle/input/dataset-1/train, /kaggle/input/dataset-2/train, /kaggle/input/dataset-3/train]
val: [/kaggle/input/dataset-1/val, /kaggle/input/dataset-2/val, /kaggle/input/dataset-3/val]
test: /kaggle/input/test-dataset/test

nc: 3
names: ["obj1", "obj2", "obj3"]
```

**Comment by glenn-jocher** [comment]
@dexforint hello!

Yes, you can indeed train a YOLO model using multiple datasets without having to unite them into a single dataset. Your approach of specifying multiple paths in the `data.yaml` configuration is correct and supported by Ultralytics YOLO.

Here's an example of how you can structure your `data.yaml` file to include multiple datasets:

```yaml
path:  # Leave empty or specify a root path if applicable
train: 
  - /kaggle/input/dataset-1/train
  - /kaggle/input/dataset-2/train
  - /kaggle/input/dataset-3/train
val: 
  - /kaggle/input/dataset-1/val
  - /kaggle/input/dataset-2/val
  - /kaggle/input/dataset-3/val
test: /kaggle/input/test-dataset/test

nc: 3
names: ["obj1", "obj2", "obj3"]
```

This configuration allows you to train your model across multiple datasets seamlessly. Each dataset path is listed under the `train` and `val` keys, and the model will iterate through all specified paths during training and validation.

To get started with training using this configuration, you can use the following command:

```bash
yolo detect train data=data.yaml model=yolov8n.pt epochs=100 imgsz=640
```

This command will initiate the training process using the datasets specified in your `data.yaml` file.

If you encounter any issues or have further questions, please feel free to ask. Happy training! 🚀

**Comment by dexforint** [comment]
Thank you VERY MUCH! You answers are fast and helpful! THANK YOU!

**Comment by glenn-jocher** [comment]
Hello @dexforint,

Thank you for your kind words! 😊 The YOLO community and the Ultralytics team are always here to help.

Regarding your question about training YOLO models over multiple datasets, your approach is spot on. Specifying multiple paths in the `data.yaml` configuration is a great way to handle multiple datasets. Here’s a quick recap of how you can structure your `data.yaml`:

```yaml
path:  # Leave empty or specify a root path if applicable
train: 
  - /kaggle/input/dataset-1/train
  - /kaggle/input/dataset-2/train
  - /kaggle/input/dataset-3/train
val: 
  - /kaggle/input/dataset-1/val
  - /kaggle/input/dataset-2/val
  - /kaggle/input/dataset-3/val
test: /kaggle/input/test-dataset/test

nc: 3
names: ["obj1", "obj2", "obj3"]
```

This setup allows you to train your model across multiple datasets seamlessly. To start training, you can use:

```bash
yolo detect train data=data.yaml model=yolov8n.pt epochs=100 imgsz=640
```

If you encounter any issues, please ensure you are using the latest version of the Ultralytics packages. If the problem persists, providing a minimum reproducible example can greatly help us diagnose the issue. You can find more information on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy training! 🚀
