### ISSUE TITLE
New YOLOv# Format for Pose Estimation with Keypoints Labels

### ISSUE THREAD

**Issue by d-kleine** [ultralytics/ultralytics#14405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The proposed feature is to introduce a new YOLOv# format (v9, v10, etc.) specifically designed for pose estimation tasks that includes key point labels. This format would enhance the current YOLOv8 capabilities by allowing users to annotate and train models not only for object detection but also for pose estimation. The new format will include key point coordinates (as in v8) but also keypoint labels, making it more versatile for applications such as human pose estimation, animal tracking, and robotic arm positioning. An information about the keypoint labels is currently not implemented in the YOLOv8 format for pose estimation.

![grafik](https://github.com/user-attachments/assets/8d70a031-a33d-48c3-af4c-a3006c666f7a)

### Use case

The new format will streamline the process of annotating and training pose estimation models by:
- Allowing users to include keypoint labels directly in the annotation files.
- Simplifying the integration of pose estimation data with existing YOLOv# workflows.
-  Enhancing the accuracy and efficiency of pose estimation tasks by providing a standardized format for keypoint annotations.
- Verify the mapping between keypoint IDs and their corresponding keypoint labels to ensure the accuracy and interpretability of the ground truth but also the model's predictions.

### Additional

As an idea, to implement this feature, by extending the YAML configuration file to include parameters for keypoint detection. This includes specifying the number of keypoints, their dimensions, but also their labels.

Example YAML Configuration:
```yaml
path: ../dataset  # root directory of the dataset
train: images/train  # training images (relative to 'path')
val: images/val  # validation images (relative to 'path')
test: images/test  # test images (optional)

# number of classes
nc: 2

# class names
names: ["person", "car"]

# keypoint parameters
kpt_shape: [10, 3]  # total number of keypoints (5 for person + 5 for car), number of dimensions (x, y, visibility)

# keypoint labels for each class (sorted in ascending order by keypoint ID)
kpt_labels:
  person:
    - nose            # keypoint ID 0
    - left_eye        # keypoint ID 1
    - right_eye       # keypoint ID 2
    - left_ear        # keypoint ID 3
    - right_ear       # keypoint ID 4
  car:
    - front_left_wheel  # keypoint ID 0
    - front_right_wheel # keypoint ID 1
    - rear_left_wheel   # keypoint ID 2
    - rear_right_wheel  # keypoint ID 3
    - roof              # keypoint ID 4
```

or having the keypoint name labels provided along the keypoint ID labels:
```yaml
...
# keypoint labels for each class (sorted in ascending order by keypoint ID)
keypoint_mappings:
  person:
    0: nose            # keypoint ID 0
    1: left_eye        # keypoint ID 1
    2: right_eye       # keypoint ID 2
    3: left_ear        # keypoint ID 3
    4: right_ear       # keypoint ID 4
  car:
    0: front_left_wheel  # keypoint ID 0
    1: front_right_wheel # keypoint ID 1
    2: rear_left_wheel   # keypoint ID 2
    3: rear_right_wheel  # keypoint ID 3
    4: roof              # keypoint ID 4
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
