### ISSUE TITLE
why yolo8s.pt have 86M?

### ISSUE THREAD

**Issue by zhu709654396** [ultralytics/ultralytics#1497]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

why yolo8s.pt have 86M?

**Comment by AyushExel** [comment]
<img width="785" alt="Screenshot 2023-03-20 at 11 08 01 AM" src="https://user-images.githubusercontent.com/15766192/226255472-6b24c78c-0cfb-4dc7-acec-da403792c112.png">
It has 11M parameters

**Comment by zhu709654396** [comment]
> <img alt="Screenshot 2023-03-20 at 11 08 01 AM" width="785" src="https://user-images.githubusercontent.com/15766192/226255472-6b24c78c-0cfb-4dc7-acec-da403792c112.png">
> 
> It has 11M parameters

This happens when I'm training my dataset

**Comment by AyushExel** [comment]
What is the number of classes in your dataset?

**Comment by zhu709654396** [comment]
> What is the number of classes in your dataset?

12 classes

**Comment by Laughing-q** [comment]
@zhu709654396 The model size could be larger while training because the pt file includes extra info like optimizer:
```python
        ckpt = {
            'epoch': self.epoch,
            'best_fitness': self.best_fitness,
            'model': deepcopy(de_parallel(self.model)).half(),
            'ema': deepcopy(self.ema.ema).half(),
            'updates': self.ema.updates,
            'optimizer': self.optimizer.state_dict(),
            'train_args': vars(self.args),  # save as dict
            'date': datetime.now().isoformat(),
            'version': __version__}
``` 
The pt files would be stripped when the training is done so you might get larger pt file if you interrupted your training. 

Also our official models have stripped these extra keys, so the model size is smaller.
[https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516](https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516)
If you run `strip_optimizer` with your trained model, the model size should be similar with the official ones.
```python
from ultralytics.yolo.utils.torch_utils import strip_optimizer
strip_optimizer("model.pt")
```

**Comment by AyushExel** [comment]
Ahh you were talking about file size. I thout 86M was param count

**Comment by zhu709654396** [comment]
> 
thanks

**Comment by zhu709654396** [comment]
> 啊，你在谈论文件大小。我认为 86M 是参数计数

I remember the same for Yolov 5, which will decrease a lot after training，but yolov8 workers>0 error,so i set workers=0,very slow，GPU-Util Most of the time is equal to 0

**Comment by Laughing-q** [comment]
@zhu709654396 would you mind to provide a reproducible example about the error you said `workers>0`?

**Comment by zhu709654396** [comment]
> @zhu709654396 would you mind to provide a reproducible example about the error you said `workers>0`?

yes,I have submitted relevant questions:https://github.com/ultralytics/ultralytics/issues/1498

**Comment by Laughing-q** [comment]
@zhu709654396 官方最终的yolov8s.onnx也是22M

**Comment by zhu709654396** [comment]
> @zhu709654396 官方最终的yolov8s.onnx也是22M

我在readme中看的如下：

YOLOv8s | 640 | 44.9 | 128.4 | 1.20 | 11.2 | 28.6
其中11.2是参数，我下载的yolov8s.pt也确实是22M

另外,请问为什么将int8=True或者simplify=True，onnx将会扩大一倍

**Comment by Laughing-q** [comment]
@zhu709654396 int8 是处理TF格式的，和onnx无关。onnx的大小和数据精度有关，对于yolov8s模型来说fp16就是22M, fp32就是44M。只要你没有设置`half=True`都会生成fp32的，就是44M

**Comment by zhu709654396** [comment]
> @zhu709654396 int8 是处理TF格式的，和onnx无关。onnx的大小和数据精度有关，对于yolov8s模型来说fp16就是22M, fp32就是44M。只要你没有设置`half=True`都会生成fp32的，就是44M

感谢回答

**Comment by Laughing-q** [comment]
@zhu709654396 没什么问题我就关闭这个issue了哈，有相关问题请随时重新打开，谢谢！

**Comment by zhu709654396** [comment]
> @zhu709654396没有什么问题我就关掉这个issue了哈，有相关问题请随时重新打开，谢谢！

好的

**Comment by Jerryporter** [comment]
### Issue Description

#### Summary
I noticed that my `yolov8s.pt` model is 22MB in size, despite not using the half precision option (`half=False`). When validating the model, the number of parameters is approximately 11M, which should result in a model size of around 44MB in FP32 format. Can you please help me understand why there is a discrepancy in the model size?

#### Details
Here are the details of my training and validation setup:

1. **Training Script:**
    ```python
    from ultralytics import YOLO

    if __name__ == '__main__':
        # Load a model
        model = YOLO("yolov8s.yaml").load("yolov8s.pt")  # build from YAML and transfer weights

        # Train the model
        results = model.train(data="D:\\AI\\样本\\yolo_format\\yolov8n.yaml", epochs=300, imgsz=640)
    ```

2. **Validation Script:**
    ```python
    from ultralytics import YOLO

    if __name__ == '__main__':
        metrics = YOLO('runs/detect/train11/weights/best.pt').val(save_json=True)
    ```

3. **Model Parameters Output:**
    ```
    YOLOv8s summary (fused): 168 layers, 11133324 parameters, 0 gradients, 28.5 GFLOPs
    ```

4. **Training Configuration (args.yaml):**
    ```yaml
    task: detect
    mode: train
    model: yolov8s.yaml
    data: D:\AI\样本\yolo_format\yolov8n.yaml
    epochs: 300
    time: null
    patience: 100
    batch: 16
    imgsz: 640
    save: true
    save_period: -1
    cache: false
    device: null
    workers: 8
    project: null
    name: train11
    exist_ok: false
    pretrained: true
    optimizer: auto
    verbose: true
    seed: 0
    deterministic: true
    single_cls: false
    rect: false
    cos_lr: false
    close_mosaic: 10
    resume: false
    amp: true
    fraction: 1.0
    profile: false
    freeze: null
    multi_scale: false
    overlap_mask: true
    mask_ratio: 4
    dropout: 0.0
    val: true
    split: val
    save_json: false
    save_hybrid: false
    conf: null
    iou: 0.7
    max_det: 300
    half: false
    dnn: false
    plots: true
    source: null
    vid_stride: 1
    stream_buffer: false
    visualize: false
    augment: false
    agnostic_nms: false
    classes: null
    retina_masks: false
    embed: null
    show: false
    save_frames: false
    save_txt: false
    save_conf: false
    save_crop: false
    show_labels: true
    show_conf: true
    show_boxes: true
    line_width: null
    format: torchscript
    keras: false
    optimize: false
    int8: false
    dynamic: false
    simplify: false
    opset: null
    workspace: 4
    nms: false
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 7.5
    cls: 0.5
    dfl: 1.5
    pose: 12.0
    kobj: 1.0
    label_smoothing: 0.0
    nbs: 64
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    bgr: 0.0
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    auto_augment: randaugment
    erasing: 0.4
    crop_fraction: 1.0
    cfg: null
    tracker: botsort.yaml
    save_dir: runs\detect\train11
    ```

I appreciate any insights you can provide to resolve this issue. Thank you!

---
