### ISSUE TITLE
Got an error in class v8SegmentationLoss while using  yolov8-seg.yaml to train my own dataset with 5 classes(nc=5)

### ISSUE THREAD

**Issue by lanbinvivy** [ultralytics/ultralytics#15654]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/3 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "d:\python-workspace\ssc\ml\yolo\yolo8\train.py", line 12, in <module>
    model.train(
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\engine\model.py", line 812, in train
    self.trainer.train()
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\engine\trainer.py", line 385, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\.conda\envs\newest\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\.conda\envs\newest\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\nn\tasks.py", line 101, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\nn\tasks.py", line 283, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python-workspace/yolo8/ultralytics-main\ultralytics\utils\loss.py", line 274, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[69, 69, -1]' is invalid for input of size 441600

### Environment

**I download the utralytics code to run train process instead of installing it, my codes are below:**

```
sys.path.append(root_path+'/yolo8/ultralytics-main')

from ultralytics.models.yolo.model import YOLO

if __name__ == '__main__':
    model = YOLO('yolov8.yaml', task="segment")  
    model.train(
        data='D:\python-workspace\ssc\ml\yolo\yolo8\stock.yaml',
        epochs=10,
        imgsz=1024
    )
```

### Minimal Reproducible Example

**Model：yolov8-seg.yaml as below:**

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-seg instance segmentation model. For Usage examples see https://docs.ultralytics.com/tasks/segment

# Parameters
nc: 5 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-seg.yaml' will call yolov8-seg.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Segment, [nc, 32, 256]] # Segment(P3, P4, P5)

```

**my own dataset as below:**

```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../../../../../datasets/stock # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images
test: # test images (optional)

# Classes
names:
  0: raise
  1: fall
  2: surge
  3: crash
  4: sideway
```

### Additional
when i add 11 meaningless classes so the nc=16, so the output size turn to 80(16*4+16), then this problem no longer show up, but a new error in the class v8SegmentationLoss raise up from code line 281（“pred_masks = pred_masks.permute(0, 2, 1).contiguous()”）：permute(sparse_coo): number of dimensions in the tensor input does not match... ...

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
