### ISSUE TITLE
Discrepancy in Training Loss and Accuracy when Loading YOLOv8 Model with Custom Config

### ISSUE THREAD

**Issue by aminchini** [ultralytics/ultralytics#16520]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am trying to train a YOLOv8 model on a custom dataset using the pretrained weights from `yolov8l.pt`. However, I am observing a significant difference in the initial training loss and accuracy depending on how I load the model.

### Case 1: Using Pretrained YOLOv8 Model Directly
When I load the model using the following code:
```python
model = YOLO('yolov8l.pt')
```
The training loss and accuracy behave as expected.

### Case 2: Using Custom Configuration and Loading Pretrained Weights Manually
When I load the model using a custom configuration file and manually load the pretrained weights, the initial training loss and accuracy differ significantly compared to the first case.

```python
model = YOLO(config_path)
model = model.cuda()
pret_state_dict = torch.load('path to model file').state_dict()
model.load_state_dict(pret_state_dict)
```

The custom config is as follows:

```yaml
# Parameters
nc: 80  # number of classes
scales: 
  # [depth, width, max_channels]
  l: [1.00, 1.00, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]                                 # 0
  - [-1, 1, Conv, [128, 3, 2]]                                # 1
  - [-1, 3, C2f, [128, True]]                                 # 2
  - [-1, 1, Conv, [256, 3, 2]]                                # 3
  - [-1, 6, C2f, [256, True]]                                 # 4
  - [-1, 1, Conv, [512, 3, 2]]                                # 5
  - [-1, 6, C2f, [512, True]]                                 # 6
  - [-1, 1, Conv, [1024, 3, 2]]                               # 7
  - [-1, 3, C2f, [1024, True]]                                # 8
  - [-1, 1, SPPF, [1024, 5]]                                  # 9

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]                # 10
  - [[-1, 6], 1, Concat, [1]]                                 # 11
  - [-1, 3, C2f, [512]]                                       # 12
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]                # 13
  - [[-1, 4], 1, Concat, [1]]                                 # 14
  - [-1, 3, C2f, [256]]                                       # 15
  - [-1, 1, Conv, [256, 3, 2]]                                # 16
  - [[-1, 12], 1, Concat, [1]]                                # 17
  - [-1, 3, C2f, [512]]                                       # 18
  - [-1, 1, Conv, [512, 3, 2]]                                # 19
  - [[-1, 9], 1, Concat, [1]]                                 # 20
  - [-1, 3, C2f, [1024]]                                      # 21
  - [[15, 18, 21], 1, Detect, [nc]]                           # 22
```

### Expected Behavior:
The training loss and accuracy should be similar regardless of how the model is loaded, as the same pretrained weights are being used.

### Actual Behavior:
- **Case 1:** The training loss and accuracy start as expected.
- **Case 2:** The training loss and accuracy differ significantly from Case 1 when loading the model with the custom configuration and pretrained weights.

### Possible Issues:
There could be an issue with how the pretrained weights are being loaded into the model when using the custom configuration or with the initialization of the model in this scenario.

### Request:
Please help identify why there is a difference in the initial training behavior between the two methods of loading the model.

### Additional

Additionally, I need to add some layers to the backbone of the model as adapter and then load the pre-trained model weights and freeze them.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @aminchini, thank you for reaching out to Ultralytics 🚀! We appreciate your detailed description of the issue you're encountering with loading YOLOv8 models.

If this is a 🐛 Bug Report, we would appreciate a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us diagnose the issue effectively.

Here are a few steps for troubleshooting:

1. **Ensure your environment is up-to-date**: Upgrade to the latest `ultralytics` package and verify that all dependencies are correctly installed:

   ```bash
   pip install -U ultralytics
   ```

2. **Check your environment**: Run YOLOv8 in one of our verified environments:

   - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

   - **Others**: Follow our guides for [GCP](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/), or [Docker](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) environments.

3. **Consult the [Documentation](https://docs.ultralytics.com)**: Ensure you’re following best practices for [custom training](https://docs.ultralytics.com/guides/model-training-tips/).

Join our community for further assistance. For real-time support, visit [Discord](https://ultralytics.com/discord) 🎧. For more detailed discussions, check out our [Discourse](https://community.ultralytics.com) forum. You can also engage with our community on [Reddit](https://reddit.com/r/ultralytics).

This is an automated response, but rest assured that an Ultralytics engineer will assist you soon. Thank you for your patience 😊!

**Comment by Y-T-G** [comment]
Ultralytics provides a `load()` method to load weights from the model checkpoint.

`model.load('checkpoint.pt')`

You should be using that.

**Comment by glenn-jocher** [comment]
@Y-T-G yes that's correct. You can start from a YAML or a PyTorch file and then load any other weights onto it using `model.load()` afterward.

See https://docs.ultralytics.com/modes/train for details.

**Comment by glenn-jocher** [comment]
<img width="962" alt="Screenshot 2024-09-28 at 16 50 14" src="https://github.com/user-attachments/assets/947f2869-248b-4376-a921-9ce60057ab40">

**Comment by aminchini** [comment]
Yes, that's correct, but what if I need to modify the YAML file by adding new layers, then load the weights of the existing layers from the pre-trained model while initializing the newly added layers randomly?

**Comment by Y-T-G** [comment]
Using `.load()` will load the pretrained weights for the layers until it finds a layer that doesn't match. So even if you add layers, it should load those weights. Whatever is left unmatched is kept randomized.

**Comment by Y-T-G** [comment]
If you want to use `load_state_dict()`, then you will have to use a callback and load it before training.

```python
def load_sd(trainer):
    from ultralytics import YOLO
    sd = YOLO("yolov8n.pt").model
    trainer.model.load_state_dict(sd)

model = YOLO("yolov8n.yaml")
model.add_callback("on_pretrain_routine_start", load_sd)
results = model.train(data="coco128.yaml", epochs=5)
```

**Comment by aminchini** [comment]
Thank you @Y-T-G and @glenn-jocher,  
As you mentioned, using `.load()` will load the pre-trained weights for all layers **up to** the point where a mismatch is encountered. But if I want to insert additional layers in the middle of the network and still load weights for all the matching layers, how can this be achieved?

**Comment by Y-T-G** [comment]
@aminchini If you insert a layer in between, then the layer names will change, so you will have to manually adjust the layer names, especially the number before you can load the weights.

**Comment by aminchini** [comment]
Consider this Yaml file:
```yaml
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  l: [1.00, 1.00, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]                                 # 0  0
  - [-1, 1, Conv, [128, 3, 2]]                                # 1  1
  - [-1, 3, C2f, [128, True]]                                 # 2  2
  - [1, 1, nn.Conv2d, [128, 128, 1, 1, 0, 1, 1, False]]       #    3
  - [-1, 1, nn.ReLU, []]                                      #    4
  - [-1, 1, nn.Conv2d, [128, 128, 1, 1, 0, 1, 1, False]]      #    5
  - [[-1, 2], 1, ResAdd, []]                                  #    6
  - [-1, 1, Conv, [256, 3, 2]]                                # 3  7
  - [-1, 6, C2f, [256, True]]                                 # 4  8
  - [-1, 1, Conv, [512, 3, 2]]                                # 5  9
  - [-1, 6, C2f, [512, True]]                                 # 6  10
  - [-1, 1, Conv, [1024, 3, 2]]                               # 7  11
  - [-1, 3, C2f, [1024, True]]                                # 8  12
  - [-1, 1, SPPF, [1024, 5]]                                  # 9  13

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]               # 10 14
  - [[-1, 10], 1, Concat, [1]]                               # 11 15
  - [-1, 3, C2f, [512]]                                      # 12 16
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]               # 13 17
  - [[-1, 8], 1, Concat, [1]]                                # 14 18
  - [-1, 3, C2f, [256]]                                      # 15 19
  - [-1, 1, Conv, [256, 3, 2]]                               # 16 20
  - [[-1, 16], 1, Concat, [1]]                               # 17 21
  - [-1, 3, C2f, [512]]                                      # 18 22
  - [-1, 1, Conv, [512, 3, 2]]                               # 19 23
  - [[-1, 13], 1, Concat, [1]]                               # 20 24
  - [-1, 3, C2f, [1024]]                                     # 21 25
  - [[19, 22, 25], 1, Detect, [nc]]                          # 22 26
 ```
And new block, ResAdd is added as follows:
```python
class ResAdd(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.add(x[0], x[1])
```
Then I tried to load weights as follows:

```python
config_path = '/content/adapter_v3.yaml'
base_ckpt_path = '/content/yolov8l.pt'
model = YOLO(config_path)
model = model.cuda()

layers_mapping = {
    '0': '0',  # Conv [64, 3, 2]
    '1': '1',  # Conv [128, 3, 2]
    '2': '2',  # C2f [128, True]
    '3': '7',  # Conv [256, 3, 2]
    '4': '8',  # C2f [256, True]
    '5': '9',  # Conv [512, 3, 2]
    '6': '10', # C2f [512, True]
    '7': '11', # Conv [1024, 3, 2]
    '8': '12', # C2f [1024, True]
    '9': '13', # SPPF [1024, 5]
    '10': '14', # nn.Upsample
    '11': '15', # Concat [1]
    '12': '16', # C2f [512]
    '13': '17', # nn.Upsample
    '14': '18', # Concat [1]
    '15': '19', # C2f [256]
    '16': '20', # Conv [256, 3, 2]
    '17': '21', # Concat [1]
    '18': '22', # C2f [512]
    '19': '23', # Conv [512, 3, 2]
    '20': '24', # Concat [1]
    '21': '25', # C2f [1024]
    '22': '26'  # Detect [nc]
}
# base_model = YOLO('yolov8l.yaml')
pret_state_dict = YOLO(base_ckpt_path).float().state_dict()
my_state_dict = {}
for k, v in layers_mapping.items():
    for kk in pret_state_dict:
        if f'model.{k}.' in kk:
            new_key = kk.replace(f'model.{k}.', f'model.{v}.')
            my_state_dict[new_key] = pret_state_dict[kk]
# for adapter weights
for k in model.state_dict():
    if k not in my_state_dict:
        print(k)
        my_state_dict[k] = torch.nn.init.zeros_(model.state_dict()[k])

model.load_state_dict(my_state_dict, strict=True)

```
but it seems that the weights are not loaded properly since at the beginning of train the accuracy is not good at all
