### ISSUE TITLE
Modification of yolov8 

### ISSUE THREAD

**Issue by Abdullah21533** [ultralytics/ultralytics#16740]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Hyperparameter Tuning

### Bug

I am making changes to the YOLOv8 model's YAML file, but I am not seeing any improvements reflected. What steps should I take to ensure that the improvements are correctly applied and visible?

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.4.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
Setup complete ✅ (12 CPUs, 53.0 GB RAM, 36.4/112.6 GB disk)

### Minimal Reproducible Example

```
# Custom YOLOv8 with DSConv, DPAG, and FEM

# Parameters
nc: 80 # number of classes
scales:
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

# Custom backbone with DSConv and FEM
backbone:
  # [from, repeats, module, args]
  - [-1, 1, DSConv, [64, 3, 2]] # 0-P1/2 (Replaced Conv with DSConv)
  - [-1, 1, DSConv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, FEM, [128, True]]    # Feature Enhancement Module (FEM)
  - [-1, 1, DSConv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]    # Standard C2f block
  - [-1, 1, DSConv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, DSConv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# Custom head with DPAG
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, DPAG, [512]]      # DPAG replaces C2f block for better attention

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, DPAG, [256]]      # DPAG for attention (P3/8-small)

  - [-1, 1, DSConv, [256, 3, 2]]  # Replace Conv with DSConv
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, DPAG, [512]]      # DPAG for better attention (P4/16-medium)

  - [-1, 1, DSConv, [512, 3, 2]]  # Replace Conv with DSConv
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, DPAG, [1024]]     # DPAG for better attention (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]] # Detect(P3, P4, P5)
```

### Additional

I am making changes to the YOLOv8 model's YAML file, but I am not seeing any improvements reflected. What steps should I take to ensure that the improvements are correctly applied and visible?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
