### ISSUE TITLE
How to improve training results onYOLOV11 or YOLOV8 n?

### ISSUE THREAD

**Issue by shaoguanglin** [ultralytics/ultralytics#16895]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why is it that for the same dataset, with large and small targets at 1280x320, in order for the large target to be completely surrounded by the detection box, I set reg_max=20, and map50 is around 0.995 on yolov10n, but only around 0.66 on yolov11n and yolov8n, with the same training parameters? What should I do to improve the training results on yolov11n and v8n?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @shaoguanglin, thank you for your interest in Ultralytics 🚀! We've received your question regarding training results on YOLOv11n and YOLOv8n. 

For custom training ❓, we recommend providing detailed information such as dataset examples and training logs to better understand the issue. Also, verify you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

If this relates to a 🐛 bug, kindly provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so our team can investigate effectively.

This is an automated response, but rest assured that an Ultralytics engineer will assist you soon.

For further community engagement, feel free to join us on [Discord](https://ultralytics.com/discord) 🎧, [Discourse](https://community.ultralytics.com), or our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Please ensure you're running the latest version of `ultralytics` with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment:

```bash
pip install -U ultralytics
```

## Environments

YOLO works in the following environments with necessary dependencies:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"/></a>
- **Google Cloud**: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"/></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"/></a>

Keep an eye on the CI badge. If it's green, all our [CI tests](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) are passing, ensuring stable operations of YOLO across platforms. 

Looking forward to your response! 😊

**Comment by Y-T-G** [comment]
You can try testing this:

https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-2367471426

**Comment by shaoguanglin** [comment]
Thanks for your reply, I will try it and see the effect

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by shaoguanglin** [comment]
> You can try testing this:
> 
> [#11634 (comment)](https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-23674714

> You can try testing this:
> 
> [#11634 (comment)](https://github.com/ultralytics/ultralytics/issues/11634#issuecomment-2367471426)

I have trained it with yolov8-p2.yaml, and now both large and small objects can be detected with good scores, but the detection box of the largest object is still not completely surrounded by the detection box. Should I set reg_max to be greater than 16, such as 20?
![1720427781780_input](https://github.com/user-attachments/assets/5227c77a-dffc-4553-92b6-fc85f071a160)

**Comment by Y-T-G** [comment]
@shaoguanglin You should add `imgsz:` in the model yaml and the branch will automatically calculate the best `reg_max` for that `imgsz`. Also add a P6 layer to your yaml.

**Comment by shaoguanglin** [comment]
> @shaoguanglin You should add `imgsz:` in the model yaml and the branch will automatically calculate the best `reg_max` for that `imgsz`. Also add a P6 layer to your yaml
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 1, Conv, [1024, 3, 2]] # 10-P6/64, add P6 
  - [-1, 3, C2f, [1024, True]] # 11
# YOLOv8.0-p2 head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 2], 1, Concat, [1]] # cat backbone P2
  - [-1, 3, C2f, [128]] # 18 (P2/4-xsmall)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]] # cat head P3
  - [-1, 3, C2f, [256]] # 21 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 24 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 27 (P5/32-large)

 # Add P6 detection head
  - [-1, 1, Conv, [1024, 3, 2]] # P6 downsample
  - [[-1, 10], 1, Concat, [1]]  # cat head P6 with backbone
  - [-1, 3, C2f, [1024]] # 30 (P6/64-xlarge)

  - [[18, 21, 24, 27, 30], 1, Detect, [nc]] # Detect(P2, P3, P4, P5, P6)
  

  Sorry, I'm a newbie. I coded like this and it gives an error when I run it. How should I correct it? 

 err：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.

**Comment by Y-T-G** [comment]
Change to your `ingsz`

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P2-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]
  
imgsz: 640

# YOLOv8.0 backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [768, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 9-P6/64
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 11

# YOLOv8.0-p2 head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 2], 1, Concat, [1]] # cat backbone P2
  - [-1, 3, C2f, [128]] # 18 (P2/4-xsmall)

  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]] # cat head P3
  - [-1, 3, C2f, [256]] # 21 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 24 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2, [768, False]] # 27 (P5/32-large)

  - [-1, 1, Conv, [768, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P6
  - [-1, 3, C2, [1024, False]] # 30 (P6/64-xlarge)

  - [[18, 21, 24, 27, 30], 1, Detect, [nc]] # Detect(P2, P3, P4, P5)
```
