### ISSUE TITLE
how can i make my custom model get the high map as same as pretrained model yolov8n released?

### ISSUE THREAD

**Issue by cheng-lao** [ultralytics/ultralytics#17150]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi, thanks for your excellent work! 
 
I would like to ask a question about a modification in the yolov8 model. When I was training, I found that the accuracy of the network I trained using the [official yolov8 yaml file configuration file](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8.yaml) was always nearly 10 maps lower than the actual accuracy. And the same situation happened in my modified yolo yaml file ,that when i trained my slightly modified model on the coco datasets.  i got the map was nearly 10 maps lower than the actual accuracy. 

 However, the effect of using [yolov8 the pre-trained weights](https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt) for training is similar to the official test accuracy.**I would like to ask if this is because the official has made fine adjustments to the pre-trained weights?**

That is, because the official parameters are adjusted well during training, the effect of the pre-trained model is better than the effect obtained from training from scratch. **If this is the case, how can I make the modified model trained from scratch achieve the same good results as the official pre-trained model? Or even better?**

Here is  my modified model 👇：
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2        # 0
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4       # 1  
  - [-1, 3, C2f, [128, True]]                 # 2
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8       # 3
  - [-1, 6, C2f, [256, True]]                 # 4
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16      # 5
  - [-1, 6, C2f, [512, True]]                 # 6
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32     # 7
  - [-1, 3, C2f, [1024, True]]                # 8
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C3k2, [512, False]] # 12                      modify here 👈

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C3k2, [256, False]] # 15 (P3/8-small)                      modify here 👈

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C3k2, [512, False]] # 18 (P4/16-medium)                      modify here 👈

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C3k2, [1024, True]] # 21 (P5/32-large)                      modify here 👈

  - [[15, 18, 21], 1, Detect, [nc]] # Detect(P3, P4, P5)

```
