### ISSUE TITLE
Multitask Yolo Model for Classification and Detection

### ISSUE THREAD

**Issue by manu13008** [ultralytics/ultralytics#17263]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey guys,

I have been exploring previous issues to find a solution at a question some people already had but was answered not clearly.

I would like to use a SINGLE model to perform both classification and object detection tasks using Yolo11.

Is it possible ? If so, what should I do ?

I have a dataset where I detect some objects and depending the position of my subject, classify each frame into a class.
Both separate models (classification and detection) work good, that's why I would like to know if it's possible to combine them into a unique one.

Thanks :)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @manu13008, thank you for reaching out and showing your interest in Ultralytics 🚀! We recommend you check out the [Ultralytics Docs](https://docs.ultralytics.com) for comprehensive guides. You may find intriguing details on [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage that could potentially answer your question.

If your query is related to a bug 🐛, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us assist you efficiently.

For training-related ❓ questions, kindly include detailed information, such as dataset samples and training logs, and make sure you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Meanwhile, feel free to join our vibrant Ultralytics community! Whether it’s real-time chat on [Discord](https://ultralytics.com/discord) 🎧, more elaborate discussions on [Discourse](https://community.ultralytics.com), or engaging threads on our [Subreddit](https://reddit.com/r/ultralytics), there's plenty of support available.

## Upgrade

To ensure you are using the latest features and fixes, upgrade to the newest `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

You can run YOLO in various updated environments with all necessary dependencies:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, it indicates that all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. These tests ensure the correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu daily and on every commit.

This is an automated response to guide you in the right direction, but rest assured, an Ultralytics engineer will be in touch soon to provide further assistance 🙂.

**Comment by Y-T-G** [comment]
It would require adding a classification head alongside the detection head and then training them. A lot of customizations.

**Comment by manu13008** [comment]
What file should I modify or what code should I implement to add this classification head ?

**Comment by glenn-jocher** [comment]
@manu13008 to add a classification head, you'll need to modify the model architecture in the YOLO codebase, specifically in the model definition files. Look into the `models` directory for guidance on where to integrate the classification layers.

**Comment by manu13008** [comment]
@glenn-jocher Could you please elaborate on how to modify the model architecture and on what my yaml file should look like ? Thks

**Comment by glenn-jocher** [comment]
To modify the model architecture, you'll need to adjust the model definition files in the `models` directory to include a classification head. For the YAML file, ensure it specifies both detection and classification tasks, detailing the dataset paths and class names for each.

**Comment by manu13008** [comment]
@glenn-jocher thanks for the feedback!



> To modify the model architecture, you'll need to adjust the model definition files in the `models` directory to include a classification head. 

The object detection head is : 

```
# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, C3k2, [512, False]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, C3k2, [256, False]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 2, C3k2, [512, False]] # 19 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 2, C3k2, [1024, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [nc]] # Detect(P3, P4, P5)
```
And the classification head is : 


```
# YOLO11n head
head:
  - [-1, 1, Classify, [nc]] # Classify
```
 Should I then just add the  - [-1, 1, Classify, [nc]] # Classify line into the head section from the object detection cfg file ?

Something like : 

```
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, C3k2, [512, False]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, C3k2, [256, False]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 2, C3k2, [512, False]] # 19 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 2, C3k2, [1024, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [nc]] # Detect(P3, P4, P5)
  - [-1, 1, Classify, [nc]] # Classify
```


For the YAML file, ensure it specifies both detection and classification tasks, detailing the dataset paths and class names for each.

Let's imagine I have 5 objects and 3 classes.

```
test: ./test/images
train: ./train/images
val: ./valid/images

nc: 5

names:
- object1
- object2
- object3
- object4
- object5
```

And the architecture of my dataset as follow : 

train
_____Class1_Folder
_____Class2_Folder
_____Class3_Folder
val
_____Class1_Folder
_____Class2_Folder
_____Class3_Folder
test
_____Class1_Folder
_____Class2_Folder
_____Class3_Folder



Is there anything important I'm missing ? Thanks !

**Comment by glenn-jocher** [comment]
@manu13008 yes, you're on the right track by adding the classification head to the model architecture. Ensure your YAML file includes both `nc` for detection classes and a separate section for classification classes. You might need to adjust the dataset paths to reflect both tasks accurately. Additionally, verify that your training script can handle both outputs simultaneously.

**Comment by manu13008** [comment]
@glenn-jocher 
Here is my new cfg file (yolo11-multitask.yaml) :

```
# Parameters
nc: 80 # number of classes

scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024] # summary: 319 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  s: [0.50, 0.50, 1024] # summary: 319 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 409 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  l: [1.00, 1.00, 512] # summary: 631 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  x: [1.00, 1.50, 512] # summary: 631 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 2, C2PSA, [1024]] # 10

# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, C3k2, [512, False]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, C3k2, [256, False]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 2, C3k2, [512, False]] # 19 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 2, C3k2, [1024, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [nc]] # Detect(P3, P4, P5)
  - [-1, 1, Classify, [5]] # Classify

```
I load it using `model = YOLO("yolo11-multi.yaml", task="detect")` command
 I couldn't specify a nc_cls into this file as it raised an error while loading my model. So I directly set up my exact number of class inside the classification head (ie. 5).

Then I configured my dataset as follow : 
__valid
_______Class1
_______Class2
_______Class3
_______Class4
_______Class5

__train
_______Class1
_______Class2
_______Class3
_______Class4
_______Class5
__test
_______Class1
_______Class2
_______Class3
_______Class4
_______Class5
__data.yaml

Each class folder contains my images as well as labels for detection. I followed this stucture because Yolo11 classification model requires this kind of dataset organization for predicting class belonging. 

I constructed my data.yaml file as follow : 


```
path: C:\Users\emman\Documents\Yolo11_Original\datasets\ClassifDetect_Dataset # dataset root dir
# Data path
test: ./test
train: ./train
val: ./valid

# Classes for detection
nc: 2  


#Classes names
names:
  - object1
  - object2
```

Normally, following the dataset structure, I wouldn't need to specify details about classification task, or am I missing something ?
(When I ran classification model only, I didn't need a data.yaml file)

Then, I started training process using 
`results = model.train(data=os.path.join(path_dataset, 'data.yaml'), epochs=10, imgsz=640, device=0, project='Run_ClassifDetect', name='ImageSize_640_Epochs_10')`

But I raised this new error just before the beginning of the first epoch.

```
AttributeError                            Traceback (most recent call last)
Cell In[28], line 5
      3 path_dataset = r'C:\Users\emman\Documents\Yolov8_Original\datasets\ClassifDetect_Dataset'
      4 # Train the model
----> 5 results = model.train(data=os.path.join(path_dataset, 'data.yaml'), epochs=10, imgsz=640, device=0, project='Run_ClassifDetect', name='ImageSize_640_Epochs_10')

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\engine\model.py:803, in Model.train(self, trainer, **kwargs)
    800     self.model = self.trainer.model
    802 self.trainer.hub_session = self.session  # attach optional HUB session
--> 803 self.trainer.train()
    804 # Update model and cfg after training
    805 if RANK in {-1, 0}:

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\engine\trainer.py:207, in BaseTrainer.train(self)
    204         ddp_cleanup(self, str(file))
    206 else:
--> 207     self._do_train(world_size)

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\engine\trainer.py:385, in BaseTrainer._do_train(self, world_size)
    383 with autocast(self.amp):
    384     batch = self.preprocess_batch(batch)
--> 385     self.loss, self.loss_items = self.model(batch)
    386     if RANK != -1:
    387         self.loss *= world_size

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\torch\nn\modules\module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\torch\nn\modules\module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\nn\tasks.py:110, in BaseModel.forward(self, x, *args, **kwargs)
     96 """
     97 Perform forward pass of the model for either training or inference.
     98 
   (...)
    107     (torch.Tensor): Loss if x is a dict (training), or network predictions (inference).
    108 """
    109 if isinstance(x, dict):  # for cases of training and validating while training.
--> 110     return self.loss(x, *args, **kwargs)
    111 return self.predict(x, *args, **kwargs)

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\nn\tasks.py:289, in BaseModel.loss(self, batch, preds)
    281 """
    282 Compute loss.
    283 
   (...)
    286     preds (torch.Tensor | List[torch.Tensor]): Predictions.
    287 """
    288 if getattr(self, "criterion", None) is None:
--> 289     self.criterion = self.init_criterion()
    291 preds = self.forward(batch["img"]) if preds is None else preds
    292 return self.criterion(preds, batch)

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\nn\tasks.py:388, in DetectionModel.init_criterion(self)
    386 def init_criterion(self):
    387     """Initialize the loss criterion for the DetectionModel."""
--> 388     return E2EDetectLoss(self) if getattr(self, "end2end", False) else v8DetectionLoss(self)

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\ultralytics\utils\loss.py:168, in v8DetectionLoss.__init__(self, model, tal_topk)
    166 self.bce = nn.BCEWithLogitsLoss(reduction="none")
    167 self.hyp = h
--> 168 self.stride = m.stride  # model strides
    169 self.nc = m.nc  # number of classes
    170 self.no = m.nc + m.reg_max * 4

File ~\anaconda3\envs\pytorch_gpu_env\Lib\site-packages\torch\nn\modules\module.py:1729, in Module.__getattr__(self, name)
   1727     if name in modules:
   1728         return modules[name]
-> 1729 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'Classify' object has no attribute 'stride'
```
