### ISSUE TITLE
Yolov8 training on KITTI Dataset

### ISSUE THREAD

**Issue by Prashambhuta** [ultralytics/ultralytics#1765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I am attempting to train KITTI Lidar data for Object detection using YOLOv8 architecture. I am struggling with creating the forward pass for training. I am using the following repositories as a reference. I would appreciate it if someone would help me construct the training model.

* https://github.com/ghimiredhikura/Complex-YOLOv3
* https://github.com/AI-liu/Complex-YOLO

There is an issue, which requests an approach to attempt this, but it is also open.

* https://github.com/ultralytics/ultralytics/issues/1058

### Use case

The Yolov8 will improve the performance of the KITTI dataset Object detection and would be good to compare the results with existing YOLO implementations.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Prashambhuta It appears that you're trying to adapt the YOLOv8 architecture for object detection using KITTI Lidar data. While I can't provide a complete solution for this task, I can guide you through the general steps that you might need to follow in order to achieve your goal.

Data preparation: The first step is to convert the KITTI Lidar dataset into a suitable format that can be used with YOLOv8. This might involve converting the point cloud data into a format that can be used as input to the YOLOv8 network.

Modify YOLOv8 architecture: Since Lidar data is inherently different from image data, you may need to modify the YOLOv8 architecture to accommodate the differences. This could involve modifying the input layer to accept Lidar data, and potentially adjusting other layers or adding new ones to better process the data.

Adapt the loss function: The loss function may also need to be adapted to suit the specific characteristics of Lidar data. You can refer to the loss functions used in the Complex-YOLOv3 and Complex-YOLO repositories you mentioned for inspiration.

Training: Once you have made the necessary modifications to the YOLOv8 architecture and loss function, you can proceed with training the model using the prepared KITTI Lidar dataset.

Evaluation: Finally, you'll need to evaluate the performance of your YOLOv8 model on the KITTI dataset. This will involve running inference on the test dataset and comparing the results to the ground truth labels, as well as comparing the results to other YOLO implementations.

Please note that adapting the YOLOv8 architecture for Lidar data is a complex task and may require significant experimentation and fine-tuning. The repositories and issue you mentioned are a good starting point, but you may also want to consult relevant research papers and other resources to gain a deeper understanding of the problem and potential solutions.

Good luck with your project!

**Comment by Prashambhuta** [comment]
Thank you for your input. I created a YOLOv8 architecture and using the same DataLoader from ComplexYOLO, I plan to train the model. I am trying to figure out the Forward step function for the v8 model.

**Comment by Prashambhuta** [comment]
@glenn-jocher Thank you very much for your input. It helped me immensely. I was able to create a custom architecture with yolov8n architecture at the core. I am now trying to fine-tune the forward calls as per the architecture. ]

If my understanding on Concat layer is correct, then should I take the outputs from layers at different depths and concat them together before passing them to the next layer in the forward call? Thank you.

**Comment by glenn-jocher** [comment]
@Prashambhuta, glad to hear that my previous response was helpful for you! Regarding your question about the Concat layer, it is correct that the layer is used to concatenate the outputs from multiple layers at different depths. This allows the network to combine information from different scales to improve the accuracy of object detection. 

In YOLOv8, the Concat layer is commonly used to concatenate the feature maps from the shortcut connections with the feature maps from the main branch of the network. The resulting concatenated feature maps are then passed through additional convolutional and activation layers to generate the final predictions.

It's important to note that the order in which the feature maps are concatenated can affect the performance of the network. In general, the features from the shallower layers are concatenated first, followed by the deeper layers. 

I hope this helps clarify the role of the Concat layer in YOLOv8 and how it can be used to improve the accuracy of object detection. If you have any further questions, please don't hesitate to ask!

**Comment by Prashambhuta** [comment]
@glenn-jocher There are two approaches I am trying side by side. 

1. To load the model straight from Ultralytics and use it as it is to train the model. Here I am running issues with dataloader, as bounding boxes and classes are custom for KITTI. I am trying to replicate this step from Complex-yolo4 repository.
2. To build a custom YOLOv8 architecture and use the first and last layer from ComplexYOLO. Here the forward function needs to be customized as well, as to concatenate as per the architecture.

For training custom object detection using yolov8 what should be the targets input to model? Just the class labels or labels along with bounding box?

**Comment by Prashambhuta** [comment]
@glenn-jocher Hi, how to calculate the loss using a custom call? I use an instance of DetectionModel(), and want to know how to pass the Loss function, as I tried the following code:

```python
from ultralytics.yolo.engine.model import DetectionModel
from ultralytics.yolo.v8.detect.train import Loss

model = DetectionModel(nc=3)
loss_fn = Loss(de_parallel(model))
total_loss = loss_fn(model(imgs), targets)
```

But I get the following error:
```py
AttributeError: 'DetectionModel' object has no attribute 'args'
```

I understand that `args` are hyperparameters for loss, but I don't know how to get them!

**Comment by glenn-jocher** [comment]
@Prashambhuta hi there! Your error message suggests that the `args` attribute may not be defined for the `DetectionModel` class in YOLOv8. Instead of using `args`, you can define the hyperparameters for the loss function directly when creating an instance of the `Loss` class. 

Here's an example of how you can modify your code to pass the hyperparameters for the loss function:
```python
from ultralytics.yolo.engine.model import DetectionModel
from ultralytics.yolo.v8.detect.train import Loss

model = DetectionModel(nc=3)
hyperparameters = {
    "obj": 1.0,
    "cls": 1.0,
    "ltrb": 1.0,
    "iou_t": 0.2,
    "cls_t": 0.4,
}
loss_fn = Loss(model, hyperparameters=hyperparameters)
total_loss = loss_fn(model(imgs), targets)
```

In this example code, we defined a dictionary `hyperparameters` that includes the values for the hyperparameters used in the loss function. These hyperparameters include `obj` (the weight for the objectness loss), `cls` (the weight for the classification loss), `ltrb` (the weight for the regression loss), `iou_t` (the IoU threshold for determining positive samples), and `cls_t` (the threshold for determining positive classification samples).

Then, we pass the `hyperparameters` dictionary to the `Loss` class when creating a new instance of the class. This allows the loss function to use the specified hyperparameters when calculating the loss.

I hope this explanation is helpful! Let me know if you have any further questions.

**Comment by Prashambhuta** [comment]
Thank you, I will give it a try. And about the DetectionTrainer, for training what is the key difference between training by creating a Trainer or training by creating a Model.

**Comment by Prashambhuta** [comment]
Loss class has no keyword argument `hyperparameters`

**Comment by Prashambhuta** [comment]
Hi, I could load the model, but there is an error with the forward call in the Concat step of the architecture. Its about the arguments received for `torch.cat()` I build the DetectionModel() using the following .yaml config. Maybe you can explain what are `depth-multiple` and `width-multiple`, also if there is anything that needs to be changed?

```yaml

# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect  # YOLO task, i.e. detect, segment, classify, pose
mode: train  # YOLO mode, i.e. train, val, predict, export, track, benchmark
nc: 3  # number of classes
depth_multiple: 0.33
width_multiple: 0.33
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)

# Train settings -------------------------------------------------------------------------------------------------------
model: config/cfg/yolov8.yaml # path to model file, i.e. yolov8n.pt, yolov8n.yaml
data:  'kitti.yaml'# path to data file, i.e. coco128.yaml
epochs: 100  # number of epochs to train for
patience: 50  # epochs to wait for no observable improvement for early stopping of training
batch: 16  # number of images per batch (-1 for AutoBatch)
imgsz: 608  # size of input images as integer or w,h
save: True  # save train checkpoints and predict results
save_period: -1 # Save checkpoint every x epochs (disabled if < 1)
cache: False  # True/ram, disk or False. Use cache for data loading
device:  # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8  # number of worker threads for data loading (per RANK if DDP)
project:  # project name
name:  # experiment name, results saved to 'project/name' directory
exist_ok: False  # whether to overwrite existing experiment
pretrained: False  # whether to use a pretrained model
optimizer: Adam  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
verbose: True  # whether to print verbose output
seed: 0  # random seed for reproducibility
deterministic: True  # whether to enable deterministic mode
single_cls: False  # train multi-class data as single-class
rect: False  # rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False  # use cosine learning rate scheduler
close_mosaic: 0  # (int) disable mosaic augmentation for final epochs
resume: False  # resume training from last checkpoint
amp: True  # Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
# Segmentation
overlap_mask: True  # masks should overlap during training (segment train only)
mask_ratio: 4  # mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # validate/test during training
split: val  # dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # save results to JSON file
save_hybrid: False  # save hybrid version of labels (labels + additional predictions)
conf:  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image
half: False  # use half precision (FP16)
dnn: False  # use OpenCV DNN for ONNX inference
plots: True  # save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # source directory for images or videos
show: False  # show results if possible
save_txt: False  # save results as .txt file
save_conf: False  # save results with confidence scores
save_crop: False  # save cropped images with results
show_labels: True  # show object labels in plots
show_conf: True  # show object confidence scores in plots
vid_stride: 1  # video frame-rate stride
line_width:   # line width of the bounding boxes
visualize: False  # visualize model features
augment: False  # apply image augmentation to prediction sources
agnostic_nms: False  # class-agnostic NMS
classes:  # filter results by class, i.e. class=0, or class=[0,2,3]
retina_masks: False  # use high-resolution segmentation masks
boxes: True  # Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # format to export to
keras: False  # use Keras
optimize: False  # TorchScript: optimize for mobile
int8: False  # CoreML/TF INT8 quantization
dynamic: False  # ONNX/TF/TensorRT: dynamic axes
simplify: False  # ONNX: simplify model
opset:  # ONNX: opset version (optional)
workspace: 4  # TensorRT: workspace size (GB)
nms: False  # CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 7.5  # box loss gain
cls: 0.5  # cls loss gain (scale with pixels)
dfl: 1.5  # dfl loss gain
pose: 12.0  # pose loss gain
kobj: 1.0  # keypoint obj loss gain
label_smoothing: 0.0  # label smoothing (fraction)
nbs: 64  # nominal batch size
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # use legacy YOLOv5 dataloader

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']
```
