### ISSUE TITLE
Are these metrics normal? Visdrone YOLO11n 

### ISSUE THREAD

**Issue by mldl4** [ultralytics/ultralytics#18031]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! First of all, thank you for the project and for the activity in the repository. It is appreciated.
Right now, I am working with YOLO11n and Visdrone dataset and I'm having problems during training.
My model doesn't learn as I expected. Nevertheless, not good results.
Several tries with different hyperparameters have been done: 
- Default training 
- https://github.com/ultralytics/ultralytics/issues/17536
- https://github.com/ultralytics/ultralytics/issues/14101 

There is something I am doing wrong? or Should I perform some data augmentation or balancing process to obtain better results?

Thank you in advance!!!

PD: Next, I show my setup, libs and code.

# Setup

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     On  | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P8              26W / 320W |      9MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
|=========================================+======================+======================|

```

```
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        46 bits physical, 48 bits virtual
CPU(s):                               24
On-line CPU(s) list:                  0-23
Thread(s) per core:                   1
Core(s) per socket:                   16
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                151
Model name:                           12th Gen Intel(R) Core(TM) i9-12900K
```

```
20.04.1-Ubuntu
```

# Code

```
from datetime import datetime
from ultralytics import YOLO
import torch
import yaml
import json
import gc

torch.cuda.empty_cache()
gc.collect()


yaml_params = {}
with open('parameters.yaml', 'r') as yaml_file:
    yaml_params = yaml.safe_load(yaml_file)

model = YOLO("yolo11n.yaml").load("yolo11n.pt")
model.train(**params)

params_val = {
    'save_json': True,
    'project': 'eval' + params['name']
}
metrics = model.val(**params_val) 

```

# Hyperparameters

```
custom:
  data: visdrone.yaml
  patience: 15
  epochs: 300
  imgsz: 640 # 928
  batch: 8
  save: True
  device: 0
  plots: True
  seed: 42
  optimizer: AdamW
  dropout: 0.1
  lr0: 0.0007856857999453613
  augment: True
  multi_scale: True
  close_mosaic: 10
  workers: 8
  save_period: 1
  verbose: True
  # StepLR: True
  # gamma: 0.1
  # step_size: 50
  weight_decay: 0.000130
  pretrained: True
  val: True
  mixup: 0.1948
  momentum: 0.92551
  # cutmix: 0.3155
```

# Results
![image](https://github.com/user-attachments/assets/841e5217-13cf-47ba-a53e-9024b1da56c8)

## Training

![image](https://github.com/user-attachments/assets/8864f31b-604a-44b4-8170-c4a4fa581787)

## Eval
![image](https://github.com/user-attachments/assets/f34ef691-2a52-4b26-9ebb-0a53db278989)

```
mAP50-95 -> 0.1858984065721675
mAP50 -> 0.31818722095404556
mAP75 -> 0.18746636795979413

```
