### ISSUE TITLE
Not all parameters in YOLO-World pretrained weights can be loaded

### ISSUE THREAD

**Issue by chongkuiqi** [ultralytics/ultralytics#18688]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

When i init a YOLOv8s-World-v2 model from a .yaml configuration file and load pretrained weights, it seems that three parameters can not be loaded.  The code and outputs are as follows:
```python
from ultralytics import YOLOWorld
model_path = './yolov8s-worldv2.pt'
model_cfg = "./yolov8s-worldv2.yaml"
model = YOLOWorld(model_cfg).load(model_path)

# outputs
Transferred 409/412 items from pretrained weights
```

The yolov8s-worldv2.yaml configuration file is copied from `ultralytics/ultralytics/cfg/models/v8/yolov8-worldv2.yaml` without any modifications except for the file name.

And i find a solution, in `ultralytics/ultralytics/nn/modules/block.py`, modify the `class BNContrastiveHead(nn.Module)` as follows:
```python
# self.bias = nn.Parameter(torch.tensor([-10.0]))
self.bias = nn.Parameter(-10.0 * torch.ones([]))
```
Rerun the above code and output as:
```python
Transferred 412/412 items from pretrained weights
```

### Environment

```
Ultralytics 8.3.59 🚀 Python-3.10.14 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24259MiB)
Setup complete ✅ (32 CPUs, 62.8 GB RAM, 686.0/915.3 GB disk)

OS                  Linux-5.15.0-130-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.14
Install             git
RAM                 62.79 GB
Disk                686.0/915.3 GB
CPU                 Hygon C86 3285  8-core Processor
CPU count           32
GPU                 NVIDIA GeForce RTX 3090, 24259MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.10.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.2+cu121>=1.8.0
torch               ✅ 2.2.2+cu121!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.17.2+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.13>=2.0.0
```

### Minimal Reproducible Example

```python
from ultralytics import YOLOWorld
model_path = './yolov8s-worldv2.pt'
model_cfg = "./yolov8s-worldv2.yaml"
model = YOLOWorld(model_cfg).load(model_path)

# outputs
Transferred 409/412 items from pretrained weights
```
The yolov8s-worldv2.yaml configuration file :
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-World-v2 object detection model with P3-P5 outputs. For details see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2fAttn, [512, 256, 8]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2fAttn, [256, 128, 4]] # 15 (P3/8-small)

  - [15, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2fAttn, [512, 256, 8]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2fAttn, [1024, 512, 16]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, WorldDetect, [nc, 512, True]] # Detect(P3, P4, P5)

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
