### ISSUE TITLE
Which hyperparameters are suitable for me?

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#18710]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I've already done finetuning and just trained YOLOv11 from scratch. But I have the following problem. Your pretrained model works well with the `car` class in some scenes that I need, but poorly in others that I also need. When I do finetuning of your pretrained model, for some reason, where your model coped well, the quality drops, and where it did not recognize anything, everything is fine. For some reason, somehow finetuning spoils what is already good and improves what was bad. I want to adapt YOLOv11 to work at night.

Can you tell me what hyperparameters I need to set so that everything is fine and the way I need it? YOLOv4 just does what it needs to do for some reason. And I want a newer version of YOLO. Maybe I need to freeze something or turn on augmentation?

Here is my training startup configuration:
```
task: detect
mode: train
model: yolov11m.yaml
data: ./yolov11_custom.yaml
epochs: 500
time: null
patience: 100
batch: 32
imgsz: 640
save: true
save_period: -1
val_period: 1
cache: false
device: 0
workers: 8
project: /YOLOv11_m_night_640
name: yolov11_custom_night
exist_ok: false
pretrained: true
optimizer: auto
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: /YOLOv1_m_night_640
```

my `yolov11_custom.yaml`:
```
path: ./data
train: ./data/train.txt
val: /data/val.txt

# Classes
names:
  0: trailer
  1: train
  2: trafficlight
  3: sign
  4: bus
  5: truck
  6: person
  7: bicycle
  8: motorcycle
  9: car
  10: streetlight
```

@glenn-jocher @Y-T-G and others. Please help me.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Egorundel, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com) for helpful guidance, especially if you're experimenting with custom training or hyperparameter tuning. The [Model Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) section offers in-depth advice for achieving optimal results in diverse scenarios.

If this is a ❓ Question about custom training or tuning, your comprehensive description is incredibly helpful 🙌. Based on your provided training configuration, you may want to explore the effects of hyperparameters like `freeze`, `auto_augment`, and specific augmentation strategies like `mosaic` or `mixup`. For issues with pretrained weights modifying existing performance, freezing specific layers during training could help retain prior capabilities while improving others.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) (MRE), including a sample dataset or images (if possible) and logs. This will help us debug your issue effectively.

To ensure you're using the latest features and fixes, please upgrade to the latest version of `ultralytics`:

```bash
pip install -U ultralytics
```

## Training Tips

For adapting YOLOv11 to nighttime conditions, here are a few community-recommended steps to try:
1. Adjust `auto_augment` or `erasing` and see their impact during fine-tuning.
2. Experiment with `freeze`, which can be used to retain existing feature representations from the pretrained model:
   ```yaml
   freeze: [0]  # Number of layers (e.g., backbone layers) to freeze during training.
   ```
3. Carefully tweak augmentation parameters such as `hsv_h`, `hsv_s`, `hsv_v`, and `brightness` to simulate night lighting scenarios in the training pipeline.

Let us know if you’ve already tried any of these approaches and their results!

## Community Resources

Feel free to join the fantastic Ultralytics community for advice and peer support:
- [Discord](https://discord.com/invite/ultralytics) 🎧 for real-time discussions
- [Discourse](https://community.ultralytics.com) for detailed troubleshooting
- [Subreddit](https://reddit.com/r/Ultralytics) to share or discover innovative solutions

## Quick Environment Setup

YOLO can be run in these verified environments for seamless experimentation:
- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing, ensuring robust operation of YOLO's [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across OS environments.

This is an automated response to help address your issue quickly. One of our Ultralytics engineers will also follow up with you soon to assist further! 🚀

**Comment by Skillnoob** [comment]
Use the default hyperparameters, they're fine for most people.
The model performs badly since it forgets what it learned previously and you changed the classes.
You should add your new classes to the coco dataset and then limit the classes to the ones you want with the `classes` argument.
Example:
```python
from ultralytics import YOLO

model = YOLO('yolo11n.pt')

model.train('coco.yaml', classes=[2]) # This would train a model with only the 'car' class
```

**Comment by Y-T-G** [comment]
Performance degradation is expected because your model starts overfitting to your dataset.

You should also include all the 80 pretrained classes in your yaml

And use this guide to lower learning rate and disable warmup.

https://www.reddit.com/r/Ultralytics/comments/1eolwl8/the_correct_way_to_train_from_a_previously/

**Comment by Egorundel** [comment]
@Skillnoob @Y-T-G And I don't need all the coco classes, I only need my 11 classes. There is no need to detect any more.


@Skillnoob What should I do then? Just add the classes I need to the coco list and specify them in classes as an array?

**Comment by Y-T-G** [comment]
> And I don't need all the coco classes, I only need my 11 classes. There is no need to detect any more.

You still have to keep them in the yaml, otherwise the weights of the head will be reset.

**Comment by Skillnoob** [comment]
> [@Skillnoob](https://github.com/Skillnoob) What should I do then? Just add the classes I need to the coco list and specify them in classes as an array?

Yes. Your data as well of course, but as the new class ids, starting from the coco 80 classes.

**Comment by Egorundel** [comment]
@Y-T-G @Skillnoob 

And how many classes will I need to specify in the cfg in line `nc: 80 # number of classes`? 
As many as I need (11) or total (coco 80 classes + my new ones)?

```
# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Ultralytics YOLO11 object detection model with P3/8 - P5/32 outputs
# Model docs: https://docs.ultralytics.com/models/yolo11
# Task docs: https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024] # summary: 319 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  s: [0.50, 0.50, 1024] # summary: 319 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 409 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  l: [1.00, 1.00, 512] # summary: 631 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  x: [1.00, 1.50, 512] # summary: 631 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 2, C2PSA, [1024]] # 10

# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, C3k2, [512, False]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, C3k2, [256, False]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 2, C3k2, [512, False]] # 19 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 2, C3k2, [1024, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [nc]] # Detect(P3, P4, P5)
```
