### ISSUE TITLE
Yolo incompatible with Jetpack 6.2(Jetson Orin Nano Super)

### ISSUE THREAD

**Issue by lida2003** [ultralytics/ultralytics#18829]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I just installed Jepack 6.2, and sudo `sudo pip3 install ultralytics`.

It seems it uses libcudnn.so.8 not cuDNN: 9.3.0.75. 

The issue might be pytorch, as I didn't see any correct version for L4T36.4.3, which is for Super performance: https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048

Any ideas?

See below link for details:

https://forums.developer.nvidia.com/t/yolo-incompatible-with-jetpack-6-2-jetson-orin-nano-super/321078

### Environment

```
Software part of jetson-stats 4.3.1 - (c) 2024, Raffaello Bonghi
Model: NVIDIA Jetson Orin Nano Developer Kit - Jetpack 6.2 [L4T 36.4.3]
NV Power Mode[0]: 15W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3767-0005
 - Module: NVIDIA Jetson Orin Nano (Developer kit)
Platform:
 - Distribution: Ubuntu 22.04 Jammy Jellyfish
 - Release: 5.15.148-tegra
jtop:
 - Version: 4.3.1
 - Service: Active
Libraries:
 - CUDA: 12.6.68
 - cuDNN: 9.3.0.75
 - TensorRT: 10.3.0.30
 - VPI: 3.2.4
 - Vulkan: 1.3.204
 - OpenCV: 4.11.0 - with CUDA: YES
```

### Minimal Reproducible Example

```
sudo pip3 install ultralytics
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
