### ISSUE TITLE
[BUG] Incorrect error message onnxruntime not found when exporting

### ISSUE THREAD

**Issue by Lunatik00** [ultralytics/ultralytics#19192]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

There is a bug regarding onnxruntime, I have it installed, but as `onnxruntime-gpu`, apparently this version is not detected by the `Ultralytics` library, I would consider this a minor bug since it doesn't prevent me from doing anything, but it should be corrected at some point.

```bash
uv run export.py yolo11n/weights/best.pt

Ultralytics 8.3.74 🚀 Python-3.11.10 torch-2.5.1+cu124 CPU (AMD Ryzen 7 5800X 8-Core Processor)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs

PyTorch: starting from 'yolo11n/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (5.2 MB)
requirements: Ultralytics requirement ['onnxruntime'] not found, attempting AutoUpdate...
/bin/sh: line 1: pip: command not found
Retry 1/2 failed: Command 'pip install --no-cache-dir "onnxruntime" ' returned non-zero exit status 127.
/bin/sh: line 1: pip: command not found
Retry 2/2 failed: Command 'pip install --no-cache-dir "onnxruntime" ' returned non-zero exit status 127.
requirements: ❌ Command 'pip install --no-cache-dir "onnxruntime" ' returned non-zero exit status 127.

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.48...
ONNX: export success ✅ 4.2s, saved as 'yolo11n/weights/best.onnx' (10.1 MB)

Export complete (5.4s)
Results saved to yolo11n/weights
Predict:         yolo predict task=detect model=yolo11n/weights/best.onnx imgsz=640  
Validate:        yolo val task=detect model=yolo11n/weights/best.onnx imgsz=640 data=medical-pills.yaml  
Visualize:       https://netron.app
```

```bash
uv run python -c "import onnxruntime; print(onnxruntime.__version__)"
1.20.1
```

The `export.py` file just in case:
```Python
from ultralytics import YOLO
import argparse

parser = argparse.ArgumentParser(description="Simple scrip to export model to onnx")
parser.add_argument("filename")
args = parser.parse_args()
# Load the YOLO11 model
model = YOLO(args.filename)

# Export the model to ONNX format
model.export(format="onnx", nms=True, imgsz=640)  # creates 'yolo11n.onnx'
```

and the `pyproject.toml`
```toml
[project]
name = "train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ultralytics>=8.3.68",
    "torch==2.5.1+cu124",
    "torchvision==0.20.1+cu124",
    "markupsafe==2.1.5",
    "onnx>=1.17.0",
    "onnxruntime-gpu>=1.20.1",
    "onnxslim>=0.1.47",
]
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu124"},
]
torchvision = [
  { index = "pytorch-cu124" },
]
```

### Environment

Ultralytics 8.3.74 🚀 Python-3.11.10 torch-2.5.1+cu124 CUDA:0 (NVIDIA GeForce RTX 3090, 24143MiB)
Setup complete ✅ (16 CPUs, 31.3 GB RAM, 762.0/881.5 GB disk)

OS                  Linux-6.12.10-zen1-x86_64-with-glibc2.40
Environment         Linux
Python              3.11.10
Install             git
RAM                 31.27 GB
Disk                762.0/881.5 GB
CPU                 AMD Ryzen 7 5800X 8-Core Processor
CPU count           16
GPU                 NVIDIA GeForce RTX 3090, 24143MiB
GPU count           1
CUDA                12.4

numpy               ✅ 2.1.1<=2.1.1,>=1.23.0
matplotlib          ✅ 3.10.0>=3.3.0
opencv-python       ✅ 4.11.0.86>=4.6.0
pillow              ✅ 11.1.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.15.1>=1.4.1
torch               ✅ 2.5.1+cu124>=1.8.0
torch               ✅ 2.5.1+cu124!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.20.1+cu124>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 6.1.1
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.14>=2.0.0

### Minimal Reproducible Example

`export.py`:
```Python
from ultralytics import YOLO
import argparse

parser = argparse.ArgumentParser(description="Simple scrip to export model to onnx")
parser.add_argument("filename")
args = parser.parse_args()
# Load the YOLO11 model
model = YOLO(args.filename)

# Export the model to ONNX format
model.export(format="onnx", nms=True, imgsz=640)  # creates 'yolo11n.onnx'
```
```bash
pip uninstall onnxruntime
pip install onnxruntime-gpu
python export.py <path to weights>
```

### Additional

The error must be related to the check in  https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L504C9-L504C27 , I was not able to find the error, i checked the output of `"onnxruntime" + ("-gpu" if torch.cuda.is_available() else "")` ant it was correct, same for what should happen in https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/checks.py#L393C34-L393C42 , at least if I enter the requirement directly it is still correct as well so I was unable to found the source of this error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
