### ISSUE TITLE
I am training with the RT-DETR model. Why is the accuracy close to 0?

### ISSUE THREAD

**Issue by dream-ahulu** [ultralytics/ultralytics#19530]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

# 不使用预训练模型训练
from ultralytics import RTDETR
model = RTDETR("rtdetr-resnet50.yaml")
results = model.train(data="ultralytics/cfg/datasets/rtdetr_my.yaml", epochs=100, imgsz=640, batch=4)

# 结果
      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     55/100      4.64G      2.194     0.0499     0.5192         35        640: 100%|██████████| 101/101 [00:08<00:00, 11.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:00<00:00, 28.55it/s]
                   all        101        647    3.3e-05    0.00155   1.67e-05      5e-06
      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     56/100      4.63G      2.178     0.0484     0.5221         63        640: 100%|██████████| 101/101 [00:08<00:00, 11.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:00<00:00, 28.43it/s]
                   all        101        647    3.3e-05    0.00155    1.7e-05   3.39e-06

I don't know why the mAP50, precision, recall, and other metrics are so low. However, if I use a COCO pre-trained model, the training converges well after loading the pre-trained weights. When training from scratch, as mentioned above, the metrics stay close to 0. Can you help me? Thank you.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @dream-ahulu, thank you for bringing this up and for your interest in Ultralytics 🚀!  

We recommend checking out our [Docs](https://docs.ultralytics.com/) for more details on getting the best results from your training. Specifically, the [Model Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) guide can help optimize your setup when training custom models.

If this is a 🐛 **Bug Report**, we'd need a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help debug the issue efficiently. From your description, it seems you're training without pre-trained weights. Please verify your dataset structure and annotations conform to the required format. You may also want to experiment with a smaller subset of your dataset to ensure the issue isn't related to data quality.  

When training from scratch, achieving good performance often requires significantly more epochs and tuning compared to using pre-trained models. If this is a ❓ **Custom Training Question**, kindly provide additional information such as:  
- A sample of your custom dataset: image examples and annotations  
- Complete training logs and your configuration (`.yaml`) files  
This would help us better understand the situation and guide you accordingly.

If you'd like insights or tips from other users, feel free to join our community discussions!  
- Real-time chat: [Discord](https://discord.com/invite/ultralytics) 🎧  
- In-depth conversation: [Discourse](https://community.ultralytics.com/)  
- Knowledge sharing: [Subreddit](https://reddit.com/r/Ultralytics)  

---

## Upgrade  

Ensure you're running the latest version of `ultralytics` by upgrading in a [**Python>=3.8**](https://www.python.org/) environment. Sometimes, issues are resolved in newer releases:  

```bash
pip install -U ultralytics
```

## Environments  

To quickly test or replicate your training setup, we recommend using one of our verified environments where dependencies are pre-installed:  
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>  
- Other cloud environments: See resources for [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) or [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).  
- Docker: Use the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.  

---

## Debug Status  

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>  

If the above badge is green, our Continuous Integration (CI) tests are up-to-date, verifying correct operations on macOS, Windows, and Ubuntu for all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/).  

This is an automated response 🤖, but don't worry, an Ultralytics engineer will take a closer look and assist you further soon! 🚀

**Comment by Y-T-G** [comment]
Did you try `rtdetr-l.yaml`?

**Comment by dream-ahulu** [comment]
Yes, I have tried it, but the results remain the same. If I don't load `rtdetr-l.pt`，only use ‘rtdetr-l.yaml’ , the metrics still stay close to zero.

**Comment by Y-T-G** [comment]
From the author, they always use a pretrained backbone to train RTDETR. So it seems like that's the recommended approach.

https://github.com/lyuwenyu/RT-DETR/issues/382

@Laughing-q We can replace the ResNet backbone in the RTDETR yaml with the one from TorchVision which comes with pretrained weights.

**Comment by dream-ahulu** [comment]
But why doesn't this issue occur when training RT-DETR-ResNet50 from scratch on the COCO dataset? Could there be a problem with my custom dataset? However, when I train YOLOv8 from scratch on my custom dataset, the issue doesn't appear. This is quite puzzling, even though my custom dataset only has one class.

**Comment by Y-T-G** [comment]
Maybe because you don't have enough images

**Comment by Y-T-G** [comment]
You can try this config. It uses pretrained ResNet50 backbone.

```yaml
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
  # [depth, width, max_channels]
  l: [1.00, 1.00, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, TorchVision, [512, resnet50, DEFAULT, True, 2, True]]
  - [0, 1, Index, [512, 6]]     # (1, 512, 80, 80)  - 1
  - [0, 1, Index, [1024, 7]]    # (1, 1024, 40, 40) - 2
  - [0, 1, Index, [2048, 8]]    # (1, 2048, 20, 20) - 3

head:
  - [-1, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 4
  - [-1, 1, AIFI, [1024, 8]]
  - [-1, 1, Conv, [256, 1, 1]] # 6

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [2, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 8
  - [[-2, -1], 1, Concat, [1]]
  - [-1, 3, RepC3, [256]] # 10
  - [-1, 1, Conv, [256, 1, 1]] # 11

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [1, 1, Conv, [256, 1, 1, None, 1, 1, False]] # 13
  - [[-2, -1], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, RepC3, [256]] # X3 (15), fpn_blocks.1

  - [-1, 1, Conv, [256, 3, 2]] # 16, downsample_convs.0
  - [[-1, 11], 1, Concat, [1]] # cat Y4
  - [-1, 3, RepC3, [256]] # F4 (18), pan_blocks.0

  - [-1, 1, Conv, [256, 3, 2]] # 19, downsample_convs.1
  - [[-1, 6], 1, Concat, [1]] # cat Y5
  - [-1, 3, RepC3, [256]] # F5 (21), pan_blocks.1

  - [[15, 18, 21], 1, RTDETRDecoder, [nc]] # Detect(P3, P4, P5)
```
