### ISSUE TITLE
Core ML Model Fails to Load: Missing outputSchema Metadata in YOLO11-seg Export

### ISSUE THREAD

**Issue by Dmcz** [ultralytics/ultralytics#19780]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

After exporting YOLO11-seg to Core ML, I encountered an error when trying to open it in Xcode.

I have tested exporting the pre-trained model, and it works fine. However, when exporting my custom-trained model using the same method, Xcode fails to open it.

Could this be related to the model training process or export settings? Any help would be greatly appreciated! 

![Image](https://github.com/user-attachments/assets/6e18edf1-c265-49ac-8b64-972ac76a3343)

Export Code
```python
   model = YOLO("/model_path")
   model.export(format="coreml", imgsz=1280)
```

Training Configuration (args.yaml)
```yaml
task: segment
mode: train
model: C:\model\yolo11s-seg.pt
data: C:\dataset\20250213\yolo\data.yaml
epochs: 400
time: null
patience: 40
batch: 8
imgsz: 1280
save: true
save_period: -1
cache: false
device: null
workers: 8
project: null
name: train
exist_ok: false
pretrained: true
optimizer: AdamW
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: 0.15
iou: 0.4
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: true
opset: null
workspace: null
nms: false
lr0: 2.0e-05
lrf: 0.005
momentum: 0.937
weight_decay: 0.0001
warmup_epochs: 5
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 8.5
cls: 1.0
dfl: 1.8
pose: 12.0
kobj: 1.0
nbs: 64
hsv_h: 0.2
hsv_s: 0.4
hsv_v: 0.3
degrees: 2.5
translate: 0.03
scale: 0.4
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0
copy_paste: 0.4
copy_paste_mode: flip
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: runs\segment\train

```
