### ISSUE TITLE
Why is the wrong path to the project directory used when downloading?

### ISSUE THREAD

**Issue by ergodeath** [ultralytics/ultralytics#20140]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

I first started my project in the folder “C:\HOME\PROG\”.
After that I created a brand new project in the folder “C:\HOME\Projects\Dog Walk”, but the download process takes place at the old address. 
Maybe the problem is in the cache and it needs to be cleaned?

Ive also tried running in a virtual environment, but everything happens the same way.

Python version:
`3.11.4`

Version packages:
```
torch==2.6.0
opencv-python==4.11.0.86
ultralytics==8.3.107
```

Code:
```python
import cv2
import torch
from ultralytics import YOLO

def main():
    model = YOLO("yolo11n-pose.pt")
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    results = model.train(data="dog-pose.yaml", epochs=3, imgsz=640, device=device) 

    video_path = r"C:\HOME\Projects\Dog Walk\video\slow-motion.mp4"
    cap = cv2.VideoCapture(video_path)
    while cap.isOpened():
        success, frame = cap.read()
        if success:
            results = model.track(frame, persist=True)

            annotated_frame = results[0].plot()

            cv2.imshow("YOLO11 Tracking", annotated_frame)

            if cv2.waitKey(10) & 0xFF == ord("q"):
                break
        else:
            break
    cap.release()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()
```

dog-pose.yaml file:

```yaml
# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Dogs dataset http://vision.stanford.edu/aditya86/ImageNetDogs/ by Stanford
# Documentation: https://docs.ultralytics.com/datasets/pose/dog-pose/
# Example usage: yolo train data=dog-pose.yaml
# parent
# ├── ultralytics
# └── datasets
#     └── dog-pose  ← downloads here (337 MB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/dog-pose # dataset root dir
train: train # train images (relative to 'path') 6773 images
val: val # val images (relative to 'path') 1703 images

# Keypoints
kpt_shape: [24, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

# Classes
names:
  0: dog

# Download script/URL (optional)
download: https://github.com/ultralytics/assets/releases/download/v0.0.0/dog-pose.zip
```

Terminal:
```
PS C:\HOME\Projects\Dog Walk> python -u "c:\HOME\Projects\Dog Walk\main.py"
Ultralytics 8.3.107 🚀 Python-3.11.4 torch-2.6.0+cpu CPU (AMD Ryzen 5 5600H with Radeon Graphics)
engine\trainer: task=pose, mode=train, model=yolo11n-pose.pt, data=dog-pose.yaml, epochs=3, time=None, patience=100, batch=16, 
imgsz=640, save=True, save_period=-1, cache=False, device=cpu, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, 
show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\pose\train
Dataset 'dog-pose.yaml' images not found ⚠️, missing path 'C:\HOME\PROG\datasets\dog-pose\val'
Downloading https://ultralytics.com/assets/dog-pose.zip to 'C:\HOME\PROG\datasets\dog-pose.zip'...
100%|...| 337M/337M [00:31<00:00, 11.4MB/s]
Unzipping C:\HOME\PROG\datasets\dog-pose.zip to C:\HOME\PROG\datasets\dog-pose...: 100%|...| 16961/16961 [00:07<00:00, 
Dataset download success ✅ (39.8s), saved to C:\HOME\PROG\datasets
...
...
```

the following folders are created in the project directory `"C:\HOME\Projects\Dog Walk\"`:
```
 runs/pose/train
 runs/pose/train ...
```
