### ISSUE TITLE
Internal error: Failed to apply delegate:

### ISSUE THREAD

**Issue by shehanGuruge** [ultralytics/ultralytics#20302]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am trying to run a yolov10n model in my flutter application. The library I use is https://pub.dev/packages/ultralytics_yolo. The yolov8n model works fine but when I load the v10n model the application crashes with this error,

```
E/YoloView(31252): Failed to load model: yolov10n
E/YoloView(31252): java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
E/YoloView(31252): ADD: Max version supported: 2. Requested version 4.
E/YoloView(31252): CAST: Not supported Cast case. Input type: BOOL and output type: INT64
E/YoloView(31252): CAST: Not supported Cast case. Input type: FLOAT32 and output type: INT64
E/YoloView(31252): CAST: Not supported Cast case. Input type: INT32 and output type: INT64
E/YoloView(31252): CAST: Not supported Cast case. Input type: INT64 and output type: FLOAT32
E/YoloView(31252): CONCATENATION: OP is supported, but tensor type/shape isn't compatible
E/YoloView(31252):      at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
E/YoloView(31252):      at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:110)
E/YoloView(31252):      at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
E/YoloView(31252):      at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
E/YoloView(31252):      at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:230)
E/YoloView(31252):      at com.ultralytics.yolo.ObjectDetector.<init>(ObjectDetector.kt:129)
E/YoloView(31252):      at com.ultralytics.yolo.YoloView.setModel$lambda$5(YoloView.kt:223)
E/YoloView(31252):      at com.ultralytics.yolo.YoloView.$r8$lambda$ZhLm8i7knpxok7dSJQa5eweve7I(Unknown Source:0)
E/YoloView(31252):      at com.ultralytics.yolo.YoloView$$ExternalSyntheticLambda4.run(Unknown Source:8)
E/YoloView(31252):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/YoloView(31252):      at java.util.concurrent.ThreadPoolExecutor$Work
```

### Environment

```
name: ml
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.4
  ultralytics_yolo: ^0.0.7
  camera: ^0.11.0+2
  image: ^4.2.0
  collection: ^1.18.0
  permission_handler: ^10.2.0
  image_picker: ^1.1.2
  flutter_image_gallery_saver: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    -  assets/

  uses-material-design: true

```

### Minimal Reproducible Example

Create a new flutter app and add the yolov10n model following the steps mentioned in https://pub.dev/packages/ultralytics_yolo. 

Later add the code 

```
import 'package:flutter/material.dart';
import 'package:ultralytics_yolo/yolo.dart';
import 'package:ultralytics_yolo/yolo_view.dart';


class PredictScreen extends StatefulWidget {
  const PredictScreen({super.key});

  @override
  State<PredictScreen> createState() => _PredictScreenState();
}

class _PredictScreenState extends State<PredictScreen> {
  final viewController = YoloViewController();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Home Screen"),
      ),
      body:  YoloView(
          controller: viewController,
          task: YOLOTask.detect,
          modelPath: 'yolov10n',
          onResult: (results) {
            print('Detected ${results.length} objects');
          },
        ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}
```

### Additional

Are only YOLOv8n models currently supported in the Flutter app, or is it possible to use other models as well?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
