### ISSUE TITLE
Python code for training

### ISSUE THREAD

**Issue by SilentJCR** [ultralytics/ultralytics#20512]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

Hi, I've been training the yolo11 model using my own dataset with commands like:

`yolo detect train data=datasets/demo_items_20250506/demo_items.yaml model=yolo11s.pt epochs=150 imgsz=640 device=0 batch=32 lr0=0.001`

It worked well.

Now I'd like to write a Python code to do the same thing. Currently the simplest code snippet is like:

```
from ultralytics import YOLO

# Load a COCO-pretrained YOLO11n model
pretrained_model = "yolo11n.pt"
model = YOLO(pretrained_model)

# Train the model with custom configuration
model.train(cfg="datasets/demo_items_20250506/demo_items.yaml")
```

As for the parameters like epochs, imgsz, batch and lr0, I instead wrote them into the demo_items.yaml.

I then ran the code and I just kept receiving errors like

> Traceback (most recent call last):
>   File "/home/averai/Jefferson/ultralytics/train_custom_data.py", line 8, in <module>
>     model.train(cfg="datasets/demo_items_20250506/demo_items.yaml")
>   File "/home/averai/Jefferson/ultralytics/ultralytics/engine/model.py", line 785, in train
>     self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/averai/Jefferson/ultralytics/ultralytics/engine/trainer.py", line 105, in __init__
>     self.args = get_cfg(cfg, overrides)
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/averai/Jefferson/ultralytics/ultralytics/cfg/__init__.py", line 310, in get_cfg
>     check_dict_alignment(cfg, overrides)
>   File "/home/averai/Jefferson/ultralytics/ultralytics/cfg/__init__.py", line 497, in check_dict_alignment
>     raise SyntaxError(string + CLI_HELP_MSG) from e
> SyntaxError: 'path' is not a valid YOLO argument. Similar arguments are i.e. ['batch=16'].
> 'names' is not a valid YOLO argument. Similar arguments are i.e. ['name', 'nms=False'].
> 'train' is not a valid YOLO argument. Similar arguments are i.e. ['pretrained=True', 'erasing=0.4', 'fraction=1.0'].

My .yaml file is as follows:

```
path: /home/averai/Jefferson/ultralytics/datasets/demo_items_20250506
train: images/train
val: images/val

task: detect # (str) YOLO task, i.e. detect, segment, classify, pose, obb
mode: train # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

epochs: 200
lr0: 0.001
batch: 32
imgsz: 640


degrees: 5.0 # (float) image rotation (+/- deg)
scale: 0.2 # (float) image scale (+/- gain)
fliplr: 0.5 # (float) image flip left-right (probability)
flipud: 0.5 # (float) image flip up-down (probability)
mosaic: 0.1 # (float) image mosaic (probability)

# nc: 4
# names: ['BlackTea', 'MilkTea', 'Toothpaste', 'ChestNut']

names:
  0: BlackTea
  1: MilkTea
  2: Toothpaste
  3: ChestNut
```

Not sure if I'm misunderstanding anything.
