### ISSUE TITLE
loadModel() returns false every time in IOS when using ultralytics_yolo

### ISSUE THREAD

**Issue by shehanGuruge** [ultralytics/ultralytics#20651]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi,

I am integrating [ultralytics_yolo](https://pub.dev/packages/ultralytics_yolo) in a flutter application and I am loading the model using 

```
yolo = YOLO(modelPath: 'yolov8n', task: YOLOTask.detect);
return await yolo.loadModel();
```
however in IOS it always returns false even when the model is present. 

Additionally in Android even if we load the model like above, when we invoke the yolo.predict function first time, it takes some time to initialize the native runtime which I presume should happen during the loadModel(). The logs in android is like belows when i try the inference for the first time,

```
I/tflite  (18205): Created TensorFlow Lite delegate for GPU.
D/TAG     (18205): GPU delegate is used.
D/YoloUtils(18205): Loading model from path: yolov8n.tflite
D/YoloUtils(18205): Loading model from assets: yolov8n.tflite
D/ObjectDetector(18205): Model metadata retrieved successfully.
D/ObjectDetector(18205): Found associated file: temp_meta.txt
D/ObjectDetector(18205): Associated file contents:
D/ObjectDetector(18205): {...}
D/ObjectDetector(18205): Loaded labels from metadata: [...]
I/TensorFlowLite(18205): Loaded native library: tensorflowlite_jni
I/TensorFlowLite(18205): Didn't load native library: tensorflowlite_jni_gms_client
I/tflite  (18205): Initialized TensorFlow Lite runtime.
I/tflite  (18205): Loaded OpenCL library with dlopen.
I/tflite  (18205): Replacing 252 out of 252 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions for subgraph 0.
E/BufferQueueProducer(18205): [ImageReader-320x240f23m4-18205-1](id:471d00000003,api:4,p:1794,c:18205) dequeueBuffer: waitForFreeSlotThenRelock: timeout. dequeuedCount: 0, acquiredCount: 2
I/tflite  (18205): Initialized OpenCL-based API.
I/tflite  (18205): Created 1 GPU delegate kernels.
D/TAG     (18205): TFLite model loaded: yolov8n
D/TAG     (18205): Model input size = 320 x 320
D/TAG     (18205): Model output shape = [1, 6, 2100]
D/TAG     (18205): ObjectDetector initialized.
D/TFLite  (18205): Output shape: [1, 6, 2100]
```

The above issue in Android causes the application to be unresponsive for a couple of seconds.

### Environment

```
name: ultralytics_yolo_pkg_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  ultralytics_yolo: ^0.0.7
  camera: ^0.11.1
  path: ^1.9.0
  path_provider: ^2.1.5
  collection: ^1.19.0
  image: ^4.5.4
  permission_handler: ^10.2.0
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


```

### Minimal Reproducible Example

Create a new flutter application. Add the models to the native folders. Instead of using the YoloView, use the camera plugin and feed the frames to the model. Include the code to load the model

```
  Future<bool> _initObjectDetectorWithLocalModel() async {
    yolo = YOLO(modelPath: 'yolov8n', task: YOLOTask.detect);
    return await yolo.loadModel();
  }
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
