### ISSUE TITLE
[rank1]: RuntimeError: Given groups=1, weight of size [1024, 1024, 1, 1], expected input[1, 512, 1, 1] to have 1024 channels, but got 512 channels instead.When I use the CBAM attention mechanism with dual-GPU training.

### ISSUE THREAD

**Issue by genanalucy** [ultralytics/ultralytics#20707]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug
```bash
(Pytorch) (base) lutaotian@yons-MS-7E06:~/PyCode/CV/ultralytics-8.3.27$ python train_v8.py  
Ultralytics 8.3.27 🚀 Python-3.9.21 torch-2.6.0+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24083MiB)
                                                      CUDA:1 (NVIDIA GeForce RTX 4090, 24092MiB)
engine/trainer: task=obb, mode=train, model=/home/lutaotian/PyCode/CV/ultralytics-8.3.27/ultralytics/cfg/models/v8/yolov8s-obb.yaml, data=./ultralytics/cfg/datasets/yolov8Dataset.yaml, epochs=200, time=None, patience=100, batch=16, imgsz=1280, save=True, save_period=-1, cache=False, device=0,1, workers=8, project=None, name=train18, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=200, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.6, hsv_v=0.5, degrees=50.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=0.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/obb/train18

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1    262754  ultralytics.nn.modules.conv.CBAM             [512]                         
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 13                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 18            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 19                  -1  1    624128  ultralytics.nn.modules.block.C2f             [896, 256, 1]                 
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 21             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 22                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 23        [15, 18, 21]  1  15133201  ultralytics.nn.modules.head.OBB              [10, 1, [384, 896, 768]]      
YOLOv8s-obb summary: 258 layers, 24,546,579 parameters, 24,546,563 gradients, 90.0 GFLOPs

DDP: debug command /home/lutaotian/anaconda3/envs/Pytorch/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 56419 /home/lutaotian/.config/Ultralytics/DDP/_temp_14pj4zay132860247632240.py
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/lutaotian/.config/Ultralytics/DDP/_temp_14pj4zay132860247632240.py", line 13, in <module>
[rank1]:     results = trainer.train()
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 211, in train
[rank1]:     self._do_train(world_size)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 332, in _do_train
[rank1]:     self._setup_train(world_size)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 238, in _setup_train
[rank1]:     ckpt = self.setup_model()
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 615, in setup_model
[rank1]:     self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/models/yolo/obb/train.py", line 70, in get_model
[rank1]:     model = OBBModel(cfg, nc=self.data["nc"], ch=self.data["channels"], verbose=verbose and RANK == -1)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 463, in __init__
[rank1]:     super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 366, in __init__
[rank1]:     m.stride = torch.tensor([s / x.shape[-2] for x in _forward(torch.zeros(1, ch, s, s))])  # forward
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 364, in _forward
[rank1]:     return self.forward(x)[0] if isinstance(m, (Segment, YOLOESegment, Pose, OBB)) else self.forward(x)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 116, in forward
[rank1]:     return self.predict(x, *args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 134, in predict
[rank1]:     return self._predict_once(x, profile, visualize, embed)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 157, in _predict_once
[rank1]:     x = m(x)  # run
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/modules/conv.py", line 650, in forward
[rank1]:     return self.spatial_attention(self.channel_attention(x))
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics/nn/modules/conv.py", line 577, in forward
[rank1]:     return x * self.act(self.fc(self.pool(x)))
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 554, in forward
[rank1]:     return self._conv_forward(input, self.weight, self.bias)
[rank1]:   File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
[rank1]:     return F.conv2d(
[rank1]: RuntimeError: Given groups=1, weight of size [1024, 1024, 1, 1], expected input[1, 512, 1, 1] to have 1024 channels, but got 512 channels instead
W0519 16:21:03.686018 34510 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 34512 closing signal SIGTERM
E0519 16:21:03.702828 34510 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 34513) of binary: /home/lutaotian/anaconda3/envs/Pytorch/bin/python
Traceback (most recent call last):
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/run.py", line 922, in <module>
    main()
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/lutaotian/.config/Ultralytics/DDP/_temp_14pj4zay132860247632240.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-19_16:21:03
  host      : yons-MS-7E06
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 34513)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/lutaotian/PyCode/CV/ultralytics-8.3.27/train_v8.py", line 5, in <module>
    train_re = model.train(data='./ultralytics/cfg/datasets/yolov8Dataset.yaml',epochs=200,batch=16,close_mosaic=200,device = '0,1')
  File "/home/lutaotian/PyCode/CV/ultralytics-8.3.27/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/home/lutaotian/PyCode/CV/ultralytics-8.3.27/ultralytics/engine/trainer.py", line 202, in train
    raise e
  File "/home/lutaotian/PyCode/CV/ultralytics-8.3.27/ultralytics/engine/trainer.py", line 200, in train
    subprocess.run(cmd, check=True)
  File "/home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lutaotian/anaconda3/envs/Pytorch/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '56419', '/home/lutaotian/.config/Ultralytics/DDP/_temp_14pj4zay132860247632240.py']' returned non-zero exit status 1.
```
### Environment

Ultralytics 8.3.139 🚀 Python-3.9.21 torch-2.6.0+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24083MiB)
Setup complete ✅ (32 CPUs, 62.6 GB RAM, 576.1/1832.2 GB disk)

OS                  Linux-6.8.0-59-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.21
Install             pip
Path                /home/lutaotian/anaconda3/envs/Pytorch/lib/python3.9/site-packages/ultralytics
RAM                 62.63 GB
Disk                576.1/1832.2 GB
CPU                 Intel Core(TM) i9-14900KF
CPU count           32
GPU                 NVIDIA GeForce RTX 4090, 24083MiB
GPU count           2
CUDA                12.6

numpy               ✅ 1.26.3>=1.23.0
matplotlib          ✅ 3.9.4>=3.3.0
opencv-python       ✅ 4.11.0.86>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.6.0+cu126>=1.8.0
torch               ✅ 2.6.0+cu126!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.21.0+cu126>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 7.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
ultralytics-thop    ✅ 2.0.14>=2.0.0

### Minimal Reproducible Example

My train_v8.py
```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('/home/lutaotian/PyCode/CV/ultralytics-8.3.27/ultralytics/cfg/models/v8/yolov8s-obb.yaml')
    train_re = model.train(data='./ultralytics/cfg/datasets/yolov8Dataset.yaml',epochs=200,batch=8,close_mosaic=200,device = '0,1')
```

My yolov8s-obb.yaml
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 Oriented Bounding Boxes (OBB) model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 10 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, CBAM, [1024]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12
  
#  - [-1, 1, CBAM, [512]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)
  
#  - [-1, 1, CBAM, [256]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)
  
#  - [-1, 1, CBAM, [512]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, OBB, [nc, 1]] # OBB(P3, P4, P5)
(data='./ultralytics/cfg/datasets/yolov8Dataset.yaml',epochs=200,batch=8,close_mosaic=200,device = '0,1')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
