### ISSUE TITLE
Using data augmentation on YOLOv8

### ISSUE THREAD

**Issue by Peanpepu** [ultralytics/ultralytics#2412]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Im trying to increment my custom dataset with data augmentation, but after searching a lot i didn't found any example or explanation about how to implement it. I guess i have to change my .yaml file but i would like to have an example about how to do it before.
Thank you in advance.

**Comment by glenn-jocher** [comment]
@Peanpepu hello! To increment your custom dataset with data augmentation, you will need to modify your dataset configuration file, which is typically a `.yaml` file. Inside this file, you will need to add an augmentation section with parameters that specify how you want to augment your data. 

The Ultralytics YOLOv8 repo supports a wide range of data augmentations. For instance, you can use a variety of transformations such as random crops, flipping, rotation, and distortion. Additionally, you can configure the intensity of these augmentation techniques with specific parameters to generate more data variety.

One option is to use the `mosaic` augmentation technique to combine four images into one, which helps prevent overfitting and augment your training data. You can also use the `mixup` augmentation to generate synthetic data by mixing two different images.

I hope this information points you in the right direction. If you have further questions or need assistance, please feel free to reach out.

**Comment by Peanpepu** [comment]
Is there any example of a config.yaml with data augmentation?

**Comment by Peanpepu** [comment]
I know the posibilities for data augmentation but i would like to see a config.yaml example for YOLOv8 with data augmentation. Could you tell me where can i find it?

**Comment by glenn-jocher** [comment]
@Peanpepu hello! Thank you for reaching out. Sure, I can help you with an example of a `config.yaml` file in YOLOv8 with data augmentation. 

For instance, if you want to apply random horizontal flipping, you can specify `hflip: 0.5` under the augmentation section. Similarly, you can use different techniques to augment the data with certain parameters to configure intensity. You could also use the `mosaic` augmentation technique that combines four images into one. On the other hand, you can use the `mixup` augmentation to generate synthetic data by mixing two different images. 

Please note that the specific augmentation techniques and parameters will depend on your dataset and your training objectives. However, the "augmentation" section of the configuration file gives you plenty of flexibility to apply various augmentation techniques.

I hope this helps! Let me know if you have any other questions.

**Comment by Peanpepu** [comment]
I'm using the following yaml file, which i call from a python file:
```
path: /root/TFG/data/dataset_rgb # rgb dataset root dir
# path: /home/pedrop/Desktop/TFG/data/dataset_term # thermical dataset root dir
train: images/train # train images (relative to "path")
val: images/test # validation images (relative to "path")

# class names
names:
  0: 'emergency vehicle'
  1: 'non-emergency vehicle'
  2: 'first responder'
  3: 'non-first responder'

# Hyperparameters ------------------------------------------------------------------------------------------------------
# lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
# lrf: 0.01  # final learning rate (lr0 * lrf)
# momentum: 0.937  # SGD momentum/Adam beta1
# weight_decay: 0.0005  # optimizer weight decay 5e-4
# warmup_epochs: 3.0  # warmup epochs (fractions ok)
# warmup_momentum: 0.8  # warmup initial momentum
# warmup_bias_lr: 0.1  # warmup initial bias lr
# box: 7.5  # box loss gain
# cls: 0.5  # cls loss gain (scale with pixels)
# dfl: 1.5  # dfl loss gain
# pose: 12.0  # pose loss gain
# kobj: 1.0  # keypoint obj loss gain
# label_smoothing: 0.0  # label smoothing (fraction)
# nbs: 64  # nominal batch size
# hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
# hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
# hsv_v: 0.4  # image HSV-Value augmentation (fraction)
# degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.2  # image scale (+/- gain)
shear: 0.2  # image shear (+/- deg) from -0.5 to 0.5
perspective: 0.1  # image perspective (+/- fraction), range 0-0.001
flipud: 0.7  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 0.3  # image mosaic (probability)
mixup: 0.1  # image mixup (probability)
# copy_paste: 0.0  # segment copy-paste (probability)
```
However, when i try to train my network these data augmentation parameters that i declare don't take its set values. What am I doing wrong?
