### ISSUE TITLE
How  How to pass albumation albunetations for  task classifiaction 

### ISSUE THREAD

**Issue by DimIsaev** [ultralytics/ultralytics#2658]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to change the albementation parameters if the line does not transfer the configuration file, but only the path to the dataset is used

`pip install -q albumentations`

`!yolo task=classify mode=train model=yolov8n-cls.pt data={dataset.location} epochs=50 imgsz=128`

default  parameters view
`albumentations: RandomResizedCrop(p=1.0, height=224, width=224, scale=(0.08, 1.0), ratio=(0.75, 1.3333333333333333), interpolation=1), HorizontalFlip(p=0.5), ColorJitter(p=0.5, brightness=[0.6, 1.4], contrast=[0.6, 1.4], saturation=[0.6, 1.4], hue=[0, 0]), Normalize(p=1.0, mean=(0.0, 0.0, 0.0), std=(1.0, 1.0, 1.0), max_pixel_value=255.0),`

### Additional
Example  file confiration 
```

train: /content/train/
val: /content/val/
nc: 3
names: ['frontvhs','sidevhs','topvhs']
augmentations:
- Albumentations:
    blur_limit: 1
    brightness_contrast: 
      brightness_limit: 0.1
      contrast_limit: 0.1
    gauss_noise:
      var_limit: (10.0, 20.0)
    horizontal_flip: true
    hue_saturation:
      hue_shift_limit: 20
      sat_shift_limit: 50
    rotate:
      limit: 45
      p: 0.5
```

_No response_
