### ISSUE TITLE
add attention model

### ISSUE THREAD

**Issue by ChenJian7578** [ultralytics/ultralytics#2958]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I added the attention module to the original 8s network. Is there any way to import the 8s pre-trained weights into the new network architecture, because the original network layers are still there.

**Comment by Kayzwer** [comment]
There is another branch https://github.com/ultralytics/ultralytics/tree/rtdetr_loss which haven't merge to main yet, maybe you can switch to that branch to use the Real Time Detection Transformer.

**Comment by glenn-jocher** [comment]
Hello @ChenJian7578, thank you for the suggestion! We appreciate your interest in YOLOv8 🚀. The Ultralytics team is committed to continuously improving the YOLOv8 repository and adding new features that benefit the community. While we cannot comment on the status of any branches that have not been merged into the main repository yet, we encourage everyone to experiment with any available branches and make pull requests if they have new features that may benefit the YOLOv8 community. We will continue to evaluate and incorporate new features as they align with our project's focus and goals.

**Comment by ChenJian7578** [comment]
The attention module I want to add is not transformers, but attention modules like SEAttention and CBAMAttention on the original network. like this:
![image](https://github.com/ultralytics/ultralytics/assets/42240985/7bd9fa7b-f6cd-435d-93f5-d4a31249ea3a)
i use the CBAM + Conv  as CBAMConv model to replace the origin Conv model. but i still want use pretrain weights for these models i made no changes.  What should I do?

**Comment by Kayzwer** [comment]
you need to modify the nn/ in the ultralytics/.

**Comment by AbdesselamFerdi** [comment]
If you want to load the standard YOLOv8s detector with COCO-pretrained weights, the command is: model=YOLO('./yolov8s.yaml').load('./yolov8s.pt').
For your modified YOLOv8s, you can use the same command but only weights of the standard YOLOv8s layers are initialiazed with the pretrained weights.

**Comment by glenn-jocher** [comment]
@Kayzwer hello! If you have modified the YOLOv8s architecture by replacing its Conv layers with CBAMConvs, you can still load the pretrained weights for the standard YOLOv8s layers, but not for the modified layers. To do this, you can use the YOLO class and its load method as follows: `model = YOLO('./path/to/modified_yolov8s.yaml').load('./path/to/yolov8s.pt')`. This will initialize the standard YOLOv8s layers with the pretrained weights, but the modified layers will need to be trained on your specific dataset from scratch. I hope this helps!

**Comment by whitewalker11** [comment]
@ChenJian7578 

```
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments                     
Traceback (most recent call last):
  File "/home/skylark/Documents/ultralytics/ultralytics/train.py", line 4, in <module>
    model = YOLO("model.yaml") #.load('.yolov8s.pt')  # build a new model from scratch
  File "/home/skylark/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 92, in __init__
    self._new(model, task)
  File "/home/skylark/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 122, in _new
    self.model = model(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/skylark/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 233, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/home/skylark/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 674, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'CBAM'
```

getting this error after changing the yaml according to what you have mentioned

**Comment by zeinabelsharkawy** [comment]
I interested
I have the same question.

**Comment by glenn-jocher** [comment]
@zeinabelsharkawy hello! If you are encountering the same issue while trying to add an attention module to the YOLOv8 network, I would suggest following the steps mentioned previously. You should load the standard pretrained weights using the `.load()` method. This will initialize the weights for the standard YOLOv8 layers, but not for the modified layers (in this case the attention module). Remember to include your attention module in the `.yaml` file. If you're still facing any errors, please provide more specifics about the issue so we can assist you better.

**Comment by HcosYu** [comment]
@glenn-jocher 
I have a question
When I run the code:
`model = YOLO('ultralytics/ultralytics/cfg/models/v8/my_yolov8_CBMA.yaml').load('runs/detect/v8n_flip_sea_e50/weights/best.pt')`
I've got the error
```
KeyError
'SEAttention'
  File "D:\yolo_deection\test_detection_v8.py", line 50, in <module>
    model = YOLO('ultralytics/ultralytics/cfg/models/v8/my_yolov8_CBMA.yaml').load('runs/detect/v8n_flip_sea_e50/weights/best.pt')
KeyError: 'SEAttention'
```
Thank you in advance

**Comment by glenn-jocher** [comment]
@HcosYu hello! The `KeyError: 'SEAttention'` suggests that the SEAttention module is not recognized within the YOLOv8 architecture. This typically happens when the module is not defined or registered in the model's namespace. To resolve this, ensure that the SEAttention module is properly implemented and accessible in the model definition. If you've added a custom module, you'll also need to ensure it's imported and available in the scope where the model is being constructed.

**Comment by glenn-jocher** [comment]
Hi @minushuang! It looks like you're doing some advanced customization with EMA modules in YOLOv8n, nice work! 🚀 When adding new layers like EMA that don't match the original model architecture, the pretrained weights for those specific new layers can't be transferred directly since they don't exist in the `yolov8n.pt` pretrained model. 

The log indicates that weights for existing matching layers in your modified architecture were successfully transferred (`Transferred 210/373 items from pretrained weights`). This is expected behavior. New or modified layers that don't have a matching counterpart in the original pretrained model file will be initialized but won't have pretrained weights. You'll need to train these parts of your model from scratch.

Focus on training your model with a suitable dataset that will allow these new EMA layers to learn effectively. This combined approach leverages the strength of pretrained models for known layers while adapting to new architectural features through further training. Keep up the experimentation! 🌟

**Comment by minushuang** [comment]
Hi @glenn-jocher thanks for your prompt reply, I checked the pretrained `yolov8n.pt` model with the original `yolov8.yaml` without the EMA modules, the train log shows `Transferred 355/355 items from pretrained weights`, Does this mean the pretrained model have 355 pretrained weights? but in my modified model, only 210 weights are transferred successfully.

below is the modified yaml with EMA module, it seems that the transfered process is ended from the first EMA module at line `[ -1, 1, EMA, [ 8 ] ]  #16`
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)
  - [ -1, 1, EMA, [ 8 ] ]  #16

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 19 (P4/16-medium)
  - [ -1, 1, EMA, [ 8 ] ] #20

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 23 (P5/32-large)
  - [ -1, 1, EMA, [ 8 ] ] #24

  - [[16, 20, 24], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```
