### ISSUE TITLE
correct way to inference custom dataset with just one split type

### ISSUE THREAD

**Issue by jet-c-21** [ultralytics/ultralytics#3337]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
```
eval-datasets
|-- P008_eval
|   |-- images
|   |   `-- eval
|   `-- labels
|       |-- eval
|       `-- eval.cache
`-- P008_eval.yaml (can I put yaml at here?)
```
also i have another directory `datasets` next to my `eval-datasets`

project
|_eval-datasets
|_datasets

I got following issue:
1. what's the correct path should a yaml path be?
2. how to prevent yolo to loading images in the dir `datasets`, I have defined `eval-datasets` I want it to just read files in it
3. what's the correct way to write the content of yaml?

my yaml content:
```yaml
names:
  0: person
  1: flying bird
  2: not flying bird
path: /home/ichase-jet/my_home/target_project/AIBR-DSB/eval-datasets/P008_eval
test: images/eval
train: ''
val: ''
```
