### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by touch177** [ultralytics/ultralytics#3378]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

****When I initiate training with the command yolo pose train data=datasetkey_point.yaml model=yolov8x-pose.pt epochs=100 imgsz=320 project="20230626keypoint" name='test' batch=16, I encounter the following error:**** 

Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
      1/100      4.36G     0.5319     0.9309     0.4692     0.7164        1.2          2        320: 100%|██████████| 1089/1089 [06:23<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 146/146 [ 
Traceback (most recent call last):
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\touch\anaconda3\envs\yoloupdata\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 405, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\engine\model.py", line 373, in train
    self.trainer.train()
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 372, in _do_train
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\engine\validator.py", line 177, in __call__
    stats = self.get_stats()
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\v8\detect\val.py", line 128, in get_stats
    self.metrics.process(*stats)
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\utils\metrics.py", line 885, in process
    results_pose = ap_per_class(tp_p,
  File "C:\Users\touch\anaconda3\envs\yoloupdata\lib\site-packages\ultralytics\yolo\utils\metrics.py", line 485, in ap_per_class
    names = [v for k, v in names.items() if k in unique_classes]  # list: only classes that have data
AttributeError: 'str' object has no attribute 'items' 

Afterwards, I was able to run the program normally by commenting out the following parts of the code in metrics.py. These parts of the code have an associated bug, AttributeError: 'str' object has no attribute 'items'.

 f1 = 2 * p * r / (p + r + eps)
    # names = [v for k, v in names.items() if k in unique_classes]  # list: only classes that have data
    # names = dict(enumerate(names))  # to dict
    # if plot:
    #     plot_pr_curve(px, py, ap, save_dir / f'{prefix}PR_curve.png', names, on_plot=on_plot)
    #     plot_mc_curve(px, f1, save_dir / f'{prefix}F1_curve.png', names, ylabel='F1', on_plot=on_plot)
    #     plot_mc_curve(px, p, save_dir / f'{prefix}P_curve.png', names, ylabel='Precision', on_plot=on_plot)
    #     plot_mc_curve(px, r, save_dir / f'{prefix}R_curve.png', names, ylabel='Recall', on_plot=on_plot)

### Environment

Ultralytics YOLOv8.0.122  Python-3.10.12 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
windows11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@touch177 your `names` variable seems to be a list instead of a dictionary. Make sure your define your classes as a dictionary in your data YAML, i.e.

```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes) <-- MUST BE DICTIONARY
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush
```
