### ISSUE TITLE
Tracking ID from boxes not found

### ISSUE THREAD

**Issue by aus10powell** [ultralytics/ultralytics#3793]
#### Version Info:
* python 3.11.3
* ultralytics: 8.0.136
* supervision: 0.11.1

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My setup:

Have a trained object detection model that has around 0.70 mAP50-95
Using model with track method:
    for result in model.track(
        source=video_path,
        show=True,
        stream=True,
        agnostic_nms=True,
        tracker="botsort.yaml",
    ):

Here's my current settings for the "botsort.yaml":
```yaml
tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.2  # 0.6 default threshold for the first association
track_low_thresh: 0.1  # threshold for the second association
new_track_thresh: 0.1  # 0.6 default threshold for init new track if the detection does not match any tracks
track_buffer: 30  # buffer to calculate the time when to remove tracks
match_thresh: 0.1  # 0.8 default threshold for matching tracks
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

#### BoT-SORT settings
cmc_method: sparseOptFlow  # method of global motion compensation
#### ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False
```

My problem:
I'm getting decent confidence on all images (see screenshot below), but having inconsistent results with both ID'ing the object.

Things I've tried:

Adjusting he above parameters to be surprisingly low
Trying to get lower cls_loss to help with object id'ing (~2.8 logloss is best I've gotten. Not great but the video quality is not great)
My Question:

Suggestions on most likely culprit to improve given that I likely will not be able to improve video quality

PS I've attached a screenshot of one such image with the above parameters set and I don't understand why a tracking ID is not created from the box
<img width="640" alt="Screenshot 2023-07-17 at 12 11 35 PM" src="https://github.com/ultralytics/ultralytics/assets/7726251/bf5f5d2b-6e69-469b-b8b6-f16e92bdb605">

### Additional

* I can verify that there are detections being made from the supervision package with the appropriate class_id (0) but no tracking id assigned:
```python
Detections(xyxy=array([[     302.09,      178.18,      319.97,      210.87]], dtype=float32), mask=None, confidence=array([    0.45749], dtype=float32), class_id=array([0]), tracker_id=None)
```
