### ISSUE TITLE
 i got this error (args.append([ch[x] for x in f]) IndexError: list index out of range)

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#3898]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

@glenn-jocher
i am trying my structure ,from 2 weeks ago i was working , when i try today i got an error 

`Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 383, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 104, in __init__
    self._new(model, task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 137, in _new
    self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 322, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 792, in parse_model
    args.append([ch[x] for x in f])
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 792, in <listcomp>
    args.append([ch[x] for x in f])
IndexError: list index out of range`

this is my 

```
`# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs


backbone:
  # [from, number, module, args]
 - [-1, 1,  X_Stem, [256, 4, 2]],  # 0-P1/2 (increased filters and stride)
 - [-1, 4,  X_Block, [512,512]],  # 1
 - [-1, 1,  X_Downsample, [512, 2, 2]],   # 2-P2/4 (increased filters and stride)
 - [-1, 4,  X_Block, [512,512]],  # 3
 - [-1, 1,  X_Downsample, [1024, 2, 2]],   # 4-P3/8 (increased filters and stride)
 - [-1, 4,  X_Block, [1024,1024]],  # 5 (decreased number of layers)
 - [-1, 1,  X_Downsample, [2048, 2, 2]],   # 6-P4/16 (increased filters and stride)
 - [-1, 4,  X_Block, [2048,2048]],  # 7 (decreased number of layers)
 - [-1, 1, SPPF, [1024, 5]],  # 9
  


`
```
how to fix this 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
