### ISSUE TITLE
Confusing yolov8 folder management

### ISSUE THREAD

**Issue by ichsan2895** [ultralytics/ultralytics#415]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation, Detection

### Bug

Confusing folder management in yolov8 8.0.6 vs 8.0.5. Somehow, yolov8 8.0.6 created `datasets` directory automatically and we must input training data in there. It was different in 8.0.5 that can use same folder with `yaml` folder.

You can check my Google Colab Notebook for any ilustration
https://colab.research.google.com/drive/1PxFZfbobw5wt4XVhiq68FCQszrdhBIlB?usp=sharing 

My `custom_dataset.yaml` file
```
train: TRAIN_SEG
val: VAL_SEG
test: TEST_SEG

nc: 2
names: ['palm', 'young-palm']

roboflow:
  workspace: palmdetection-1cjxw
  project: palm_detection_experiment
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/palmdetection-1cjxw/palm_detection_experiment/dataset/3
```

### Environment

Google colab env:
```
Ultralytics YOLOv8.0.6 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.4/78.2 GB disk)
```

### Minimal Reproducible Example

You can check my Google Colab Notebook for any ilustration
https://colab.research.google.com/drive/1PxFZfbobw5wt4XVhiq68FCQszrdhBIlB?usp=sharing 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
