### ISSUE TITLE
How to perform segmentation for two classes with different dataset paths?

### ISSUE THREAD

**Issue by ammar-deep** [ultralytics/ultralytics#4624]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training a segmentation model on custom dataset with two classes (classA and classB). The only difference from regular datasets is that my images and corresponding labels have exactly one class during training i.e. classA images only have this class labels and not classB labels and similarly classB images only have its labels and not classA

My data.yaml file is as follows.

```
path: /
train: 
 - './classA/images/train'
 - './classB/images/train'
val: 
 - './classA/images/valid'
 - './classB/images/valid'

names:
 0: classA
 1: classB

nc: 2
```
When I train this model my model is only able to segment classA and it cannot detect or segment classB. I tried to swap the names i.e. 0 for classB and 1 for classA and retrained and this time it only segments classB in short it only learns the 0 label class. 

Can someone help me in segmenting both classes together during inference?
