### ISSUE TITLE
YOLO framework flip left-right of my dataset when training

### ISSUE THREAD

**Issue by elcolie** [ultralytics/ultralytics#4760]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to correctly disable data augmentation in YOLO framework?

`echometer.yaml`
```yaml
path: .
train: echometer_nodistraction/images
val: echometer_nodistraction/images
test:

names:
  0: firing
  1: bump

flipud: 0.0 # image flip up-down (probability)
fliplr: 0.0 # image flip left-right (probability)
mosaic: 0.0 # image mosaic (probability)
mixup: 0.0 # image mixup (probability)
copy_paste: 0.0 # segment copy-paste (probability)
```

`main.py`
```python
    model = YOLO("yolov8n.yaml")  # build a new model from scratch
    model.train(data="echometer.yaml", epochs=50, device=device, batch=3, augment=False)
    metrics = model.val(data="echometer.yaml", device=device)
    print(metrics)
```

In the `train_batch1.jpg` it shows me the flip left-right picture
![image](https://github.com/ultralytics/ultralytics/assets/18206728/6b12d1bd-40ed-4256-b8d3-b6903b5af0db)
And even worst for the next `train_batch2.jpg` it flip left-right all picture except 1 picture.
The long spike must be in the left hand side as always.
![image](https://github.com/ultralytics/ultralytics/assets/18206728/6b72e175-79f5-42fa-acca-9352458c1d96)

I have setup the `fliplr = 0` already. Where am I wrong?

### Additional

ultralytics==8.0.170
Python 3.11.4
OSX: 13.5.1
