### ISSUE TITLE
 'yolov8n-obb.yaml' does not exist

### ISSUE THREAD

**Issue by Yousra442-sheikh** [ultralytics/ultralytics#5183]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am working on dota2 dataset and facing this issue : FileNotFoundError: 'yolov8n-obb.yaml' does not exist

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Yousra442-sheikh thank you for bringing this issue to our attention and for your willingness to contribute to the YOLOv8 project. 

Based on the error you've posted, it seems like the file 'yolov8n-obb.yaml' doesn't exist in your current directory. This YAML file is typically used for model configuration, and the 'FileNotFoundError' indicates that the program can't locate this file in the specified path. 

To fix this issue, please ensure the following: 

1. Check that the file 'yolov8n-obb.yaml' actually exists in your working directory. 

2. If the file exists, confirm that the filename is correctly spelled and matches exactly what is used in your script. Remember, filenames are case sensitive. 

3. Verify the provided path in your script or command. If 'yolov8n-obb.yaml' is not in the same location as your script, you need to provide the full path to the file.

I hope these suggestions assist you in resolving this issue. If these checks don't solve your problem or if you face any other issues, please do not hesitate to describe them here along with any changes you made to our recommended solutions. We appreciate your contribution to the project!

**Comment by RizwanMunawar** [comment]
@Yousra442-sheikh, thank you for the information. It appears that the `yolov8n-obb.yaml` file is not present in your current working directory. To resolve this, you can follow these steps:

**Step 1:** Copy the provided YAML content:

```YAML
# Ultralytics YOLO 🚀, AGPL-3.0 license
# DOTA 2.0 dataset https://captain-whu.github.io/DOTA/index.html for 
# object detection in aerial images by Wuhan University
# Example usage: yolo train model=yolov8n-obb.pt data=DOTAv2.yaml
# parent
# ├── ultralytics
# └── datasets
#     └── dota2  ← downloads here (2GB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) 
# list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/DOTAv2  # dataset root dir
train: images/train  # train images (relative to 'path') 1411 images
val: images/val  # val images (relative to 'path') 458 images
test: images/test  # test images (optional) 937 images

# Classes for DOTA 2.0
names:
  0: plane
  1: ship
  2: storage tank
  3: baseball diamond
  4: tennis court
  5: basketball court
  6: ground track field
  7: harbor
  8: bridge
  9: large vehicle
  10: small vehicle
  11: helicopter
  12: roundabout
  13: soccer ball field
  14: swimming pool
  15: container crane
  16: airport
  17: helipad

# Download script/URL (optional)
download: https://github.com/ultralytics/yolov5/releases/download/v1.0/DOTAv2.zip
```

**Step 2:** Save the copied content as a YAML file named "yolov8n-obb.yaml" in your working directory.

**Step 3:** After saving the file, you can proceed with running the DOTAv2 training using this newly created YAML file.

This should help you set up the necessary configuration for your training. If you encounter any further issues or have additional questions, please feel free to ask.

Thanks
