### ISSUE TITLE
Not enough values to unpack in yolov8-pose 

### ISSUE THREAD

**Issue by Jaykumaran** [ultralytics/ultralytics#5191]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

WARNING ⚠️ No images found in /content/train/labels.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-8-c81b72589279>](https://localhost:8080/#) in <cell line: 5>()
      3 model = YOLO('yolov8n.yaml')
      4 
----> 5 model.train(data='/content/data (1).yaml',epochs=5)

9 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py](https://localhost:8080/#) in get_labels(self)
    120         # Check if the dataset is all boxes or all segments
    121         lengths = ((len(lb['cls']), len(lb['bboxes']), len(lb['segments'])) for lb in labels)
--> 122         len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
    123         if len_segments and len_boxes != len_segments:
    124             LOGGER.warning(

ValueError: not enough values to unpack (expected 3, got 0)

my data.yaml

test: /content/train/images
train: /content/train/images
val: /content/train/images
# Classes
names:
  0: joints

# Keypoints
kpt_shape: [3, 3]

my yolo annotation file 
0 0.485896 0.332236 0.255865 0.248009 0.357964 0.351019 2 0.545229 0.208231 2 0.613828 0.456241 2 

Request for a detailed blog or tutorial or git regarding the custom keypoint training without error @Glen @RizwanMunawar 

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('yolov8n.yaml')

model.train(data='/content/data (1).yaml',epochs=5)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@Jaykumaran, thank you for sharing the information. It appears that the dataset format may not be correct. I typically utilize the provided `data.yaml` file for pose estimation, and it works effectively.

**Sample `data.yaml`**

```yaml
path: "ultralytics\\Dataset"
train: images\\train
val: images\\val
test: 

kpt_shape: [12, 3]
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
names:
  0: lion
```

Based on the information in this `data.yaml` file, it's essential to ensure that your labels are located at the following paths: `ultralytics\\Dataset\\labels\\train` for the training set and `ultralytics\\Dataset\\labels\\val` for the validation set.

A modified version of your `data.yaml` file could look like this:

```yaml
path: "path to the folder where train and val folders exist"
test: images\\test
train: images\\train
val: images\\val

names:
  0: joints

kpt_shape: [3, 3]
```

Please make sure to adjust your `data.yaml` file accordingly. 

We have already included a documentation section dedicated to training pose models on custom data. You can access it by following this link: [Training Pose Models on Custom Data](https://docs.ultralytics.com/tasks/pose/#train).

Hope this helps! Let me know if you have any additional questions.
Thanks
