### ISSUE TITLE
datasets_dir in settings.yaml should be relative, not absolute

### ISSUE THREAD

**Issue by Liquidmasl** [ultralytics/ultralytics#6371]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I describe my issues in detail here: https://github.com/ultralytics/ultralytics/issues/6367

the bug is that the dataset folder dir in the settings.yaml is set automatically to an absolut path with a fixed folder name, this leads to a number of issues and is inconsistant in comparison with weights_dir and runs_dir

### Minimal Reproducible Example

```py
from ultralytics import YOLO


model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="datasets/fire-ext/fire-ext.yaml", epochs=3)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
results = model("path/to/test_img")  # predict on an image
path = model.export(format="onnx")  # export the model to ONNX format
```

where as 
fire-ext.yaml is
```yaml
train: ./train/images
val: ./valid/images
test: ./test/images

nc: 1
names: ['Fire-extinguisher']

roboflow:
  workspace: projet-3a
  project: fire-extinguisher-detection
  version: 5
  license: CC BY 4.0
  url: https://universe.roboflow.com/projet-3a/fire-extinguisher-detection/dataset/5
```

and the folder structure is:

```
|   dockerfile
|   yolo.py
|   yolov8n.pt
|   
\---datasets
    \---fire-ext
        |   .gitignore
        |   fire-ext.yaml
        |   README.dataset.txt
        |   README.roboflow.txt
        |   
        +---test
        |   +---images
        |   |
        |   \---labels
        +---train
        |   +---images
        |   |       
        |   \---labels
        |           
        \---valid
            +---images
            |       
            \---labels
  
```

or just use this dockerfile:

```
FROM ultralytics/ultralytics:latest

WORKDIR /workspace

COPY . .
ENTRYPOINT ["python3", "yolo.py"]
```

The Dataset:
https://universe.roboflow.com/projet-3a/fire-extinguisher-detection
( i manually included the missing splits )

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
