### ISSUE TITLE
copy_paste for detection 

### ISSUE THREAD

**Issue by wsy-yjys** [ultralytics/ultralytics#6590]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is copy_paste data augmentation available for detection tasks, or only for segmentation tasks？

![image](https://github.com/ultralytics/ultralytics/assets/78601159/651afcfc-5faa-4882-ab6b-4e4952116d8e)

**Comment by glenn-jocher** [comment]
@wsy-yjys hello there! 👋

Copy-paste data augmentation is indeed a powerful technique for object detection tasks. In YOLOv8, we've incorporated different data augmentation strategies to improve the model's generalization capabilities, and copy-paste is among those strategies that can be applied to detection tasks. It functions by copying objects from some images and pasting them onto others, providing additional diversity in training data which can be particularly beneficial when dealing with objects that present in various contexts or with limited dataset size.

To use copy-paste augmentation during training, simply ensure that your data configuration is appropriately set up, and the model will apply this strategy alongside other augmentations during the training process.

Feel free to refer to the [Ultralytics Docs](https://docs.ultralytics.com) for more detailed information on data augmentation and training best practices.

Happy training! 🚀

**Comment by wsy-yjys** [comment]
Thank you for your reply. Does copy_patse require a label with data set segmentation

**Comment by glenn-jocher** [comment]
@wsy-yjys you're welcome! No, the copy-paste augmentation for detection tasks does not necessarily require a dataset with segmentation labels. It primarily operates on bounding box annotations, which are standard for detection tasks. The augmentation process will select objects based on their bounding boxes from various images and paste them onto others to enrich the training samples.

This means you can utilize the copy-paste augmentation with your existing bounding box labeled datasets. Just ensure your dataset is properly annotated for detection, and YOLOv8 will handle the augmentation internally as part of its training process.

If you have any further questions or need more clarity, don't hesitate to dive into the [Ultralytics Docs](https://docs.ultralytics.com) or reach out again. Good luck with your projects! 🌟

**Comment by wsy-yjys** [comment]
Thank you very much. I have two more questions for you：
(1) Why are the default data augmentation methods the following, mixup and copy_paste not enable in default?
```yaml
hsv_h: 0.015  # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # (float) image HSV-Value augmentation (fraction)
degrees: 0.0  # (float) image rotation (+/- deg)
translate: 0.1  # (float) image translation (+/- fraction)
scale: 0.5  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.0  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # (float) image flip up-down (probability)
fliplr: 0.5  # (float) image flip left-right (probability)
mosaic: 1.0  # (float) image mosaic (probability)
mixup: 0.0  # (float) image mixup (probability)
copy_paste: 0.0  # (float) segment copy-paste (probability)
```
(2) which of the above methods will hurt the performance of small models
