### ISSUE TITLE
Dataset YAML file support for classification tasks

### ISSUE THREAD

**Issue by JCab09** [ultralytics/ultralytics#6874]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Classification tasks should accept a dataset YAML file for training the same way detect and segment do.

e.g.: `ultralytics mode=classify task=train model=<model> data=<path/to/dataset.yaml>`

with the dataset YAML file looking something like like this:
```YAML
path: /root/path/dataset
train: train/images  # With subfolders IO and NIO
val: val/images  # With subfolders IO and NIO
test: test/images  # With subfolders IO and NIO

nc: 2
names: ['IO', 'NIO']
```

### Use case

Uniform dataset preparation and task execution over all modes (detect, segment and classify).

More flexibility for dataset handling when using classification tasks

### Additional

Feature request arose from issue #6818

My short investigation on this matter https://github.com/ultralytics/ultralytics/issues/6818#issuecomment-1845199849:  
> After checking the `BaseTrainer` class it looks like there is no support for specifying the dataset structure with a YAML file when doing classification tasks. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/trainer.py#L113-L118
> 
> The `check_cls_dataset` function checks if the dataset argument points to a directory and if not, it appends '.zip' and tries to download it. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/utils.py#L354-L365
> 
> The `check_det_dataset` function on the other hand does support YAML files. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/utils.py#L237

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
