### ISSUE TITLE
add albumentations to conf.yaml file

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#7707]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to change the albumentations parameters in conf file and how the structure will looks like.

is it like this structure? 

albumentations: 
    MedianBlur: 0.01
    ..
   ..

regards,

**Comment by glenn-jocher** [comment]
@osamaalschame hello! To adjust the albumentations parameters in the `conf.yaml` file for YOLOv8, you'll want to specify them under the `augment` section. The structure you've provided is on the right track. You'll list each augmentation you want to use as a key, followed by its parameters in a nested structure. For example:

```yaml
augment:
  Albumentations:
    MedianBlur:
      p: 0.01
      blur_limit: (3, 7)
    # Add other augmentations here in a similar fashion
```

Make sure to maintain proper indentation as YAML is sensitive to it. For more details on the specific parameters you can set for each augmentation, please refer to the Ultralytics Docs. 😊
