### ISSUE TITLE
Model is only predicting square bboxes in segmentation

### ISSUE THREAD

**Issue by pg37013** [ultralytics/ultralytics#7988]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone,

I used a pretrained model, `yolov8n-seg.pt`, to train a model to perform segmentation, and used the following configuration:

``` yaml
task: segment
mode: train
model: yolov8n-seg.pt
data: config.yaml
epochs: 200
time: null
patience: 20
batch: 64
imgsz: 512
save: true
save_period: -1
cache: false
device: 0
workers: 1
project: null
name: train22
exist_ok: false
pretrained: true
optimizer: auto
verbose: true
seed: 0
deterministic: true
single_cls: true
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.2
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.05
hsv_s: 0.5
hsv_v: 0.2
degrees: 10
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
```

Although the segmentation is having the expected behavior, it seems that the model is only considering squared bounding boxes. I'm getting this:

![port_0allergy-cold-disease-flu-41284](https://github.com/ultralytics/ultralytics/assets/43340476/0e3fd29b-d682-4d17-b7a2-29ab400b8bb3)

But I want to have this instead:
![port_0allergy-cold-disease-flu-41284](https://github.com/ultralytics/ultralytics/assets/43340476/f0ca3017-44fd-4e99-88cc-9d6d444ffe28)

I already try to train a model setting `rect=True` but this didn't solve the problem. What am I doing wrong?

Can someone help me, please?
