### ISSUE TITLE
Need more details regarding the `data` option when training for detection

### ISSUE THREAD

**Issue by AlainPilon** [ultralytics/ultralytics#8103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you give more information regarding the `data` option when training a detection model? On this page https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings is says: 

Key	Value	Description
data	None	path to data file, i.e. coco128.yaml

So it seems the dataset file structure is not restricted to the val/train folders with the images/labels sub folders. Is that right? If so, what are the supported formats?

**Comment by glenn-jocher** [comment]
@AlainPilon the `data` option specifies the path to a YAML file that contains dataset details for training. The YAML file should define the dataset structure, including paths to train and val directories, class names, and optionally test directories and additional parameters. The structure is not restricted to specific subfolders, but it should be clearly defined in the YAML file.

Supported formats for the dataset are images and annotations in YOLO format, with images typically in common formats like JPG or PNG, and annotations as text files with one row per object.

Here's an example of a simple dataset YAML:
```yaml
# Dataset YAML example
train: /path/to/train/images  # directory containing training images
val: /path/to/val/images      # directory containing validation images
nc: 80                        # number of classes
names: ['class1', 'class2', ...]  # list of class names
```

For more details on custom datasets and YAML structure, please refer to our documentation on [Training on Custom Data](https://docs.ultralytics.com/tutorials/train-custom-dataset/). 📘
