### ISSUE TITLE
.yaml file to point Images and labels which are at different locations

### ISSUE THREAD

**Issue by AdityaNikhil** [ultralytics/ultralytics#8254]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I would like to train a YOLOv8 model such that maintaining images and labels in a totally different directories. Unlike the following structure, 

### Traditional YOLOv8 dataset structure
```
dataset/train
     Cats_Dogs/
          images/
          labels/
```

### Expected YOLOv8 dataset structure
```
Dataset/                         ---> Images Directory
        Cats_Dogs/
               images/

Dataset/Some/Random/Path/        ---> Labels Directory at a different location
          Cats_Dogs/
                  Labels/
```

Now how do I define my `.yaml` file pointing images and labels at different locations?
Explain by providing an example definition of the `.yaml` file.

`Note: I have checked similar issues possible but couldn't find an appropriate solution. Hence, I raised an issue here.`

Thank You!

**Comment by glenn-jocher** [comment]
@AdityaNikhil hi there! 👋

You can definitely specify different directories for your images and labels in your `.yaml` file. Here's an example of how you can set it up:

```yaml
# dataset.yaml
train: Dataset/Cats_Dogs/images  # directory containing training images
val: Dataset/Cats_Dogs/images    # directory containing validation images

# Specify the full path to the labels directories
train_labels: Dataset/Some/Random/Path/Cats_Dogs/labels
val_labels: Dataset/Some/Random/Path/Cats_Dogs/labels
```

Make sure to use the `train_labels` and `val_labels` keys to point to your labels directories. The YOLOv8 training pipeline will automatically pair each image with its corresponding label file based on matching filenames.

Happy training, and let us know if you have any more questions! 😊

**Comment by AdityaNikhil** [comment]
Thanks for sharing. It works like a charm!!!
I'd like to know more keys/arguments that we can define in a .yaml file. 
Can you please share a link if there's any to learn more?

Thanks!

**Comment by AdityaNikhil** [comment]
Hey @glenn-jocher ,

I see that a new issue arises. I am trying to maintain just one image directory folder that contains all the images of cats and dogs. 
The number of imgs for traininig and testing is specified by the `train_labels` and `val_labels`. While training the images are getting loaded but for the labels, its showing a warning stating that,

`No labels found in detect set, can not compute metrics without labels`.


How can I direct the `.yaml` file to the `train_labels` and `val_labels` while maintaining just one image directory?

**Comment by glenn-jocher** [comment]
@AdityaNikhil to train a YOLOv8 model with images and labels located in different directories, you can specify the paths to these directories separately in your dataset `.yaml` file. Here's an example of how you might structure your `.yaml` file to point to the different locations for images and labels:

```yaml
# Example dataset.yaml
path: ./  # root dir
train: Dataset/Cats_Dogs/images  # train images (relative to 'path')
val: Dataset/Cats_Dogs/images  # val images (relative to 'path'), can be the same as train or different
test:  # test images (optional)

# Classes
nc: 2  # number of classes
names: ['Cat', 'Dog']  # class names

# Directories to save labels
train_labels: Dataset/Some/Random/Path/Cats_Dogs/labels  # train labels
val_labels: Dataset/Some/Random/Path/Cats_Dogs/labels  # val labels
```

In the above `.yaml` file, `train` and `val` are set to the paths where the images are located, while `train_labels` and `val_labels` are custom fields that you can use to specify where the corresponding labels are located.

However, YOLOv8 expects the labels to be in the same directory as the images by default. To accommodate the custom label paths, you would need to modify the data loading code in the YOLOv8 repository to use `train_labels` and `val_labels` paths when loading label files.

Here's a high-level overview of the steps you would need to take:

1. Fork the YOLOv8 repository so you can make changes to the code.
2. Find the data loading script, which is typically responsible for parsing the dataset `.yaml` file and loading images and labels.
3. Modify the script to check for the existence of `train_labels` and `val_labels` in the `.yaml` file.
4. Update the label loading logic to use the custom paths if they are provided.

Please note that this approach requires changes to the YOLOv8 codebase and is not supported out-of-the-box. If you're not comfortable making these changes, you might consider creating symbolic links or copying the label files to the expected locations within the image directories.
