### ISSUE TITLE
Training yolov8 on one class

### ISSUE THREAD

**Issue by adeelhasan19** [ultralytics/ultralytics#8497]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I train the yolov8 object detection model only on a single class,
if not, then how can I label the 2nd class because concerned object will not be present in the image

**Comment by glenn-jocher** [comment]
@adeelhasan19 absolutely, you can train YOLOv8 on a single class! 🚀 When preparing your dataset, simply label the objects of interest with your single class, and ensure your dataset configuration file (`*.yaml`) reflects that you have only one class. Here's a quick example of how your dataset configuration might look:

```yaml
# example.yaml
train: /path/to/train/images
val: /path/to/val/images

nc: 1  # number of classes
names: ['your_class_name']
```

And then, you can start training with:

```bash
yolo detect train data=example.yaml model=yolov8n.yaml
```

No need to worry about labeling a second class if it's not present in your images. Just focus on accurately labeling the class you're interested in. Happy training! 🎉
