### ISSUE TITLE
Yolov8: Wrong image size?

### ISSUE THREAD

**Issue by lesept777** [ultralytics/ultralytics#8938]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 
I train my model using images of size (320, 320):
`results = model.train(data='./data_div3', epochs=50, imgsz=320, cos_lr=True, lr0=0.002, batch=-1, optimizer='AdamW', augment=False, auto_augment=None)`

After that I run an inference on a few test images. They are generated on the fly from wav files as follows:
```
        sp = librosa.feature.melspectrogram(y=son, sr=sr)
        spec = librosa.amplitude_to_db(sp, ref=1.0)
        spec = (spec - min) / (max - min) * 255
        spec = spec.astype('uint8')
        img = Image.fromarray(spec, mode="L")
        img = ImageOps.colorize(img, black="red", mid="green", white="blue")
        img = img.resize((320,320))
...
        img.save(savefile)
```
Immediately after that, I run the inference:
`pred = model(savefile)`

I get some output as follows, which shows an image size of (640, 640):

> image 1/1 /data1/Yolo/wav_1.jpg: **640x640** 3 0.24, 5 0.19, 8 0.17, 2 0.09, 9 0.08, 2.4ms

If I check the size of the image file wav_1.jpg, it indeed displays 320 x 320.

So does the model convert it to 640 x 640, or is just a weird message that I shouldn't bother about? 
Or should I force the image size in the yaml file of the model somewhere?

```
# Ultralytics YOLO ??, AGPL-3.0 license
# YOLOv8-cls image classification model. For Usage examples see https://docs.ultralytics.com/tasks/classify

# Parameters
nc: 10 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.30, 0.20, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 1024]
  l: [1.00, 1.00, 1024]
  x: [1.00, 1.25, 1024]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8  # Passer à 210 !
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]

# YOLOv8.0n head
head:
  - [-1, 1, Classify, [nc]] # Classify
```

BTW, what do all these numbers mean, just after the image size? 

> 3 0.24, 5 0.19, 8 0.17, 2 0.09, 9 0.08, 2.4ms
