### ISSUE TITLE
Problems with loading trained model to TensorFlow (web)

### ISSUE THREAD

**Issue by nazersrewel** [ultralytics/ultralytics#8972]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We succeeded trained our model and we exported from ultralytics docker to tfjs format. But the model does not work when we try to use it in [yolov8-tfjs](https://github.com/Hyuto/yolov8-tfjs) example.

### Additional

error message:
```js
Uncaught (in promise) Error: Error in slice3D: begin[2] + size[2] (84) would overflow input.shape[2] (7)
    at assert (chunk-W43QHE4A.js?v=37c0e35c:1723:11)
    at Object.assertParamsValid (chunk-W43QHE4A.js?v=37c0e35c:6513:5)
    at Object.slice3 [as kernelFunc] (chunk-W43QHE4A.js?v=37c0e35c:22738:22)
    at kernelFunc (chunk-W43QHE4A.js?v=37c0e35c:3773:22)
    at chunk-W43QHE4A.js?v=37c0e35c:3816:21
    at Engine.scopedRun (chunk-W43QHE4A.js?v=37c0e35c:3691:19)
    at Engine.runKernelFunc (chunk-W43QHE4A.js?v=37c0e35c:3811:10)
    at Engine.runKernel (chunk-W43QHE4A.js?v=37c0e35c:3732:17)
    at slice_ (chunk-W43QHE4A.js?v=37c0e35c:7707:17)
    at slice__op (chunk-W43QHE4A.js?v=37c0e35c:4349:22)
```
our files:
![image](https://github.com/ultralytics/ultralytics/assets/87078473/90079af2-292e-48de-81ca-19ebe1fdaa1c)

our metadata:
```yaml
author: Ultralytics
date: '2024-03-15T15:54:05.244556'
version: 8.1.27
license: AGPL-3.0 License (https://ultralytics.com/license)
docs: https://docs.ultralytics.com
stride: 32
task: detect
batch: 1
imgsz:
- 640
- 640
names:
  0: id-card
  1: mrz2
  2: mrz3
```
