### ISSUE TITLE
Using custom COCO dataset to train model

### ISSUE THREAD

**Issue by RPalmr** [ultralytics/ultralytics#9161]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, is it possible to train a YoloV8 model on a custom COCO dataset in this format? - 

`{
  "images": [
    {
      "id": 13004,
      "license": 1,
      "file_name": "/path/to/image1.jpg",
      "height": 2168,
      "width": 3848,
      "date_captured": "2020-11-20T08:21:10.334962+0000"
    },
    {
      "id": 34227,
      "license": 1,
      "file_name": "/path/to/image2.jpg",
      "height": 2168,
      "width": 3848,
      "date_captured": "2020-12-09T06:23:07.440353+0000"
    },
    {
      "id": 40125,
      "license": 1,
      "file_name": "/path/to/image3.jpg",
      "height": 2168,
      "width": 3848,
      "date_captured": "2021-04-21T10:45:53.557586+0000"
    },
    {
      "id": 94219,
      "license": 1,
      "file_name": "/path/to/image4.jpg",
      "height": 2168,
      "width": 3848,
      "date_captured": "2020-02-18T09:09:10.669984+0000"
    },`
    
    
 Or are there any scripts to convert this to Yolo txt format please? I have tried JSON2YOLO but I am not having any luck.

**Comment by glenn-jocher** [comment]
@RPalmr hello! 👋 Yes, you can definitely train a YOLOv8 model on a custom COCO dataset. The format you've shown is the standard COCO format for the images section. YOLOv8 can automatically handle this format during training by specifying the correct paths in your dataset YAML file. 

For your COCO dataset, ensure you have a YAML file like this:

```yaml
# dataset.yaml
train: /path/to/your/train/images  # directory to train images
val: /path/to/your/val/images  # directory to val images

# COCO json annotation files
train_ann: /path/to/your/train/annotations.json
val_ann: /path/to/your/val/annotations.json

nc: 80  # number of classes
names: [ 'class1', 'class2', ..., 'class80']  # class names
```

Then you can train your model using:

```bash
yolo train model=yolov8n.pt data=dataset.yaml
```

No need to convert to YOLO txt format for training, as YOLOv8 directly supports COCO JSON format. 🎉 If you encounter issues with JSON2YOLO or have specific needs not met by direct COCO JSON training, could you share more details so we can help further? 

Happy training!

**Comment by RPalmr** [comment]
Thank you so much Glenn. Have a great day.

**Comment by RPalmr** [comment]
Hey Glenn, thanks for your reply. My dataset.yaml folder is set exactly like the example you gave. I have extracted the images  as .jpg format into train and val folders respectively. I have set the train_ann and val_ann as the coco file. Though, when I run `yolo train model=yolov8n.pt data=dataset.yaml`, the training images are all recognised as backgrounds by yolo. Does this mean that yolo recognises the images as un-annotated?

**Comment by glenn-jocher** [comment]
@RPalmr hey there! 🌟 It sounds like you've set up your `dataset.yaml` correctly. If YOLO is recognizing all images as backgrounds, it likely means it's not correctly parsing your annotations.

For COCO datasets, it's perfectly fine to have all annotations in a single file. YOLOv8 should automatically handle this as long as the paths in your `dataset.yaml` point correctly to where your single COCO formatted annotation file for both training and validation is located.

Please double-check the `train_ann` and `val_ann` paths in your `dataset.yaml` file to ensure they accurately point to your COCO annotation file. If your training and validation images are sharing the same annotation file, make sure the IDs in the dataset correctly match those specified in the annotation.

```yaml
train_ann: /path/to/your/annotations.json
val_ann: /path/to/your/annotations.json
```

Remember, the dataset loader will filter out the relevant annotations for each image based on the `image_id` provided in the COCO JSON. If the paths and IDs are correctly set, YOLOv8 will properly recognize and use those annotations rather than defaulting to treating all images as having no annotations. 

Let me know if this helps or if you're still encountering issues!

**Comment by JosueDavalos** [comment]
Hi @glenn-jocher 

I am experiencing the same problem. I want to use my annotations in COCO format and I see that all images are detected as **background** and the loss and performance of the model is 0.
 
I am trying to train an intance segmentation model that detects only one class using google colab. Can you help me to detect and solve my problem. Here I attach details of the configuration I have. As you will see, for practical purposes, I am using the same dataset to train and validate.

I also tried adding the full path to the images (for example: from  ` "file_name": "1.jpg"` to ` "file_name": "/content/drive/MyDrive/folder_1/project_folder/images/1.jpg"`), thinking this was the problem, but I still get the same result


```json
{
  "images": [
    {
      "license": 0,
      "file_name": "1.jpg",
      "coco_url": "n/a",
      "height": 1520,
      "width": 2688,
      "date_captured": "",
      "flickr_url": "n/a",
      "id": 1149177037,
      "tag_ids": []
    },
    {
      "license": 0,
      "file_name": "2.jpg",
      "coco_url": "n/a",
      "height": 1520,
      "width": 2688,
      "date_captured": "",
      "flickr_url": "n/a",
      "id": 478292595,
      "tag_ids": []
    },
    ......
  ],
  "annotations": [
    {
      "id": 1,
      "image_id": 478292595,
      "category_id": 886886774,
      "segmentation": [[1367.0, 496.0, 1379.0]],
      "area": 24697.50390111655,
      "bbox": [1199.0, 496.0, 217.0, 237.0],
      "iscrowd": 0,
      "extra": {}
    },
    {
      "id": 2,
      "image_id": 478292595,
      "category_id": 886886774,
      "segmentation": {
        "counts": [2349218, 18, 1498],
        "size": [1520, 2688]
      },
      "area": 89721.0,
      "bbox": [1545, 554, 286, 642],
      "iscrowd": 1,
      "extra": {}
    },
    ......
  ]
}

```

```yaml
train: /content/drive/MyDrive/folder_1/project_folder/images
val: /content/drive/MyDrive/folder_1/project_folder/images

# COCO json annotation files
train_ann: /content/drive/MyDrive/folder_1/project_folder/labels.json
val_ann: /content/drive/MyDrive/folder_1/project_folder/labels.json

nc: 1
names: ["class_name"]
```

```python
model = YOLO('yolov8n-seg.pt')

dataset_path = '/content/drive/MyDrive/folder_1/project_folder/security-cam.yaml'
results = model.train(
    data=dataset_path,
    project="people-tracking",
    name="baseline",
    single_cls=True,
    plots=True,
    epochs=2,
    imgsz=640,
)
```
