### ISSUE TITLE
Getting half of the feature map from the previous layer 

### ISSUE THREAD

**Issue by RezaHajimohammadi** [ultralytics/ultralytics#9358]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, i am developing my custom backbone in yaml model file, i need to get half of the feature map in depth from previous layer and next in future layer concatenate with the other half, how can i do this? What block with what arguments should I use? Thanks
![Screenshot 2024-03-27 155626](https://github.com/ultralytics/ultralytics/assets/106597793/f796e34c-fdd9-4862-8f5b-e1b330fd9bd1)

**Comment by glenn-jocher** [comment]
@RezaHajimohammadi hello! It sounds like you're working on an interesting customization for your model. To achieve the operation where you split the feature map and later concatenate it, you can use custom modules in your YAML file designed for slicing and concatenation.

Assuming you've already defined a custom module in your implementation to handle slicing (let's call it `Slice`) and another for concatenation (`Concat`), your YAML could look something like this:

```yaml
# Example custom block definitions (Pseudo code)
layers:
  - id: layer_x
    type: Conv
    ...
  - id: slice_half
    type: Slice
    inputs: [layer_x]
    args: {start:0, end: half_of_depth} # Indicate how you determine this split
  ...
  - id: another_layer
    type: Conv
    inputs: [slice_half]
    ...
  - id: concat_layer
    type: Concat
    inputs: [slice_half, another_layer]
    ...
```

🚀 Make sure to adjust the `args` with precise slicing logic as per your requirement and replace `half_of_depth` with actual depth calculation based on your layer's feature map depth.

If you haven't yet implemented custom modules like `Slice` or `Concat`, you might need to dive into the model's source code to create functionality that meets your needs. Don't hesitate to refer to the PyTorch documentation for `torch.cat` function for concatenation and slicing with PyTorch tensor indexing for splitting the feature maps!

Hope this helps a bit! Keep innovating 💡 and feel free to share more about how it goes!
