### ISSUE TITLE
Adding parameters to yaml file

### ISSUE THREAD

**Issue by ChinmayBH** [ultralytics/ultralytics#9461]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a question. Can I add epochs and other hyperparameters in yaml file to execute training? because I have seen projects where only at a training command the parameters were added not in yaml. Can we do that? and if yes then how to add? Thanks in advance.

**Comment by glenn-jocher** [comment]
@ChinmayBH hello! Thank you for reaching out with your question. 😊

Indeed, you can include various parameters, such as epochs and other hyperparameters, directly in your YAML file when training with YOLOv8. This approach can help streamline the training command by having predefined settings.

Here's a quick example of how you might structure your YAML file to include such parameters:

```yaml
# Example training YAML configuration
nc: 80 # number of classes
epochs: 100 # number of training epochs
batch_size: 16 # batch size
img_size: 640 # image size
...

# Hyperparameters (optional, if you want to customize)
lr0: 0.01 # initial learning rate
momentum: 0.937 # optimizer momentum
weight_decay: 0.0005 # weight decay
...
```

Then, when you're ready to train, you can simply reference this YAML file:

```bash
yolo train data=my_training_config.yaml model=yolov8n.yaml
```

This setup allows you to adjust training parameters without modifying your command line input directly. Keep exploring and experimenting with configurations that best fit your project needs! If you have further questions or need more detailed examples, feel free to ask. Happy training! 🚀

**Comment by ChinmayBH** [comment]
Thanks @glenn-jocher ! Please guide on the below questions also.
1. While using a custom config file can we add new parameters to the file so that we can use it for some other tasks such as data splitting as well?
2. Is it possible to add new parameters that are not already present in the default yaml file? I have already tried adding the parameters and was checking by passing the custom file through the cfg parameter in the training command but got an error for the new parameter.
This will help me to work on custom data and custom model training.

**Comment by glenn-jocher** [comment]
@ChinmayBH hey there! 😊 Absolutely, glad to assist with your questions.

1. You can indeed add new parameters to your custom config file for various tasks like data splitting. Just ensure that these parameters are correctly handled in your code or scripts that process the YAML file.
   
2. While you can add new parameters, the YOLOv8 training script might throw errors if it encounters unknown parameters directly within the training process. If these new parameters are for external tasks (not directly consumed by the YOLOv8 training process), you might consider segregating them in a separate section of your YAML or handling them with custom code logic.

Here's a small code snippet on handling custom parameters in Python, assuming you segregate them under a `custom_params` key in your YAML:

```yaml
# In your YAML
nc: 80
epochs: 100
...
custom_params:
  split_ratio: 0.8
  additional_param: value
```

```python
import yaml

with open("my_custom_config.yaml", 'r') as stream:
    try:
        config = yaml.safe_load(stream)
        # Now you can access your custom parameters like so:
        split_ratio = config['custom_params']['split_ratio']
        print(split_ratio)
    except yaml.YAMLError as exc:
        print(exc)
```

Just ensure any custom logic for these parameters is implemented in your project. Hope this clears things up! Keep pushing through with your custom training endeavors. 👍
