### ISSUE TITLE
Training with 80 classes

### ISSUE THREAD

**Issue by ZeeRizvee** [ultralytics/ultralytics#951]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train YOLO v8 on my custom dataset, using all 80 classes. However, whenever the training starts, it first discards all training images with class greater than 14, saying (for example) "Label class 78 exceeds dataset class count 15. Possible class labels are 0-14". The architecture does display classes to be 80 in the final layer, but I'm not sure why it still overrides it after the 'optimizer' step and forces classes to be 15. I have set nc to 80 in my yaml file which I am directing the code to. I tried both with yolov8n.pt and yolov8l.pt and the issue remains the same. Can you please guide over this?

**Comment by Laughing-q** [comment]
@ZeeRizvee please provide more info .i.e data.yaml, training command and package version, then we're able to reproduce the issue. :)

**Comment by glenn-jocher** [comment]
@ZeeRizvee nc is no longer read from data.yaml files. Class counts are read directly from your `names` dictionary, i.e.:

```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush
```
