### ISSUE TITLE
How does yolov8s-world extend custom identification label?

### ISSUE THREAD

**Issue by lizhiwen19900709** [ultralytics/ultralytics#9986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How does yolov8s-world extend custom identification label?

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 hey there! 🚀 Extending YOLOv8s-world with custom identification labels involves a few steps, including updating your dataset and training your model with this dataset. Essentially, you'll need to:

1. Prepare your dataset with images annotated with your custom labels.
2. Update your dataset config file (`*.yaml`) to include these new classes.
3. Train your YOLOv8s-world model using this updated dataset.

Here's a quick example on how to specify your custom classes in the dataset config file:

```yaml
# example_dataset.yaml
train: ../train/images
val: ../val/images

nc: 5  # number of classes
names: ['label1', 'label2', 'label3', 'label4', 'label5']
```
And then, train your model by pointing to this config file:

```bash
yolo detect train data=example_dataset.yaml model=yolov8s-world.pt
```

Make sure your annotations and dataset are correctly formatted based on the YOLOv8 requirements. Happy training! 😊
